### ISSUE TITLE
`doctl compute droplet create --wait` is not waiting long enough 

### ISSUE THREAD

**Issue by samuelstroschein** [digitalocean/doctl#1003]
**Describe the Issue:**

I am using GitHub workflows to provision new droplets. After creating the droplet and trying to SSH into it, I always got a connection refused' error. Trying to SSH into the newly created droplet on my local machine worked. Therefore, I thought it had to do with the GitHub environment. Turns out the --wait flag simply does not wait till the server is ready to accept a connection which I expected. It might be no bug but either clearly mention it in the documentation or change the --wait flag to test whether the droplet is ready to accept a connection. The workaround is to naively wait for X seconds after the droplet has been created. 

**Environment:**

 - digitalocean/action-doctl@v2.1.0
 - runs-on: ubuntu-latest

**Comment by danaelhe** [comment]
Hi there,

Thank you for the write up. We merged #1498  PR that offers a work around with the `doctl compute ssh <droplet-id>`command by adding a `--ssh-retry-max` flag . This flag will retry for a successful connection to the droplet a certain amount of times before returning control to the user. I tested it out with a bash script and it consistently worked well. If you need anything else, please open another issue.
