### ISSUE TITLE
Help for 'kubeconfig save' is incomplete 

### ISSUE THREAD

**Issue by andrewsomething** [digitalocean/doctl#1007]
The help for 'kubeconfig save' just kind of trails off... We can do better.

```
$ doctl kubernetes cluster kubeconfig save -h

This command adds the credentials for the specified cluster to your local kubeconfig. After this, your kubectl installation can directly manage your

Usage:
  doctl kubernetes cluster kubeconfig save <cluster-id|cluster-name> [flags]

```

https://docs.digitalocean.com/reference/doctl/reference/kubernetes/cluster/kubeconfig/save/

https://github.com/digitalocean/doctl/blob/343c86e08006c3f27c67f26818bda6926f49e3c5/commands/kubernetes.go#L394-L395

**Comment by danaelhe** [comment]
merged
