### ISSUE TITLE
`doctl auth login` doesn't work on Mac

### ISSUE THREAD

**Issue by zevav** [digitalocean/doctl#101]
Contrary to the tutorial [here](https://www.digitalocean.com/community/tutorials/how-to-use-doctl-the-official-digitalocean-command-line-client), `doctl auth login` only returns `Error: access token is required`, if there's no config file, and doesn't pop open a browser tab.

There is no instruction given in that tutorial as to what key name to use in the config; I randomly guessed `access-token`, which worked.

**Comment by bryanl** [comment]
Hello,

You are correct, the proper key should be `access-token`, and the documentation needs to be updated to reflect this fact. As for `doctl auth login`, the command is set to be replaced with `doctl auth init` #94, and that work will start soon.
