### ISSUE TITLE
Option --droplet-agent false creates a duplicate droplet

### ISSUE THREAD

**Issue by piechologist** [digitalocean/doctl#1018]
Running

`doctl compute droplet create foo --region fra1 --size s-1vcpu-1gb --image fedora-34-x64 --wait --droplet-agent false`

creates two droplets named `foo` and `false` whereas

`doctl compute droplet create bar --region fra1 --size s-1vcpu-1gb --image fedora-34-x64 --wait --droplet-agent=false`

creates only one droplet `bar` as expected. Note the equal sign in the last flag. 

**Environment:**
 - doctl version: doctl version 1.63.1-release
 - macOS 11.5.2 Big Sur 
 - Installation method: Homebrew

**Additional Details:**

`doctl compute droplet create --help` does not mention the equal sign. Also, all other flags do not require it either so, this is quite unexpected behavior.

**Comment by andrewsomething** [comment]
This is the behavior for all boolean flags. `--droplet-agent` by itself means `true`, and `--droplet-agent=false` is needed to disable it. We inherit this from Cobra, the library we use for flags, but it is also the behavior for the `flag` package in the Go standard library. We should find a way to make this more clear in the documentation.

**Comment by piechologist** [comment]
Oh, I see, thank you. Good to have libraries that add more variety to command line options, depending on the internal type of a variable 😉. 

I consulted the man page with `doctl compute droplet create -h` so, including the equal sign there should be sufficient. I hope there are not too many other places in doctl that require boolean arguments...

Anyhow, thank you for maintaining such a powerful tool!

**Comment by andrewsomething** [comment]
With the docs changes in https://github.com/digitalocean/doctl/commit/31ab1c6f1bcd9038394a2d5a74493e3ca72108b4, I'm going to go ahead and close this out.
