### ISSUE TITLE
doctl compute droplet find

### ISSUE THREAD

**Issue by biji** [digitalocean/doctl#102]
please add command: doctl compute droplet find ABCD

To find matching droplet with **partial name** or **ip** or **tags**

**Comment by bryanl** [comment]
Hello,

I believe we'll be able to accomplish the following with the work being done in #95 and #96. Feel free to comment there if you don't think these two additions will be sufficient. 

Also, you can currently filter with partial names and tags using `doctl compute droplet ls`.  E.g.

```sh
$ doctl compute d ls --tag-name frontend # only list droplets tagged with frontend
$ doctl compute d ls 'frontend*' # only list droplets that start that match glob (not regex) 'frontend*'
```

As for public IPv4, you can pipe the output to grep, but that seems less than ideal.  With them template support in in #95, you could accomplish this in a more succinct fashion.
