### ISSUE TITLE
domain record update unexpectedly changes record TTL

### ISSUE THREAD

**Issue by rcj4747** [digitalocean/doctl#1020]
**Describe the Issue:**

I have an existing domain record where I want to update one field, RecordData, but if I don't look up the existing TTL value and specify it during an update it will be changed to [1800](https://github.com/digitalocean/doctl/blob/84fb230735f6e6d0f7636aae8d4cbeb74d931ac7/commands/domains.go#L87).

I would like to run `doctl compute domain records update ${ZONE} --record-id ${REC_ID} --record-data ${NEW_IP}` and have the TTL remain unchanged.

The API documentation for [update_domain_record](https://docs.digitalocean.com/reference/api/api-reference/#operation/update_domain_record) does not indicate that the field is nullable :-( but a test with a value of 0 shows that the existing TTL is preserved.

**Environment:**

 - doctl version: doctl version 1.64.0-release, Git commit hash: 84fb2307
 - OS: Ubuntu 21.04
 - Installation method: Snap package version v1.63.1+git1.84fb2307

**Additional Details:**

Recreate steps:

```
ZONE=do.examplezone.com
RECORD=foo
DATA=192.168.1.1
TTL=600

# Create a record with a custom TTL
$ doctl compute domain records create $ZONE --record-type A --record-ttl $TTL --record-name $RECORD --record-data $DATA
ID           Type    Name    Data           Priority    Port    TTL    Weight
169333525    A       foo     192.168.1.1    0           0       600    0

# Updating a records without specifying TTL changes it to the default of 1800
$ doctl compute domain records update $ZONE --record-id 169333525 --record-data 192.168.1.2
ID           Type    Name    Data           Priority    Port    TTL     Weight
169333525    A       foo     192.168.1.2    0           0       1800    0

# Updating the record requires specification of the desired TTL to maintain its value
$ doctl compute domain records update $ZONE --record-id 169333525 --record-data 192.168.1.2 --record-ttl 600
ID           Type    Name    Data           Priority    Port    TTL    Weight
169333525    A       foo     192.168.1.2    0           0       600    0

# Patch the source for doctl changing the default TTL on updates from 1800 to 0
$ git diff
diff --git a/commands/domains.go b/commands/domains.go
index d5ac511b..24936095 100644
--- a/commands/domains.go
+++ b/commands/domains.go
@@ -84,7 +84,7 @@ func Domain() *Command {
        AddStringFlag(cmdRecordUpdate, doctl.ArgRecordData, "", "", "Record data; varies depending on record type")
        AddIntFlag(cmdRecordUpdate, doctl.ArgRecordPriority, "", 0, "Record priority")
        AddIntFlag(cmdRecordUpdate, doctl.ArgRecordPort, "", 0, "The port value for an SRV record")
-       AddIntFlag(cmdRecordUpdate, doctl.ArgRecordTTL, "", 1800, "The record's Time To Live value, in seconds")
+       AddIntFlag(cmdRecordUpdate, doctl.ArgRecordTTL, "", 0, "The record's Time To Live value, in seconds")
        AddIntFlag(cmdRecordUpdate, doctl.ArgRecordWeight, "", 0, "The weight value for an SRV record")
        AddIntFlag(cmdRecordUpdate, doctl.ArgRecordFlags, "", 0, "An unsigned integer between 0-255 used for CAA records")
        AddStringFlag(cmdRecordUpdate, doctl.ArgRecordTag, "", "", "The parameter tag for CAA records. Valid values are `issue`, `issuewild`, or `iodef`")

# Build
$ docker build --tag=doctl .

# Test
$ docker run --rm --interactive --tty --env=DIGITALOCEAN_ACCESS_TOKEN="nope" doctl compute domain records update $ZONE --record-id 169333525 --record-data 192.168.1.3 
ID           Type    Name    Data           Priority    Port    TTL    Weight
169333525    A       foo     192.168.1.2    0           0       600    0
```

**Comment by danaelhe** [comment]
Thanks for bringing up this issue. You'll see that we've pushed up a PR for this issue #1027 . Once this PR is included in the latest doctl release, you'll need to do one more work around to get the expected behavior. The work around involves editing your doctl config file. Your doctl config file is located in different directories depending on your OS- you can see where your doctl config is located [here](https://github.com/digitalocean/doctl#configuring-default-values). Once you've located your doctl config file, edit the records.update.record-ttl from 1800 to 0, as shown below:
`records:
  create:
    format: ""
    no-header: false
    record-data: ""
    record-flags: 0
    record-name: ""
    record-port: 0
    record-priority: 0
    record-tag: ""
    record-ttl: 1800
    record-type: ""
    record-weight: 0
  delete:
    force: false
  list:
    format: ""
    no-header: false
  update:
    format: ""
    no-header: false
    record-data: ""
    record-flags: 0
    record-id: 0
    record-name: ""
    record-port: 0
    record-priority: 0
    record-tag: ""
    record-ttl: 0
    record-type: ""
    record-weight: 0`

This will get you the expected behavior.
