### ISSUE TITLE
Access to recovery console settings

### ISSUE THREAD

**Issue by jedahan** [digitalocean/doctl#1022]
**What is the problem this feature would solve? Please describe.**
I'd like to script installing a non-containerized operating system on a droplet, using the Recovery ISO. Creating and powering down a droplet is easy, but setting it to boot into recovery iso is not.

**Describe the solution you'd like**
Something like

    doctl droplet tag <droplet-id|droplet-name> recovery-iso
    doctl droplet reboot <droplet-id|droplet-name>

or

    doctl droplet reboot <droplet-id|droplet-name> --recovery-iso

Ideally, it would return the url to open the recovery console in addition to the normal metadata about the droplet

**Comment by danaelhe** [comment]
Hi there,

Thanks for bringing this up. Unfortunately, we don't support this via the API yet. We have relayed your request to Product Management.

**Comment by tagwint** [comment]
Hello, 
Is there any feedback from Product  Management on this, please?
Interested in this option too, so any news would be nice to get
Thank you

**Comment by danaelhe** [comment]
Hi there,

Yes, they've let us know that it's a rather large lift and since it's a rarely-request feature, that they will not be pursuing it at this time.
