### ISSUE TITLE
snapshot help doesn't list required parameters

### ISSUE THREAD

**Issue by jedahan** [digitalocean/doctl#1023]
**Describe the Issue:**

I tried creating a snapshot from the commandline, but it gave me an error message that --snapshot-name was missing. It is also not present in autocomplete for zsh.

**Environment:**
 - doctl version: doctl version 1.64.0-release

 - OS: macOS Big Sur
 - Installation method: Homebrew

**Additional Details:**

```
doctl compute droplet-action snapshot $dropletid
Error: (droplet-action.snapshot.snapshot-name) command is missing required arguments
```

```
doctl compute droplet-action snapshot --help    
Use this command to take a snapshot of a Droplet. We recommend that you power off the Droplet before taking a snapshot to ensure data consistency.

Usage:
  doctl compute droplet-action snapshot <droplet-id> [flags]

Flags:
      --format ID              Columns for output in a comma-separated list. Possible values: ID, `Status`, `Type`, `StartedAt`, `CompletedAt`, `ResourceID`, `ResourceType`, `Region`
  -h, --help                   help for snapshot
      --no-header              Return raw data with no headers
      --snapshot-name string   Snapshot name (required)
      --wait                   Wait for action to complete

Global Flags:
  -t, --access-token string   API V2 access token
  -u, --api-url string        Override default API endpoint
  -c, --config string         Specify a custom config file (default "/Users/micro/Library/Application Support/doctl/config.yaml")
      --context string        Specify a custom authentication context name
  -o, --output string         Desired output format [text|json] (default "text")
      --trace                 Show a log of network activity while performing a command
  -v, --verbose               Enable verbose output
```

**Comment by danaelhe** [comment]
Hi there,

Thanks for the write up. The "required" flags are in the same section as the "flags" section. Typing this out and hitting tab shows --snapshot-name as an autocomplete suggestion in the output in zsh. Hitting tab without anything typed will list commands, but to list flags it seems you need to type -- and then hit tab for it to show them. Could you try that and see if it works as expected?

**Comment by jedahan** [comment]
My bad, I was expecting to see it in the usage line, like 

```
Usage:
  doctl compute droplet-action snapshot <droplet-id> <--snapshot-name string> [flags]
```

Since it is documented, this isn't really a bug. Thanks for your help.

The autocompletion does show --snapshot-name in zsh.
