### ISSUE TITLE
Cannot delete volume using doctl

### ISSUE THREAD

**Issue by patrykcloudmind** [digitalocean/doctl#1037]
Cannot delete volume 

```
doctl compute volume delete pvc-f36b9620-ae36-...............
Warning: Are you sure you want to delete this volume? (y/N) ? y
Error: DELETE https://api.digitalocean.com/v2/volumes/pvc-f36b9620-ae36-...........: 404 (request "47912ca4-3b03-4dc9-bcc6-a4fdd71fdb99") The resource you were accessing could not be found.
```

I am able to delete the PVC using DO console, but I need to do that using script. 

I auth using the following command:
```
| => doctl auth init
Using token [872c00............]

Validating token... OK
```

**Environment:**
 - doctl version 1.64.0-release
 - OS:  macOS Big Sur 11.8
 - Installation method: Homebrew

**Comment by danaelhe** [comment]
Hi there,

The delete command requires the volume-id:
```
 doctl compute volume delete --help
Use this command to delete a block storage volume by ID, destroying all of its data and removing it from your account.

Usage:
  doctl compute volume delete <volume-id> [flags]
```

Looks like you're trying to delete the volume by the volume name and not he volume-id. Could you confirm that?

**Comment by patrykcloudmind** [comment]
Thank you, @andrewsomething. The ID did the trick.
