### ISSUE TITLE
--user-data-file not used?

### ISSUE THREAD

**Issue by zubfatal** [digitalocean/doctl#106]
Created  a droplet with the --user-data-file argument with a local file containing a few lines of shell code, which normally works when used from the control panel. The data doesn't seem to be used.

**Comment by bryanl** [comment]
This is a feature I see used a bunch in `doctl`. Curious to what the first line of the file pointed to by `--user-data-file` looks like.

**Comment by zubfatal** [comment]
Sure thing, this is the entire script, except for the IP addresses :)

```
#!/bin/sh
for X in 1.2.3.4 2.3.4.5 do ; ufw allow from $X to any proto tcp port 22 ; done
sed -r -i 's/^#force_color_prompt=yes/force_color_prompt=yes/' /etc/skel/.bashrc
echo '' >> /root/.bashrc
echo '# Force prompt in other colors for root' >> /root/.bashrc
echo "PS1='\${debian_chroot:+(\$debian_chroot)}\[\033[01;31m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '" >> /root/.bashrc
```

All it does is open SSH for a couple of IPs, enable color prompts for all users created later, and a specific colored prompt for root, not a big secret :)

**Comment by bryanl** [comment]
I ran a test of `doctl compute droplet create` with the `--user-data-file` with success. Curious if there is any clues in `/var/log/cloud-init-output.log`?

**Comment by zubfatal** [comment]
@bryanl argh! sorry for the inconvenience man :( it seems there actually was an error in my stupid script

/var/log/cloud-init-output-log:
```

**Comment by bryanl** [comment]
No problem. Sometimes the details are the killer!
