### ISSUE TITLE
`doctl k8s clusters create --wait --1-clicks` is not waiting long enough

### ISSUE THREAD

**Issue by guidoiaquinti** [digitalocean/doctl#1063]
**Describe the Issue:**
Similar issue as #1003 but related to the 1-click install on Kubernetes. When creating a new cluster and running a 1 click installation, the command returns before the app installation finishes.

**Comment by danaelhe** [comment]
Hi! Thanks for the write up. After the cluster is created, it takes time for the 1-clicks software to be installed as well. The `wait` flag works as expected as it just polls for when the cluster is ready. It currently does not support waiting on the 1-click application install to be ready.
