### ISSUE TITLE
Tag droplet returns 404 error

### ISSUE THREAD

**Issue by zubfatal** [digitalocean/doctl#107]
Running the command:
`doctl compute droplet tag <droplet-name or droplet-id> --tag-name mytag` 

returns the error message:
`Error: POST https://api.digitalocean.com/v2/tags/testing/resources: 404 The resource you were accessing could not be found.`

**Comment by bryanl** [comment]
The tag is required to exist before tagging a resource.

**Comment by zubfatal** [comment]
@bryanl oh! thanks - didn't really know how tagging worked, was just testing, tags aren't visible in the control panel (yet?) anyways.

**Comment by andrewsomething** [comment]
@zubfatal  Right. There are plans to expose them in the control panel, but currently they are API only. You can find out more here:

https://www.digitalocean.com/community/tutorials/how-to-use-droplet-tagging-with-the-digitalocean-api

**Comment by zubfatal** [comment]
@andrewsomething Thanks - yeah i found that link as well, and I can see how it can be useful if you have a bunch of doplets, not sure how it visually would be the best way to group/display the droplets by tag, but I can see the potential in using tags, could be someting like:

```
webservers
     webserver1 x.x.x.x 
     webserver2 x.x.x.x

database-servers
     database1 x.x.x.x
     database2 x.x.x.x
```

Although that would probably be a bit weird grouping if a droplet has both tags..

Do you know if there is a roadmap or something like that, for stuff Digital Ocean is planning to add? (features for droplets, or changes in the control panel, new datacentre or whatever)

**Comment by andrewsomething** [comment]
We don't have a full public roadmap, but we do use UserVoice to track feature requests: https://digitalocean.uservoice.com

**Comment by zubfatal** [comment]
@andrewsomething Cool! thanks - maybe that should be referenced somewhere on the website and/or the control panel? :)
