### ISSUE TITLE
Config initialization failed: open /home/<user>/.config/doctl/config.yaml: permission denied

### ISSUE THREAD

**Issue by rolaca11** [digitalocean/doctl#1074]
**Describe the Issue:**

Any time I want to run any command related to doctl (including kubectl) I get the following error:
`Config initialization failed: open /home/<user>/.config/doctl/config.yaml: permission denied`.

Renewing authentication isn't an option because of #947 

**Environment:**

 - doctl version:  1.68.0-release (22869cba)
 - OS:  Pop!_OS 21.10
 - Installation method: snap

**Additional Details:**

I noticed the issue after upgrading pop os (it has introduced issues with docker as well).
Fun fact: `doctl version` returns the same error message, I could get the version by renaming the file in question

**Comment by rolaca11** [comment]
I did a `snap remove` `snap install`, now any doctl command does literally nothing. It just gets stuck and stays there until I ^C

**Comment by rolaca11** [comment]
I'm sorry for this, but after I turned my computer on this morning, I tried the `doctl auth init` and got the error message that it isn't installed. After sunning snap install again, it seems to be okay now. So it's probably a snap bug or sg...

**Comment by danaelhe** [comment]
Thanks for the update!
