### ISSUE TITLE
[Suggestion] notify/callback option when --wait omitted

### ISSUE THREAD

**Issue by zubfatal** [digitalocean/doctl#108]
This is probably not specific for `doctl` itself, but also the API.
I think it could be useful if you start creating a droplet, and don't want to wait until it's finished, if you could have it notify you by e-mail once it's done creating, or maybe a callback URL?

I'm part of a new startup company located in Denmark, where we're already using Digital Ocean for some of our servers, we do plan to use this for our customers also, although (would be sweet with a Digital Ocean presence in Denmark :)) and as part of a more or less automated deployment is where I think a callback URL option could be useful, it would probably be required to implement this into the API also.

**Comment by aybabtme** [comment]
Hi @zubfatal ! This idea was put forward in https://github.com/digitalocean/api-v2/issues/14 but we don't have ETA for it yet.

**Comment by zubfatal** [comment]
Oh, thanks @aybabtme :)
