### ISSUE TITLE
compute ssk-key import gets permission denied error

### ISSUE THREAD

**Issue by MorKaragh** [digitalocean/doctl#1085]
Greetings.

I have a "permission denied" error when importing ssh key^

> localname@note:~$ sudo doctl compute ssh-key import keyname --public-key-file ~/.ssh/id_rsa.pub
> Error: open /home/localname/.ssh/id_rsa.pub: permission denied

I am sure that I have everything right with permissions for the .pub file

> localname@note:~/.ssh$ ls -lat | grep id_rsa.pub
> -rw-r--r--  1 localname localname  393 Dec 17 22:03 id_rsa.pub

doctl is freshly installed on ubuntu 18.04 with "snap install doctl":

> localname@note:~/.ssh$ doctl version
> doctl version 1.68.0-release
> Git commit hash: 22869cba

What permissions do I need to make it work fine? 
Please, help me to understand.

**Comment by andrewsomething** [comment]
Hi @MorKaragh, 

When using the Snap package, you may need to grant doctl access to you SSH keys:

```
sudo snap connect doctl:ssh-keys :ssh-keys
```

**Comment by MorKaragh** [comment]
Thank you. it helped. I was absolutely sure that I did this before, but it is clear now that I did something wrong.
