### ISSUE TITLE
Confirm before delete droplet

### ISSUE THREAD

**Issue by colkito** [digitalocean/doctl#109]
Feature request: We need a confirmation before delete (or any other critical action) a droplet. 😰

**Comment by snoopdouglas** [comment]
#110 - pull request for this appears to have gone cold

**Comment by xmudrii** [comment]
@bryanl I don't think it is polite to original author, but can someone of us take on this problem? It it already more than 2 months from last activity on #110.
I could do it, make it working and possibly add it to more locations (like deleting volumes, images, etc).

I was also thinking about, something in lines of `assume-yes` config. If it is set to `true` in cfg file, you will not be asked for confirmation (doctl will work in mode like it is now). Maybe it would not be bad for users who can live without it, or use doctl in integration with other tools/scripts

**Comment by bryanl** [comment]
@xmudrii I don't think it would be impolite seeing as #110 has gone code for a while. The only requirement from my point of view would be to ensure it works in interactive and non-interactive settings (eg. in a script and triggered with a flag). As for the configuration item, let's revisit that in a second PR. Personally, I have no problem with it, but I would like to float the idea internally as well.

**Comment by colkito** [comment]
Sorry for my delay! but at the moment I'm overloaded of work and sadly my free time to learn more about GO is very little...
If somebody can finish my PR could be great!
we are all agree about this requested feature, right?
greetings!

**Comment by xmudrii** [comment]
@colkito 
Not a problem, I will have soon a first version on it so will make PR for @bryanl to check if is it ok for now. :)

**Comment by xmudrii** [comment]
@bryanl This should be closed, I fixed it in #109. It should be Fixes, not fixs, at least TIL :P

**Comment by xmudrii** [comment]
@aybabtme @nanzhong I think you can close this, I fixed this in #109
