### ISSUE TITLE
Doctl/API return 404 when Droplet name is just number

### ISSUE THREAD

**Issue by kicaj** [digitalocean/doctl#1106]
When using Doctl, command like `doctl compute droplet get 5942369` always return 404 with message "The resource you were accessing could not be found.".
The problem is when name of droplet is just from numbers.

**Comment by kicaj** [comment]
I can see that it was reported a bit earlier: https://github.com/digitalocean/doctl/issues/1087

**Comment by andrewsomething** [comment]
Closing in favor of #1087
