### ISSUE TITLE
`Fingerprint could not be generated, please make sure your key is valid` while creating ssh-key with doctl

### ISSUE THREAD

**Issue by dipendrachaudhary** [digitalocean/doctl#1110]
Basically I want to use ssh fingerprint for clusterAPI
`export DO_SSH_KEY_FINGERPRINT=<your-ssh-key-fingerprint>`

When I do `doctl compute ssh-key list`, it shows nothing hence there is no key
```
$ doctl compute ssh-key list
ID    Name    FingerPrint
```

So I tried to create ssh-key and it gave me this error
```
$ doctl compute ssh-key  create test --public-key id_rsa
Error: POST https://api.digitalocean.com/v2/account/keys: 422 (request "54f71bbf-25ec-4abd-89b8-6071adc05eb1") Fingerprint could not be generated, please make sure your key is valid
```

**Comment by scotchneat** [comment]
@dipendrachaudhary Typically the `id_rsa` file is the private key which usually has a `id_rsa.pub` file containing the public respective public key. It looks like you might be sending the private key for the `--public-key` flag. 
Try changing this to `--private-key id_rsa.pub` instead and let us know if you're still seeing issues.
