### ISSUE TITLE
image on docker hub seems to be dysfunctional

### ISSUE THREAD

**Issue by lukasleuschen** [digitalocean/doctl#1129]
**Describe the Issue:**

FROM digitalocean/doctl
RUN doctl version

yields "#4 0.319 /bin/sh: doctl: not found"

**Environment:**
 - doctl version: whatever is part of the image
 - OS: whatever is part of the image
 - Installation method: no installation, just pulling from docker hub

**Comment by andrewsomething** [comment]
Hi @lukasleuschen,

The image published to Docker Hub uses `doctl` as the entrypoint. This is designed so that it can be used on the command line like:

```
docker run --rm --interactive --tty \
  --env=DIGITALOCEAN_ACCESS_TOKEN=<YOUR-DO-API-TOKEN> \
  digitalocean/doctl account get
```

Inside the container itself, the `doctl` binary is installed to the `/app` directory which is set as `WORKDIR`. It is not added to the `PATH`. If you want to use in a derived image, you'll need to do something like:

```
FROM digitalocean/doctl
RUN ./doctl version
```

**Comment by lukasleuschen** [comment]
Hey @andrewsomething 
thank you so much for responding so quickly. Is there a certain reason that doctl isn't in PATH? I can't be the only one trying to build a runner that can interface with DOs managed kubernetes? Or is this not the image one is supposed to use for such things?

**Comment by andrewsomething** [comment]
Generally, we built this image with `docker run` as the expected usage, but we've definitely seen people using it as a base image. We can consider adding it to `PATH`, but installing it to somewhere besides `/app` would be a breaking change as we see people referencing the full path to it. For example, people are copying over the binary to their image with:

    COPY --from=digitalocean/doctl /app/doctl /bin/doctl

**Comment by lukasleuschen** [comment]
Personally, I think it would be great to add it to `PATH` because the suggested method of installation via `snap` (from the official documentation) doesn't seem to work in a docker image
