### ISSUE TITLE
Initial node pool contains more nodes than expected

### ISSUE THREAD

**Issue by j-zimnowoda** [digitalocean/doctl#1144]
**Describe the Issue:**
I create my k8s cluster as follows:
```
doctl kubernetes cluster create jeho \
--tag jeho \
--region ams3 \
--vpc-uuid=<redacted> \
--node-pool "name=jeho;size=s-4vcpu-8gb;tag=jeho;auto-scale=true;min-nodes=2;max-nodes=5;" \
--wait
```

Then I see that three nodes are created by default:
```
 k get node
NAME         STATUS   ROLES    AGE     VERSION
jeho-cmzqb   Ready    <none>   6m32s   v1.22.8
jeho-cmzqj   Ready    <none>   6m32s   v1.22.8
jeho-cmzqr   Ready    <none>   6m38s   v1.22.8
```
And after sometime the node pool scales down to two nodes
```
NAME         STATUS   ROLES    AGE   VERSION
jeho-cmzqj   Ready    <none>   14m   v1.22.8
jeho-cmzqr   Ready    <none>   14m   v1.22.8
```

**Expected behaviour**
A node pool starts with minimum number of nodes.

**Environment:**
```
doctl version 1.73.0-release
```

**Comment by andrewsomething** [comment]
Hi @j-zimnowoda,

DOKS node pools default to three nodes. As you did not explicitly add a `count`  argument, the default is used. Though with auto-scaling enabled and no active workloads, it scales back down to two.

If you specify the count, the node pool will start with that number. E.g.

    --node-pool "name=jeho;size=s-4vcpu-8gb;tag=jeho;auto-scale=true;min-nodes=2;max-nodes=5;count=2"

**Comment by j-zimnowoda** [comment]
Hi @andrewsomething,
Thanks for clarification. No issue then.
