### ISSUE TITLE
Documentation not rendering correctly for some pages

### ISSUE THREAD

**Issue by KylePeterDavies** [digitalocean/doctl#1147]
**Describe the Issue:**

On MacOS some pages [Digital Ocean Documentation](https://docs.digitalocean.com/reference/doctl/reference/kubernetes/cluster/create) for Doctl does not display correctly for some pages leading to the text being cropped and unable to be read.

**Environment:**

- MacOS 12.2.1
- Google Chrome 100.0.4896.60 (Official Build) (x86_64)
- Safari Version 15.3 (17612.4.9.1.8)

**Additional Details:**
I have tried to zoom out / in this does not resolve the problem, I believe this is a CSS problem. I have attached some screenshots.

![Screenshot 2022-04-15 at 02 54 47](https://user-images.githubusercontent.com/12613678/163506474-818e04cb-c9e9-402c-bf0f-b538ca755fe3.png)
<img width="1792" alt="Screenshot 2022-04-15 at 02 54 50" src="https://user-images.githubusercontent.com/12613678/163506480-d7028d81-e60f-49bc-bf1a-0526eca1d765.png">
<img width="1792" alt="Screenshot 2022-04-15 at 02 58 57" src="https://user-images.githubusercontent.com/12613678/163506483-d1787384-faac-4c7e-9685-c5bacbd5c811.png">
<img width="1792" alt="Screenshot 2022-04-15 at 02 59 05" src="https://user-images.githubusercontent.com/12613678/163506490-2d2f9103-0b04-4e09-9644-730807dd3f58.png">

**Comment by ChiefMateStarbuck** [comment]
Hello @KylePeterDavies . Thanks for the report. We're currently working on a solution.

**Comment by andrewsomething** [comment]
Looks like the CSS fix for the documentation site has shipped. Thanks again for flagging this for us!
