### ISSUE TITLE
Add examples other than [*] to compute cdn flush --files in documentation and/or add output showing which files are flushed

### ISSUE THREAD

**Issue by prurigro** [digitalocean/doctl#1156]
**What is the problem this feature would solve? Please describe.**

Currently there aren't any examples showing what a path should look like. Does it start with a leading slash? Do you need the bucket name like you do in s3cmd? Can you start with a wildcard to flush everything with a given file extension?

The fact that doctl always returns an empty success makes it even more difficult to determine whether you've entered the path correctly.

**Describe the solution you'd like**

Documentation showing a few examples of how you'd format a request, like:

```
doctl compute cdn flush <cdn-id> [/spacename/foldername/*]
doctl compute cdn flush <cdn-id> [*/*.mp4]
doctl compute cdn flush <cdn-id> [/spacename/*.obj]
```

It would be great if doctl could also return a list of the files that had their cache flushed.

Thanks!

**Comment by rustiever** [comment]
Hey @andrewsomething can i take up this ?

**Comment by andrewsomething** [comment]
@rustiever  Go for it! Let me know if you need any pointers.

**Comment by rustiever** [comment]
hey i would love to have some pointers to get started @andrewsomething

**Comment by andrewsomething** [comment]
Hey @rustiever!

The  `doctl compute cdn flush` command is constructed here:

https://github.com/digitalocean/doctl/blob/76730b59c7349b665466ebbd687662709acd1baf/commands/cdns.go#L82-L92 

You can make updates to the help output there. Next, you can run `make build`. That will build a version of `doctl` with your changes in the `builds/` directory. You can check that your changes look as expected by running the command from the new build:

    ./builds/doctl compute cdn flush -h

Wildcards can only be used to recursively purge a folder, e.g.  `/spacename/foldername/*` or all files `*`, not for matching patterns ( `/spacename/*.obj`). So some example commands could be:

    doctl compute cdn flush <cdn-id>  --files /path/to/assets/*
    doctl compute cdn flush <cdn-id>  --files "/path/to/file.one, /path/to/file.two"
    doctl compute cdn flush <cdn-id>  --files /path/to/file.one --files  /path/to/file.two
    doctl compute cdn flush <cdn-id>  --files *
