### ISSUE TITLE
Get "/v2/account": unsupported protocol scheme ""

### ISSUE THREAD

**Issue by f2k2game** [digitalocean/doctl#1167]
I have created api using https://docs.digitalocean.com/reference/api/create-personal-access-token/, 

when i try to use `doctl auth init`

```
Please authenticate doctl for use with your DigitalOcean account. You can generate a token in the control panel at https://cloud.digitalocean.com/account/api/tokens

Enter your access token: 
Validating token... invalid token

Error: Unable to use supplied token to access API: Get "/v2/account": unsupported protocol scheme ""
```

**Comment by andrewsomething** [comment]
Hi @f2k2game,

Do you happen to be passing the `--api-url` flag or have the  `DIGITALOCEAN_API_URL` variable set in the environment? If so, it needs to include the protocol scheme (`https://`). For example, `https://api.digitalocean.com` rather than just `api.digitalocean.com`.

**Comment by f2k2game** [comment]
I don't know what problem is, I completely uninstalled and installed again and now it working.

```
brew uninstall -f doctl
rm -rf "$HOME/Library/Application Support/doctl"
brew install doctl
```

**Comment by andrewsomething** [comment]
Thanks for the follow up @f2k2game. Glad to hear it's working now. I'm going to go ahead and close this issue out as there isn't much we can do without more information. Please feel free to reopen if you run into any other problems.
