### ISSUE TITLE
Droplet sizes in doctl do not match those displayed in the Web

### ISSUE THREAD

**Issue by cool00geek** [digitalocean/doctl#1180]
**Describe the Issue:** `doctl compute size list` lists 70 different types of VMs, however many of those do not match with what's provided on the web site. Every size that is present in the command output with a disk size of over 100gb shows as 100gb on the web, while the API shows a larger size. The reason the API fetches more than the web is because of #381. However, the problem here is the mismatch in disk size between the API and the website.

**Environment:**

 - doctl version: doctl 1.75.0-1
 - OS: Manjaro
 - Installation method: Manjaro Repos

**Additional Details:**

The results in `doctl` seem to match those on the [api site](https://slugs.do-api.dev/)

However, it is possible there are quotas preventing my account from using disks with a size greater than 100gb. If this is the case, the API should also enforce the quotas and not display larger disk sizes and allow me to create instances with larger disk sizes.

**Comment by andrewsomething** [comment]
Hi @cool00geek,

If you could give a specific example of a slug for a plan you see in the API but not the control panel, it would be helpful in understanding the problem?

One thing to note is that some sizes that the API returns are not show as discrete plans in the control panel. Instead, they can be found by using the "disk options" to increase the available storage. Could that account for the additional plans you are seeing?

![172639435-128d3356-2d0c-4fd3-b036-64f28dc06c0e](https://user-images.githubusercontent.com/46943/172647953-c6fdefa8-34b5-4784-a9ab-4da996dbc99c.png)

![172639683-865e96be-175f-4b1b-87be-6366e153a48c](https://user-images.githubusercontent.com/46943/172647981-d36f2d5e-05c4-4aa4-9e70-5a6e8cb2bb68.png)
