### ISSUE TITLE
Getting Duplicate Suggestions for invalid commands  

### ISSUE THREAD

**Issue by harkiratsm** [digitalocean/doctl#1192]
**Describe the Issue:**

Currently if a user use a invalid command ```doctl apa``` , we are getting duplicate suggestions for that commands . 
![image](https://user-images.githubusercontent.com/71957674/180653970-2343ffd2-ffee-423a-b01d-912bed702d27.png)

**Environment:**

 - doctl version: 1.78.0-release
 - OS: windows/amd64
 - Installation method: Source 

**Additional Details:**

**Comment by ChiefMateStarbuck** [comment]
Hello @harkiratsm . Thank you for the bug report. We have a draft PR open now and will into the error further
