### ISSUE TITLE
Use consistent aliases for `list` and `delete` sub-commands

### ISSUE THREAD

**Issue by andrewsomething** [digitalocean/doctl#1262]
**What is the problem this feature would solve? Please describe.**

Many `doctl` commands provide aliases allowing you to use a shorter version of the command. In particular, `list` is often aliased as `ls` and `delete` is often aliased as `rm`. These are short memorable aliases that recall common Unix commands. Unfortunately, we have not always made sure every new sub-command adds these aliases. We should provide a consistent experience. User should know that they can use `ls` and `list` interchangeably across `doctl`.

**Describe the solution you'd like**

- `ls` should be added as an alias for all  `list` sub-commands
- `rm` should be added as an alias for all  `delete` sub-commands

You can find an example here:

https://github.com/digitalocean/doctl/blob/c7bf8d427e73e395f59f743cee05f6747392b677/commands/sizes.go#L35-L36

**Additional context**

Adding a test to `commands/commands_test.go` to iterate through the commands and inspect their aliases can help to identify where changes are needed. For example: 

```go
func assertCommandAliases(t *testing.T, cmd *cobra.Command) {
	for _, c := range cmd.Commands() {
		if c.Name() == "list" {
			assert.Contains(t, c.Aliases, "ls", "Missing 'ls' alias for 'list' command.")
		}
		if c.Name() == "delete" {
			assert.Contains(t, c.Aliases, "rm", "Missing 'rm' alias for 'delete' command.")
		}
	}
}

func TestCommandAliases(t *testing.T) {
	for _, cmd := range DoitCmd.Commands() {
		t.Run(cmd.Name(), func(t *testing.T) {
			assertCommandAliases(t, cmd)
			for _, c := range cmd.Commands() {
				t.Run(c.Name(), func(t *testing.T) {
					assertCommandAliases(t, c)
				})
			}
		})
	}
}
```

**Comment by selborsolrac** [comment]
Hello, I'd like to work on this issue for Hacktoberfest 2022!

Thank you for the example test logic. I used this slightly modified version to find missing aliases:
```
func assertCommandAliases(t *testing.T, cmd *cobra.Command) {
	for _, c := range cmd.Commands() {
		if c.Name() == "list" {
			assert.Contains(t, c.Aliases, "ls", "Missing 'ls' alias for 'list' command.")
		}
		if c.Name() == "delete" {
			assert.Contains(t, c.Aliases, "rm", "Missing 'rm' alias for 'delete' command.")
		}
	}
}

func recurseCommand(t *testing.T, cmd *cobra.Command) {
	t.Run(cmd.Name(), func(t *testing.T) {
		assertCommandAliases(t, cmd)
	})
	for _, c := range cmd.Commands() {
		recurseCommand(t, c)
	}
}

func TestCommandAliases(t *testing.T) {
	for _, cmd := range DoitCmd.Commands() {
		recurseCommand(t, cmd)
	}
}
```

It found 14 instances of "list" or "delete" commands missing aliases in these files:
```
commands/activations.go
commands/apps.go
commands/domains.go
commands/functions.go
commands/images.go
commands/monitoring.go
commands/namespaces.go
commands/snapshots.go
commands/sshkeys.go
commands/tags.go
commands/triggers.go
```

I can submit a draft PR to add the missing aliases. Please let me know if I missed any!
