### ISSUE TITLE
Add --wait flag to database create command

### ISSUE THREAD

**Issue by andrewsomething** [digitalocean/doctl#1263]
**What is the problem this feature would solve? Please describe.**

`doctl` aims to be useful in scripting. One way it does this is by providing a `--wait` flag for long running, async operations to block until until they are complete rather than making the user implement polling in their own script. Some examples include:

- `doctl compute droplet create --wait`
- `doctl kubernetes cluster create --wait`
- `doctl apps create --wait`

Currently the `doctl database create` command does not have a `--wait` flag.

**Describe the solution you'd like**

Add a `--wait` flag to the `doctl database create` command. It should poll the [`/v2/databases/$DATABASE_ID` endpoint](https://docs.digitalocean.com/reference/api/api-reference/#operation/databases_get_cluster), blocking until the database cluster's `status` attribute moves from `creating` to `online`.

**Additional context**

Following the code path starting here demonstrates how `doctl apps create`'s  `--wait` flag is implemented:

https://github.com/digitalocean/doctl/blob/de1918ad1ee4b1e523c335fa9254e85d415d18aa/commands/apps.go#L282

One important difference for databases is that some database engines (mongodb now, but potentially others) only return the password in the initial response to the create request. It is _not_ included in subsequent GET responses. So that value must be retained.

**Comment by VictorAvelar** [comment]
If you still have this one available, I'll take it.
