### ISSUE TITLE
Implement `--wait` on `compute volume create`

### ISSUE THREAD

**Issue by benmordaunt** [digitalocean/doctl#1268]
You currently cannot wait for a volume to complete creation. This is no good for CI.

Add a `--wait` flag for `doctl compute volume create`.

**Comment by volmedo** [comment]
@benmordaunt I'm looking for projects to contribute to as part of Hacktoberfest 2022. Should I give this issue a try?

**Comment by volmedo** [comment]
@andrewsomething maybe you are better suited to tell if this would be an interesting contribution to the project. If it is, I wouldn't mind working on it.

**Comment by danaelhe** [comment]
Hi there, 

Thanks for the write up. You actually get `--wait` for free in the `volumes create` command as it doesn't return to prompt until you get a response, and if the response is a 2xx HTTP response, your volume exists. This is due to volume creates being synchronous.
