### ISSUE TITLE
serverless connect + status (and others) fails with Snap

### ISSUE THREAD

**Issue by FuegoFro** [digitalocean/doctl#1284]
**Describe the Issue:**

When installed via snap, seemingly all functions that interact with serverless fail, even after a successful connect. For instance:
```
❯ doctl serverless connect
Connected to functions namespace 'fn-<redacted>' on API host 'https://faas-sfo3-<redacted>.doserverless.co' (label=<redacted>)

❯ doctl serverless status
Error: serverless support is installed but not connected to a functions namespace (use `doctl serverless connect`)
```

Note that I get the same failure for `doctl serverless functions list`

**Environment:**

 - doctl version: 
 ```
doctl version 1.83.0-release
Git commit hash: c9b8dec9
```
 - OS: WSL2 on Windows 11:
```
WSL version: 0.70.0.0
Kernel version: 5.15.68.1
WSLg version: 1.0.45
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22000.1098
```
Running in an Ubuntu 20.04 container:
```
❯ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal
```
 - Installation method: Snap

**Additional Details:**

The `connect` command *does* write the credentials out to `~/.config/doctl/sandbox/creds/<hash>/credentials.json`, but the `status` command is only looking to read them from `/snap/doctl/<number>/opt/sandbox/creds/<hash>/credentials.json`.

The mismatch seems to come from unconditionally using `usualServerlessDir` at
https://github.com/digitalocean/doctl/blob/a1f1c350b96080999048a1b32368ec50a7eb631c/do/serverless.go#L322
and the fact that some things use `serverlessDir` to lookup the creds whereas others use `credsDir`. But even more, it *seems* that `status` should actually be looking in the home dir since the snap dir is only writeable by root (at least for me).

Let me know if there's any other useful information I can provide!

Recent Snap PRs:
- https://github.com/digitalocean/doctl/pull/1173
- https://github.com/digitalocean/doctl/pull/1224

Refactor that introduced the above line:
- https://github.com/digitalocean/doctl/pull/1222

(feel free to ignore this aside, since it transitions fully into back-seat driving with literally zero context on this project or the feasibility of the suggestion 🙃 BUT from the other PRs linked above it seems there's been a few times that Snap auth has broken and I wonder if it's possible to run more integration-y tests to ensure folks installing via the recommended method on Ubuntu can use the tool)

**Comment by FuegoFro** [comment]
Hey, thanks so much for the quick response! I've tried to start fresh and ran into the same problem 😕 I went through the exact steps above, output is here:
<details>
<summary>Reinstall doctl</summary>

```
❯ sudo snap remove doctl
[sudo] password for <user>:
doctl removed

❯ which -a doctl
doctl not found

❯ ll /snap
total 16K
-r--r--r-- 1 root root  548 Oct 16 17:04 README
drwxr-xr-x 2 root root 4.0K Oct 17 19:44 bin
drwxr-xr-x 3 root root 4.0K Oct 16 17:05 core20
drwxr-xr-x 3 root root 4.0K Oct 16 17:04 snapd

❯ rm -rf ~/.config/doctl

❯ sudo snap install doctl
doctl v1.83.0 from DigitalOcean✓ installed

❯ doctl serverless status
Error: Unable to initialize DigitalOcean API client: access token is required. (hint: run 'doctl auth init')

❯ doctl auth init
Please authenticate doctl for use with your DigitalOcean account. You can generate a token in the control panel at https://cloud.digitalocean.com/account/api/tokens

Enter your access token:
Validating token... OK


❯ doctl serverless connect
Connected to functions namespace 'fn-<namespace>' on API host 'https://faas-sfo3-<host>.doserverless.co' (label=<label>)


❯ doctl serverless status
Error: serverless support is installed but not connected to a functions namespace (use `doctl serverless connect`)

❯ doctl auth list
default (current)
```
</details>

I don't know if it's helpful, but according to `strace` it really doesn't look like it's trying to write to the Snap dir during `connect` or read from the home dir during `status`. I've pulled out the parts that look relevant below with links to gists with the full output in case that's helpful.

[`sudo strace -u <user> -f -D -vv -o serverless_connect.txt -e trace=file doctl serverless connect`](https://github.com/digitalocean/doctl/files/9806180/serverless_connect.txt)
```
1820  newfstatat(AT_FDCWD, "/home/<user>/.config/doctl/config.yaml", {st_dev=makedev(0x8, 0x20), st_ino=82403, st_mode=S_IFREG|0600, st_nlink=1, st_uid=1000, st_gid=1000, st_blksize=4096, st_blocks=40, st_size=18696, st_atime=1666061197 /* 2022-10-17T19:46:37.048071836-0700 */, st_atime_nsec=48071836, st_mtime=1666061185 /* 2022-10-17T19:46:25.188068020-0700 */, st_mtime_nsec=188068020, st_ctime=1666061185 /* 2022-10-17T19:46:25.188068020-0700 */, st_ctime_nsec=188068020}, 0) = 0
1820  openat(AT_FDCWD, "/home/<user>/.config/doctl/config.yaml", O_RDONLY|O_CLOEXEC) = 6
1820  newfstatat(AT_FDCWD, "/snap/doctl/1064/opt/sandbox", {st_dev=makedev(0, 0x51), st_ino=7623672575, st_mode=S_IFDIR|0755, st_nlink=4, st_uid=0, st_gid=0, st_blksize=131072, st_blocks=0, st_size=0, st_atime=1665157924 /* 2022-10-07T08:52:04-0700 */, st_atime_nsec=0, st_mtime=1665157924 /* 2022-10-07T08:52:04-0700 */, st_mtime_nsec=0, st_ctime=1665157924 /* 2022-10-07T08:52:04-0700 */, st_ctime_nsec=0}, 0) = 0
1820  openat(AT_FDCWD, "/snap/doctl/1064/opt/sandbox/version", O_RDONLY|O_CLOEXEC) = 6
1820  newfstatat(AT_FDCWD, "/snap/doctl/1064/opt/sandbox/creds/<hash>/credentials.json", 0xc0002982a8, 0) = -1 ENOENT (No such file or directory)
...
1822  newfstatat(AT_FDCWD, "/home/<user>/.config/doctl/sandbox/creds/<hash>", {st_dev=makedev(0x8, 0x20), st_ino=347430, st_mode=S_IFDIR|0700, st_nlink=2, st_uid=1000, st_gid=1000, st_blksize=4096, st_blocks=8, st_size=4096, st_atime=1666061197 /* 2022-10-17T19:46:37.558071448-0700 */, st_atime_nsec=558071448, st_mtime=1666061197 /* 2022-10-17T19:46:37.558071448-0700 */, st_mtime_nsec=558071448, st_ctime=1666061197 /* 2022-10-17T19:46:37.558071448-0700 */, st_ctime_nsec=558071448}, 0) = 0
1822  openat(AT_FDCWD, "/home/<user>/.config/doctl/sandbox/creds/<hash>/credentials.json", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0600) = 7
```

[`sudo strace -u <user> -f -D -vv -o serverless_status.txt -e trace=file doctl serverless status`](https://github.com/digitalocean/doctl/files/9806185/serverless_status.txt)
```
2203  newfstatat(AT_FDCWD, "/home/<user>/.config/doctl/config.yaml", {st_dev=makedev(0x8, 0x20), st_ino=82403, st_mode=S_IFREG|0600, st_nlink=1, st_uid=1000, st_gid=1000, st_blksize=4096, st_blocks=40, st_size=18696, st_atime=1666061197 /* 2022-10-17T19:46:37.048071836-0700 */, st_atime_nsec=48071836, st_mtime=1666061185 /* 2022-10-17T19:46:25.188068020-0700 */, st_mtime_nsec=188068020, st_ctime=1666061185 /* 2022-10-17T19:46:25.188068020-0700 */, st_ctime_nsec=188068020}, 0) = 0
2203  openat(AT_FDCWD, "/home/<user>/.config/doctl/config.yaml", O_RDONLY|O_CLOEXEC) = 6
...
2211  newfstatat(AT_FDCWD, "/snap/doctl/1064/opt/sandbox", {st_dev=makedev(0, 0x51), st_ino=7623672575, st_mode=S_IFDIR|0755, st_nlink=4, st_uid=0, st_gid=0, st_blksize=131072, st_blocks=0, st_size=0, st_atime=1665157924 /* 2022-10-07T08:52:04-0700 */, st_atime_nsec=0, st_mtime=1665157924 /* 2022-10-07T08:52:04-0700 */, st_mtime_nsec=0, st_ctime=1665157924 /* 2022-10-07T08:52:04-0700 */, st_ctime_nsec=0}, 0) = 0
2211  openat(AT_FDCWD, "/snap/doctl/1064/opt/sandbox/version", O_RDONLY|O_CLOEXEC <unfinished ...>
...
2211  <... openat resumed>)             = 6
...
2211  newfstatat(AT_FDCWD, "/snap/doctl/1064/opt/sandbox/creds/<hash>/credentials.json", 0xc00058c1d8, 0) = -1 ENOENT (No such file or directory)
```

And finally, yeah honestly sorry for including that last bit in the original message, it's not particularly productive and it implied y'all hadn't thought about that which isn't particularly respectful. That was my bad, sorry.

**Comment by joshuaauerbachwatson** [comment]
Thanks for the traces.   They do make me suspicious that, at least in your case, the status command is looking for `credentials.json` under the snap install directory instead of your home directory, at least some of the time.   I will investigate further down those lines.   At this point, I have no idea why this seems to work correctly for me and incorrectly for you.

**Comment by FuegoFro** [comment]
Hmmm, I'm wondering if this is some WSL/snapfuse shenanigans. Listing a directory with the same permissions in my home dir fails as expected, but listing the snap dir just silently passes:
```
❯ pwd
/home/<user>/tmp

❯ mkdir owned_by_root && sudo chown root:root owned_by_root && sudo chmod 700 owned_by_root

❯ ls -ld owned_by_root
drwx------ 2 root root 4096 Oct 18 09:57 owned_by_root

❯ ls owned_by_root; echo $?
ls: cannot open directory 'owned_by_root': Permission denied
2

❯ ls -ld /snap/doctl/1064/opt/sandbox/creds/
drwx------ 2 root root 0 Oct  7 08:51 /snap/doctl/1064/opt/sandbox/creds/

❯ ls /snap/doctl/1064/opt/sandbox/creds/; echo $?
0
```
Notably the snap dir is using `fuse.snapfuse` (whereas my home dir uses ext4):
```
❯ df . /snap/doctl/1064/opt/sandbox/creds/
Filesystem      Size  Used Avail Use% Mounted on
/dev/sdc        251G  7.2G  231G   3% /
snapfuse         57M   57M     0 100% /snap/doctl/1064

❯ mount | grep -E ' on (/|/snap/doctl/1064) '
/dev/sdc on / type ext4 (rw,relatime,discard,errors=remount-ro,data=ordered)
snapfuse on /snap/doctl/1064 type fuse.snapfuse (ro,nodev,relatime,user_id=0,group_id=0,allow_other)
```
So maybe not worth digging into too much if this is just some WSL weirdness? I dunno haha. I'm happy to run any other tests that would be helpful though!

**Comment by joshuaauerbachwatson** [comment]
Should be fixed in this release: https://github.com/digitalocean/doctl/releases/tag/v1.84.1

**Comment by FuegoFro** [comment]
Hey, yeah can confirm that fixes it for me! Thank you for the fast responses here! 😀
