### ISSUE TITLE
Broken link to AUR package

### ISSUE THREAD

**Issue by kraai** [digitalocean/doctl#1291]
**Describe the Issue:**

https://github.com/digitalocean/doctl#arch-linux contains a link whose text is "AUR" that points to https://aur.archlinux.org/packages/doctl-bin/.  When I follow that link, it redirects to https://aur.archlinux.org/packages/doctl-bin and displays a 404 page.  I searched that site for "doctl", "digitalocean", and "digital ocean" and didn't find a package of doctl.

**Comment by andrewsomething** [comment]
Look like the AUR link is no longer relevant.  We should probably link this instead: https://archlinux.org/packages/community/x86_64/doctl/
