### ISSUE TITLE
doctl as NPM package and .deb

### ISSUE THREAD

**Issue by dav1app** [digitalocean/doctl#1326]
**What is the problem this feature would solve? Please describe.**
- We can use doctl as a dependency on NPM. This eases the integration with native code and reduces friction for CI/CD. 
- `.deb` packages are preferred under linux environments as `snap` [slows down the entire machine](https://www.reddit.com/r/Ubuntu/comments/rh3u89/snap_is_slowing_down_your_system/). 

**Describe the solution you'd like**
- Pack doctl in .deb and NPM packages.

**Comment by andrewsomething** [comment]
Thanks for the feed back. We are already tracking the request for a Debian package in https://github.com/digitalocean/doctl/issues/751 You can follow that issue for any updates.
