### ISSUE TITLE
oh-my-zsh plugin not working

### ISSUE THREAD

**Issue by guglielmo** [digitalocean/doctl#1329]
**Describe the Issue:**
The plugin is installed by adding the doctl keyword to the *plugins* line:

```
plugins=(git pyenv tmux docker doctl)
```

After logging into a new shell, there is no sign of completion at all.

```
doctl compute TAB
[nothing happens]
```

**Environment:**

 - doctl version: 
   doctl version 1.91.0-release
   Git commit hash: 0863be
 - OS: **Ubuntu 22.04**
 - Installation method: 
   - **doctl** has been installed through snap,
   - **zsh** has been installed through apt (v5.8.1),
   - **oh-my-zsh** has been installed through curl 
   - **powerlevel10k** was installed through curl

**Additional Details:**
```
doctl completion zsh
```

Is there a way to debug and understand why the autocompletion is not working?

**Comment by andrewsomething** [comment]
Hi @guglielmo,

The doctl oh-my-zsh plugin is not something maintained here. It is part of oh-my-zsh itself:

https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/doctl/doctl.plugin.zsh

One thing that jumps out at me is that is does not have the `compdef` line. 

If I edit `~/.oh-my-zsh/plugins/doctl/doctl.plugin.zsh` to include it, tab completion seems to work as expected:

```zsh
if [ $commands[doctl] ]; then
  source <(doctl completion zsh)
  compdef _doctl doctl
fi
```

Can you give that a try? If it works for you, we can open a PR to oh-my-zsh.

**Comment by shinebayar-g** [comment]
Instructions provided on readme is working just fine. You should prefer native implementation rather than third party plugins.

**Comment by guglielmo** [comment]
Hi @andrewsomething, it works perfectly, many thanks!

**Comment by andrewsomething** [comment]
Great to hear. I've opened a PR to oh-my-zsh, so hopefully this gets fixed on their end.
