### ISSUE TITLE
Ability to delete multiple snapshots

### ISSUE THREAD

**Issue by daoenix** [digitalocean/doctl#133]
Being billing will begin on October 1st for customers storing snapshots. It would be beneficial to allow doctl to permit to delete multiple snapshots at once. Much like you can do with droplets. 

At the moment, we have noticed attempting to mass delete images, it provides syntax errors.

**Comment by akshaychhajed** [comment]
Looks like #153 takes care of this. It did not get correctly linked due to a typo.
