### ISSUE TITLE
Database Replica Functions Missing Integration Tests

### ISSUE THREAD

**Issue by ChiefMateStarbuck** [digitalocean/doctl#1359]
**Describe the Issue:**

When working on #1348 to add `promote` functionality it was discovered that other endpoints under `replica` are missing integration tests. `replica create`, `replica delete`, `replica get`, `replica list`, and `replica getReplicaConnection` are all missing integration tests.

**Environment:**
Local Dev

**Comment by dhanusaputra** [comment]
hi can I work on this please, thanks

**Comment by prakrit55** [comment]
@ChiefMateStarbuck, if its still there I would like to work on it
