### ISSUE TITLE
doctl integration with snap package manager (not only for Ubuntu[1])

### ISSUE THREAD

**Issue by claudioandre** [digitalocean/doctl#136]
It is possible to package doctl using snap. Advantages:
- you can advertise the rigorous application isolation;
- it will update automatically and transactionally;
- for example, after an update, if the new release is broken the user can easily roolback to the last working version.
- not only for x64 (for example, I have armhf and arm64 packages published).

So doctl will be always fresh and never broken.

---

In fact, using exactly the binary inside https://github.com/digitalocean/doctl/releases/download/v1.4.0/doctl-1.4.0-linux-amd64.tar.gz, I created a snap and installed it locally. That said, I would like to say:
- you, digitalocean can, in minutes create an official account in Ubuntu Store and submit yourself the snap package. I can make a PR.
- I can register a name like doctl-snap and publish the snap myself.

Anyway, even if I submit the package myself, I really appreciate if anyone more confortable with doctl help me assuring package works as expected.

---

[1] snaps should now work, unmodified, on Arch, CentOS, Debian, Elementary, Fedora, Gentoo, RHEL, SUSE... and of course the whole family of *buntu's.

**Comment by bryanl** [comment]
Hello, 

Finding a delivery solution for Linux has been on my secondary list for a while. I'm not familiar with ubuntu snap, and I will research this option. Thanks for pointing it out.

**Comment by claudioandre** [comment]
Hi Bryan

Feel free to ping me if you want to experiment or chat about your findings
and opinions. If you are busy, just create a VM and I'll show you how easy
is to have fun with it.

Trust me, easy-peasy.

**Comment by claudioandre** [comment]
Sorry for the spam, I'm just trying to 'be part of the community'. And I found no ML.
****

While at it, it is possible to use continuous integration. For every commit/or only for a branch:
- build, snap and upload.
- you can upload for stable, edge, beta and/or candidate (so, safe).

```
#!/bin/sh -e

set -e

DIR="$(pwd)"
OUT_DIR="$DIR/out"

# Only if the secret is known, upload the package
if [ -z "$SNAPCRAFT_SECRET" ]; then
    exit 0
fi

# Set up and build
go build   -o $OUT_DIR/doctl   -ldflags "-X github.com/digitalocean/doctl/Build=`git rev-parse --short HEAD`"   github.com/digitalocean/doctl/cmd/doctl
cp snap/snapcraft.yaml .
cp $OUT_DIR/doctl .
ls -la

version="$(git rev-parse --short HEAD)"
sed -i "s/edge/$version/g" snapcraft.yaml

mkdir -p ".encrypted"
if [ ! -e ".encrypted/snapcraft.cfg.enc" ]; then
    echo "Seeding a new macaroon."
    echo "$SNAPCRAFT_CONFIG" > ".encrypted/snapcraft.cfg.enc"
fi

mkdir -p "$HOME/.config/snapcraft"
openssl enc -aes-256-cbc -base64 -pass env:SNAPCRAFT_SECRET -d -in ".encrypted/snapcraft.cfg.enc" -out "$HOME/.config/snapcraft/snapcraft.cfg"

if docker run -v $HOME:/root -v $(pwd):/cwd didrocks/snapcraft sh -c 'cd /cwd; ls -la; snapcraft'; then
    docker run -v $HOME:/root -v $(pwd):/cwd didrocks/snapcraft sh -c "cd /cwd; snapcraft push *.snap"
fi

openssl enc -aes-256-cbc -base64 -pass env:SNAPCRAFT_SECRET -out ".encrypted/snapcraft.cfg.enc" < "$HOME/.config/snapcraft/snapcraft.cfg"
rm -f "$HOME/.config/snapcraft/snapcraft.cfg"
```

**Comment by bryanl** [comment]
Hello, this issue isn't being ignored. I have a few higher priority tasks that are taking precedence over this issue for a few days. I plan on circling back around by Tuesday or Wednesday.

**Comment by claudioandre** [comment]
Overwhelmed? :laughing:

We know how it is. :thumbsup:

**Comment by xmudrii** [comment]
@mauricio this was implemented as well. I think we just need to update to 1.6.0.
#154 addressed this.
when you execute `snap find doctl` you get:
```
Name   Version  Developer  Notes  Summary
doctl  1.5.0    joeborg    -      Digital Ocean command line tool
```
I don't know is it official or not but it exists.

**Comment by flexiondotorg** [comment]
`snap find doctl`

```
Name   Version  Developer  Notes  Summary
doctl  1.6.0    joeborg    -      Digital Ocean command line tool
```
