### ISSUE TITLE
Can't use shell autocompletion on macOS + zsh

### ISSUE THREAD

**Issue by rbrtmrtn** [digitalocean/doctl#1366]
**Describe the Issue:**

I followed the instructions for installing shell autocompletion on macOS:

https://github.com/digitalocean/doctl#enabling-shell-auto-completion

On the last step when I ran `source ~/.zshrc` I got these errors:

```bash
/opt/homebrew/etc/bash_completion:59: command not found: shopt
/opt/homebrew/etc/bash_completion:1192: command not found: shopt
/opt/homebrew/etc/bash_completion:1420: command not found: shopt
/opt/homebrew/etc/bash_completion.d/brew:5: command not found: shopt
/opt/homebrew/etc/bash_completion.d/docker:70: command not found: shopt
/opt/homebrew/etc/bash_completion.d/docker:71: command not found: shopt
/opt/homebrew/etc/bash_completion.d/docker-compose:19: command not found: shopt
/opt/homebrew/etc/bash_completion.d/docker-compose:20: command not found: shopt
/opt/homebrew/etc/bash_completion.d/doctl:type:282: bad option: -t
ERROR: this script is obsolete, please see git-completion.zsh
/opt/homebrew/etc/bash_completion.d/helm:type:319: bad option: -t
/opt/homebrew/etc/bash_completion.d/kubectl:type:333: bad option: -t
/opt/homebrew/etc/bash_completion.d/minikube:type:4631: bad option: -t
/opt/homebrew/etc/bash_completion.d/service:35: no matches found: /etc/init.d/*
/opt/homebrew/etc/bash_completion.d/ssh:194: command not found: shopt
/opt/homebrew/etc/bash_completion.d/ssh:247: command not found: shopt
/opt/homebrew/etc/bash_completion.d/xrandr:17: parse error near `)'
```

At a glance it looks like the problem is that this is trying to run bash code, but my default shell is zsh — maybe? However, the doctl docs seem to indicate that zsh is fine and works with the `bash-completion` library.

**Environment:**

 - doctl version: doctl version 1.93.1-release
 - OS: macOS Ventura 13.3.1 (22E261)
 - Installation method: Homebrew

**Additional Details:**

n/a

Thank you!

**Comment by ChiefMateStarbuck** [comment]
hey @rbrtmrtn I created a PR that might fix [this issue](https://github.com/digitalocean/doctl/pull/1368/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R374-R378). 

let me know if this solution works for you
