### ISSUE TITLE
`doctl version` now outputs json without `-o json` switch

### ISSUE THREAD

**Issue by ElanHasson** [digitalocean/doctl#1382]
**Describe the Issue:**

**Environment:**

 - doctl version: 1.96.1-release
 - OS: Ubuntu 22.04.2 LTS (GNU/Linux 5.15.0-73-generic x86_64)
 - Installation method: binary download via GH release 

**Additional Details:**

It seems https://github.com/digitalocean/doctl/pull/1377 introduced a regression to `doctl version` where the output is always output as json. 

```shell
❯ doctl version
{
  "version": "1.96.1-release",
  "commit": "d94f8bbe",
  "latestRelease": "1.96.1"
}
❯ doctl version -o json
{
  "version": "1.96.1-release",
  "commit": "d94f8bbe",
  "latestRelease": "1.96.1"
}
```

**Comment by andrewsomething** [comment]
I can't reproduce this. I wonder if you somehow have the default output format set to json in your config file?

```
asb@asb-do-laptop:~$ doctl version
doctl version 1.96.1-release
Git commit hash: d94f8bbe
asb@asb-do-laptop:~$ cat ~/.config/doctl/config.yaml | grep 'output'
output: text
```

**Comment by ElanHasson** [comment]
@andrewsomething wow! Taht was it. I had no idea there was a default. How did that get set? or rather, How does it get set?

**Comment by ElanHasson** [comment]
Closing issue as the problem was an unknown config.
