### ISSUE TITLE
[Idea] Add SCP command do doctl

### ISSUE THREAD

**Issue by xmudrii** [digitalocean/doctl#141]
I'm thinking about idea of implementing `scp` into `doctl`, so you can easy upload or download files from your droplet.
It will help DigitalOcean users to have one tool, which does everything, from managing droplets, images... to SSH access and possibly SCP. Windows users will benefit too, as they don't have integrated SCP in shell.

I got idea of making it in two commands:
`doctl compute download <droplet-id> <remote-location> <local-location>`
`doctl compute upload <droplet-id> <local-location> <remote-location>`

As far as I researched, I don't think it would be hard to make it.
For Linux/OS X users, we can use system SCP (like now SSH, external). It should work well.
Yet for Windows users I found two SCP packages:
[Pacakge `scp` from github.com/tmc/scp](https://godoc.org/github.com/tmc/scp).
[Package `goScp` from github.com/kkirsche/go-scp](https://godoc.org/github.com/kkirsche/go-scp).

I wanted to know does doctl collaborators/DigitalOcean thought about this idea. Would it be useful, is it worth to add it, is it good idea?
Maybe, I could do it myself, but I want to hear comments on it :)

**Comment by bryanl** [comment]
Hello,

I think this idea sounds useful, however, I would like to not add any more features to doctl if possible. Instead, I would like to renew interest in the plugins project and add this this type of functionality there.

**Comment by akshaychhajed** [comment]
@bryanl could not find much information about plugins for doctl. Please elaborate.

**Comment by bryanl** [comment]
It's not documented. It only lives in the code as an unfinished idea. When it comes back into scope, I was thinking about integrating https://github.com/hashicorp/go-plugin.

**Comment by xmudrii** [comment]
Closing this issue to make tracker cleaner. ;)
