### ISSUE TITLE
Unable to delete tags from bash variable

### ISSUE THREAD

**Issue by CollinAlpert** [digitalocean/doctl#1417]
**Describe the Issue:**

When using the `doctl registry repository delete-tag` command and I want to delete multiple tags, I need to enter them all manually, instead of sourcing them from a bash variable. When sourced from a variable, `doctl` assumes the entire string is the tag name.

**Environment:**

 - doctl version: doctl version 1.97.1-release
 - OS: macOS Ventura 13.5.2
 - Installation method: Homebrewh

**Additional Details:**

![image](https://github.com/digitalocean/doctl/assets/14217185/05ae54d8-52dc-4b52-b7c6-4e47829bf284)

**Comment by andrewsomething** [comment]
Hi @CollinAlpert. Sorry for the late response. 

It looks like you're on macOS, so I'm guessing your shell is zsh. If you were using bash, the example you provided would have worked as expected. Though in zsh, things work a bit differently:

> One commonly encountered difference is that variables substituted onto the command line are not split into words. See the description of the shell option `SH_WORD_SPLIT` in [Parameter Expansion](https://zsh.sourceforge.io/Doc/Release/Expansion.html#Parameter-Expansion). In zsh, you can either explicitly request the splitting (e.g. `${=foo}`) or use an array when you want a variable to expand to more than one word. See [Array Parameters](https://zsh.sourceforge.io/Doc/Release/Parameters.html#Array-Parameters).

https://zsh.sourceforge.io/Doc/Release/Roadmap.html

So if you use the following, it should do what you want:

    doctl registry repository delete-tag registry.digitalocean.com/<reg>/<repo> ${=TAGS}

**Comment by CollinAlpert** [comment]
Thanks for the explanation!
