### ISSUE TITLE
Autocompletion for Fish Shell is unclear

### ISSUE THREAD

**Issue by awkto** [digitalocean/doctl#1418]
**Describe the Issue:**

**Environment:**

 - doctl version: 
 - OS: 
 - Installation method: 

**Additional Details:**

**Comment by danaelhe** [comment]
Hi there, 

Could you provide more details so we can best assist you?

**Comment by awkto** [comment]
Whoops, I thought I definitely added more details in the original post.

I was trying to add autocompletion for a command into fish shell and it wasn't working.

I figured out the issue on my end. the autocompletion files must also end in *.fish extension otherwise they will not work

**Comment by andrewsomething** [comment]
Thanks for following up!
