### ISSUE TITLE
Add Support for Alerts for Uptime Checks

### ISSUE THREAD

**Issue by danaelhe** [digitalocean/doctl#1419]
**Overview:**
Now that we've added doctl support for uptime checks (https://github.com/digitalocean/doctl/pull/1386), we should follow up with supporting uptime alerts so that we support the entire feature set. 

**Instructions**

1. Clone this repo
2. Create file: doctl/commands/uptime_alerts.go
3. Reference this [PR](https://github.com/digitalocean/doctl/pull/1386) and the API [documentation](https://docs.digitalocean.com/reference/api/api-reference/#operation/uptime_alert_create) for creating support for uptime alerts in doctl. You will need to use the [digitalocean/godo](https://github.com/digitalocean/godo) package to make the API calls. Refer to #1386 on how that was done.
4. Create a test file.
5. Create PR for us to review and merge 🎆

**Comment by dhanusaputra** [comment]
hi, can I work on this please? thanks

**Comment by mikesmithgh** [comment]
Hi @danaelhe, I am looking into this for #Hacktoberfest and have some questions around the expected arguments.

I see `alerts` are a part of `checks`: `/v2/uptime/checks/$CHECK_ID/alerts`.

I see there already exists alert policies `doctl monitoring alert` and I am not sure if this would be confusing to a user with both `doctl monitoring uptime alert` and `doctl monitoring alert`.

Do you want the command `doctl monitoring uptime alert` or have another format in-mind?

**Comment by danaelhe** [comment]
Oh that's a very good design question, thank you for bringing this up. 

We can see how that might be confusing, but `doctl monitoring uptime alert` is still our preferred way to go. It remains consistent with doctl pattern and also mirrors the control panel experience as well. I'm going to create a separate PR for expanding the `doctl monitoring alert -h` output a bit to differentiate the type of alerts.

**Comment by mikesmithgh** [comment]
> @mikesmithgh Oh that's a very good design question, thank you for bringing this up.
> 
> We can see how that might be confusing, but `doctl monitoring uptime alert` is still our preferred way to go. It remains consistent with doctl pattern and also mirrors the control panel experience as well. I'm going to create a separate PR for expanding the `doctl monitoring alert -h` output a bit to differentiate the type of alerts.

Sounds good, thanks!

**Comment by MeenuyD** [comment]
I would like to work on this issue can you please guide me?

**Comment by mikesmithgh** [comment]
Hi @danaelhe I am working on this issue and noticed some inconsistencies in the APIs.

For the uptime alert `comparison` the values are either `greater_than` or `less_than` (see https://github.com/search?q=repo%3Adigitalocean%2Fopenapi%20greater_than&type=code).

But, the alert API is using `compare` with `GreaterThan` and `LessThan` (see https://github.com/search?q=repo%3Adigitalocean%2Fopenapi%20GreaterThan&type=code).

Should this be opened as a bug? The API spec is correct and I can hit the endpoints with the syntax, so I am assuming this would be in the actual API repo.

**Comment by danaelhe** [comment]
Oh yes, good catch. You are correct in that it is an inconsistency with the different types of `alert`s.  It is more of an inconsistency from a user experience perspective, as you point out, since functionally it's still accurate. Though, trying to enforce a common standard now would cause a breaking change. Unfortunately, it is not a breaking change we can fix right now. We will pass the feedback on to the appropriate internal product teams who will decide what/when is the best course of action to mitigate inconsistencies in the past and in the future.

Thank you for sharing your feedback!

**Comment by mikesmithgh** [comment]
@danaelhe Thanks! makes sense 👍

**Comment by danaelhe** [comment]
addressed in #1431
