### ISSUE TITLE
compute image create --image-file

### ISSUE THREAD

**Issue by stemid** [digitalocean/doctl#1426]
**What is the problem this feature would solve? Please describe.**
For example Fedora CoreOS offer a digitalocean image, and they helpfully provide cryptographic signatures to verify that the image you download is correct. But since digitalocean only allow you to programmatically upload images using doctl all those methods are useless because you can only specify an image URL.

So the only way to upload a verified image is manually through the web UI.

**Describe the solution you'd like**
Either to specify --image-url file:// or a new argument called --image-file, whatever is better.

**Additional context**

**Comment by andrewsomething** [comment]
This request is the same as https://github.com/digitalocean/doctl/issues/997. Lets consolidate and track it there.
