### ISSUE TITLE
webgui xterm code 

### ISSUE THREAD

**Issue by syonfox** [digitalocean/doctl#1465]
**What is the problem this feature would solve? Please describe.**

Please let me know where i can find the code for the do xterm web display. Im curios on how i can incorporate the do access mechanism to my users service as Eventually will need to use do on a tenant basis.  

**Describe the solution you'd like**
Please advise on if there is a version of the terminal code that's easy to incorporate ideally mit ;) 

**Additional context**
When i go to my dashboard its easy to access any server with the do client access server. 
We can all learn a terminal interface. 2 optimizations could be speed and security.

**Comment by andrewsomething** [comment]
Hi @syonfox, 

Unfortunately the entire implementation is not open source, but I can provide a few bits that should hopefully point you in the right direction. The UI itself is built on xterm.JS:

https://xtermjs.org/
https://www.npmjs.com/package/xterm
https://github.com/xtermjs/xterm.js

On the Droplet side, this daemon is used to provide access:

https://github.com/digitalocean/droplet-agent

Hope that helps!
