### ISSUE TITLE
git: no submodule mapping found in .gitmodules

### ISSUE THREAD

**Issue by zchee** [digitalocean/doctl#150]
Hi,
I tried `go get github.com/digitalocean/doctl/cmd/doctl`, occur error. the log is below.
FYI, it's the first fetch and also tried `rm -rf doctl` and re-fetch use `git` directly. same results.

``` bash
fatal: no submodule mapping found in .gitmodules for path 'vendor/github.com/vektra/errors'
```

I don't know `doctl` repository history(did use submodule for the manage vendoring previous?), but it might exist junk submodule data on git tree.
`go get` command automatically fetch submodule with `--recursive` flag, and `git clone --recursive` will occur.
If `git clone` only, maybe not occur.

Anyway, If I'm not wrong(my git environment), I think we should solve it.

**Comment by zchee** [comment]
Or, it's `github.com/vektra/errors` issue?

**Comment by hholst80** [comment]
I have the same error. No comments from Digital Ocean?

**Comment by xmudrii** [comment]
It is known issue. As far as I know, @bryanl was looking into it, but I don't know did he made any progress with it. There was even some PRs that tried to fix it but it was out of luck.
You can just run command again and it should install it without any problem.
Take look at #42 for more insight about it.

**Comment by lapawa** [comment]
Have the same issue here. command:
$  go get github.com/digitalocean/doctl/cmd/doctl
exits with message:
$  fatal: no submodule mapping found in .gitmodules for path 'vendor/github.com/vektra/errors'

$ go version
go version go1.6.2 linux/amd64

**Comment by dch** [comment]
this hack https://github.com/digitalocean/doctl/issues/47#issuecomment-278467149 is enough to get the tool built, but from a production perspective skipping the tests is not really ideal.a

**Comment by zchee** [comment]
@xmudrii Ohh. Today, I understood that cause.
I'll send pull request later(maybe).
