### ISSUE TITLE
Adding taints has wrong syntax in DO docs

### ISSUE THREAD

**Issue by fniko** [digitalocean/doctl#1507]
I have observed an issue in (probably) auto-generated docs under `doctl kubernetes cluster node-pool create` and `doctl kubernetes cluster node-pool update`.  Under Flags option `--taint`, the description says
> Taint in key[=value:]effect notation to apply to the node pool, repeat to add multiple taints at once. Omitted taints will be removed from the node pool if the flag is specified.

Using `key[=value:]effect` does not work.

The right syntax is just `key=value:effect`
Example
```cli
doctl kubernetes cluster node-pool update cluster-name node-pool-name --taint key=value:NoExecute
```

I am not sure whether the error is in the code (I was unable to locate that) or in auto-generation mechanism.

Link to docs
- https://docs.digitalocean.com/reference/doctl/reference/kubernetes/cluster/node-pool/create/
- https://docs.digitalocean.com/reference/doctl/reference/kubernetes/cluster/node-pool/update/

**Comment by bentranter** [comment]
Hey @fniko, thanks for the report!

Our documentation is generated from the doctl source, and it strangely appears to be correct:

https://github.com/digitalocean/doctl/blob/80974e963da3e7782722a4c5f09e42f0d14f6baa/commands/kubernetes.go#L303

Going through the history though, I can see that this was a recent-ish change, and that it was previously using the incorrect syntax that you see now in our docs. I'll get our docs regenerated, which should resolve this. I'll post here once that's done.

**Comment by bentranter** [comment]
Fixed now – you might need to hard refresh those pages if you had them open recently to see the change.
