### ISSUE TITLE
Access the link to download CA certificate for managed databases

### ISSUE THREAD

**Issue by AAverin** [digitalocean/doctl#1512]
**What is the problem this feature would solve? Please describe.**

To fully automate managed database cluster setup within my infrastructure, including access to the database by other services, I would like to have a way to access CA database certificate download link.
This would allow me to download certificate and pass it through the environment to configure SSL access.
Additionally I would love that to be accessible with Terraform too.

**Describe the solution you'd like**
Doctl implementation + Terraform exposed output parameter for the `digitalocean_database_cluster` resource: https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/resources/database_cluster

**Additional context**

**Comment by MrCuPper** [comment]
Hello, God, I don't know what I did, I don't know programming at all, I'm
just very interested in these programs, but I don't have the money to
spend, nor the possibility to study, that's why I got stuck, I don't know
what I did.

**Comment by andrewsomething** [comment]
On the Terraform side, the `digitalocean_database_ca` data source has been available since v2.13.0 (released October 7, 2021).

https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/data-sources/database_ca

**Comment by loosla** [comment]
Implemented in doctl [v1.114.0](https://github.com/digitalocean/doctl/releases/tag/v1.114.0)
