### ISSUE TITLE
Error: websocket: bad handshake for doctl apps logs <app id> -f --tail 200

### ISSUE THREAD

**Issue by wcomnisky** [digitalocean/doctl#1525]
**Describe the Issue:**

The command `doctl apps logs <app id> -f --tail 200` returns the following error: `Error: websocket: bad handshake`

**Environment:**

 - doctl version: 1.105.0-release
 - OS: macOS Sonoma 14.1.1 (23B2082)
 - Installation method: Homebrew

**Additional Details:**

I've reinstalled it but the error persists.

**Comment by wcomnisky** [comment]
Tested the https://github.com/digitalocean/doctl/releases/download/v1.105.0/doctl-1.105.0-darwin-amd64.tar.gz and got the same

**Comment by jcodybaker** [comment]
Hi William, this code path is working correctly in our testing.  Can you file a ticket on https://support.digitalocean.com and please include the app-id you're using?

**Comment by wcomnisky** [comment]
Hello! I'm going to close this as it seems to be related to the deployment of an App Platform that also has a Function. For some reason, destroying (undeploying) the Function resolves the issue, but we're still investigating it with the support. Thanks.
