### ISSUE TITLE
`doctl auth list --output json` produces text output

### ISSUE THREAD

**Issue by glennslaven** [digitalocean/doctl#1543]
**Describe the Issue:**
Running `doctl auth list --output json` & `doctl auth list --output text` produce the same output in text format.

**Environment:**

 - doctl version: `doctl version 1.108.0-release, Git commit hash: 5b24b236`
 - OS: Ubuntu 20.04.6 LTS
 - Installation method: GitHub download

**Additional Details:**
n/a

**Comment by loosla** [comment]
@andrewsomething Could you assign this issue to me? :pray:

**Comment by andrewsomething** [comment]
Fixed via https://github.com/digitalocean/doctl/pull/1547

**Comment by bentranter** [comment]
The fix is available in the latest release (https://github.com/digitalocean/doctl/releases/tag/v1.109.1).
