### ISSUE TITLE
Add --wait flag to databases migrate command

### ISSUE THREAD

**Issue by loosla** [digitalocean/doctl#1584]
**What is the problem this feature would solve? Please describe.**
doctl aims to be useful in scripting. One way it does this is by providing a --wait flag for long running, async operations to block until they are complete rather than making the user implement polling in their own script. Some examples include:

- `doctl database create --wait`
- `doctl compute droplet create --wait`
- `doctl kubernetes cluster create --wait`
- `doctl apps create --wait`

Currently the `doctl databases migrate` command does not have a `--wait` flag.

**Describe the solution you'd like**
Add a --wait flag to the `doctl databases migrate` command. It should poll the [/v2/databases/$DATABASE_ID/migrate](https://docs.digitalocean.com/reference/api/api-reference/#operation/databases_update_region), blocking until the database cluster's status attribute moves from migrating to online.

**Additional context**
Following the code path starting here demonstrates how `doctl database create`'s  `--wait` flag is implemented:

https://github.com/digitalocean/doctl/blob/de1918ad1ee4b1e523c335fa9254e85d415d18aa/commands/apps.go#L282

**Comment by shashank-priyadarshi** [comment]
@loosla can I please take this up?

**Comment by SkySingh04** [comment]
This looks like a fun issue, Will be working on this!

**Comment by shashank-priyadarshi** [comment]
@SkySingh04 it will possibly be duplicate effort as I have already started work on this.

**Comment by loosla** [comment]
I appreciate everyone's interest in contributing! Just a friendly reminder: when we assign someone to a PR in an open repository, it can sometimes limit opportunities for other developers to contribute, it may lead to issues being abandoned and work not progressing.

We generally would like to follow a first-come, first-served approach for assignments to ensure fairness.

I recommend leaving a comment to let others know you've started working on this issue and [link your PR](https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword), along with an approximate timeline for when you expect to finish. This way, everyone will be aware that you're handling it.

Thank you for your understanding! :ocean: :dolphin: :ocean:

**Comment by SkySingh04** [comment]
Thank you for the clarification @loosla , Do you recommend I work on this issue or can you point me towards any other CLI issue I can work towards? I have worked extensively on the [Keploy CLI ](github.com/keploy/keploy) tool before.

**Comment by shashank-priyadarshi** [comment]
> I recommend leaving a comment to let others know you've started working on this issue and [link your PR](https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword), along with an approximate timeline for when you expect to finish. This way, everyone will be aware that you're handling it.

Sure thanks @loosla .
I have indeed started work on this in the past week, and looking to close this by Mon.

**Comment by SkySingh04** [comment]
Hey @loosla , Since the deadline for this was Monday and no PR was raised, I have raised a PR for this issue!
