### ISSUE TITLE
Add --wait flag to databases resize command

### ISSUE THREAD

**Issue by loosla** [digitalocean/doctl#1585]
**What is the problem this feature would solve? Please describe.**
doctl aims to be useful in scripting. One way it does this is by providing a --wait flag for long running, async operations to block until they are complete rather than making the user implement polling in their own script. Some examples include:

- `doctl database create --wait`
- `doctl compute droplet create --wait`
- `doctl kubernetes cluster create --wait`
- `doctl apps create --wait`

Currently the `doctl databases resize` command does not have a `--wait` flag.

**Describe the solution you'd like**
Add a --wait flag to the `doctl databases resize` command. It should poll the [/v2/databases/$DATABASE_ID/resize](https://docs.digitalocean.com/reference/api/api-reference/#operation/databases_update_clusterSize), blocking until the database cluster's status attribute moves from resizing to online.

**Additional context**
Following the code path starting here demonstrates how `doctl database create`'s  `--wait` flag is implemented:

https://github.com/digitalocean/doctl/blob/de1918ad1ee4b1e523c335fa9254e85d415d18aa/commands/apps.go#L282

**Comment by Yordaniss** [comment]
Hello @loosla This one sounds interesting. Can you please assign this issue to me? 🙂 Thanks

**Comment by SkySingh04** [comment]
This looks like a fun issue, Will be working on this!

**Comment by Yordaniss** [comment]
Hey @SkySingh04 sorry i already started working on this and already created a PR ^^
