### ISSUE TITLE
pass ssh command line down to the actual ssh

### ISSUE THREAD

**Issue by mman** [digitalocean/doctl#168]
Right now ``doctl compute ssh droplet`` simply ignores all command line args specified so things like these do not work:

```
$ doctl compute ssh mydroplet uptime
$ doctl compute ssh mydroplet free
```

I think it would be cool to add ability to simply pass through all command line args not processed by ``doctl`` itself to the underlying ssh command for easy scripting

**Comment by andrewhowden** [comment]
doctl compute ssh mydroplet --ssh-command "uptime"
