### ISSUE TITLE
droplet delete name disambiguation

### ISSUE THREAD

**Issue by thisismitch** [digitalocean/doctl#18]
If you have multiple droplets with the same name, e.g. "ubuntu-2gb-nyc3-01", and issue a droplet delete command, doctl deletes the oldest one.

```
doctl compute droplet delete ubuntu-2gb-nyc3-01
```

This should be documented, or there should be a disambiguation or confirmation prompt.

**Comment by bryanl** [comment]
I'm leaning towards making it fail quick if it detects duplicate names. That way no decision needs to be made.
