### ISSUE TITLE
"Error: ssh: no key found" when adding ssh-key

### ISSUE THREAD

**Issue by timdream** [digitalocean/doctl#181]
When adding an new ssh key into DO, I got the `Error: ssh: no key found` error. This is on macOS 10.12.2.

Full output (token censored):

```
/tmp$ ssh-keygen -t ed25519 -f id_ed25519 -C "" -N ""
Generating public/private ed25519 key pair.
Your identification has been saved in id_ed25519.
Your public key has been saved in id_ed25519.pub.
The key fingerprint is:
SHA256:JO94mkmIgBr/jOOYcGeuyQPivzUP/+h1rIGvRX579iA
The key's randomart image is:
+--[ED25519 256]--+
|                 |
|                 |
|      . .        |
|.      +         |
|+       S.       |
|++ . . o+ .      |
|=.+ ++o.o= E .   |
|.*oO..=== = oo.  |
|o.B*= =*o+ .o .. |
+----[SHA256]-----+
/tmp$ doctl compute ssh-key import test --public-key-file id_ed25519.pub -t abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabc
import ssh key

Usage:
  doctl compute ssh-key import <key-name> [flags]

Aliases:
  import, i


Flags:
      --format string            Columns for output in a comma seperated list. Possible values: ID,Name,FingerPrint
      --no-header                hide headers
      --public-key-file string   Public key file (required)

Global Flags:
  -t, --access-token string   API V2 Access Token
  -c, --config string         config file (default is $HOME/.config/doctl/config.yaml)
  -o, --output string         output format [text|json] (default "text")
      --trace                 trace api access
  -v, --verbose               verbose output

Error: ssh: no key found
/tmp$
```

The same key can be added from the Web UI, and I can find the error message [here](https://github.com/golang/crypto/blob/c3b1d0d6d8690eaebe3064711b026770cc37efa3/ssh/keys.go#L241) from `golang/crypto`, so I guess this might be an upstream issue?

**Comment by timdream** [comment]
```
/tmp$ cat id_ed25519.pub
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGQBoMtNXivDai83BeEl/5L18MJgDg+G+wp7Ir9OcLg4
/tmp$
```

**Comment by timdream** [comment]
I think I misunderstood what `import` do. I should use `create`. Please
close this issue if it is no longer valid.

**Comment by andrewsomething** [comment]
Thanks for the report. I'm going to go ahead and close this, but you have helped surface a usability issue. If nothing else, the help output needs to be improved for both of those commands. It should be much more clear what the differences are.

**Comment by timdream** [comment]
@andrewsomething Thanks for the quick response. I'll leave to you to file an new issue on that.

(small nit: when paste the output the spell checker was also annoyed by the misspelled word "seperated". You could fix that too.)
