### ISSUE TITLE
snapshots

### ISSUE THREAD

**Issue by jaclu** [digitalocean/doctl#184]
Documentation unclear on syntax for generating new snapshots

**Comment by xmudrii** [comment]
Hi there! 
Can I help you with something specific?

**Version 1.5.0 and prior to 1.5.0** have following commands to help you create snapsohts:
## Droplet snapshots
### Creating snapshots
Command for creating snapshots is under `droplet-action` tree — `doctl compute droplet-action snapshot`.
**Syntax is following: `doctl compute droplet-action snapshot <droplet-id> --snapshot-name "some-name"`.**
Once executed, if successful, it'll return snapshot ID and other information:
```
ID		Status		Type		Started At			Completed At	Resource ID	Resource Type	Region
000000000	in-progress	snapshot	2017-01-25 16:35:15 +0000 UTC	<nil>		00000000	droplet		nyc1
```

### Listing snapshots
Command for Snapshots list is under `droplet` tree — `doctl compute droplet snapshots`.
It requires to provide you Droplet ID for which you want to see list of Snapshots. **Syntax is:
`doctl compute droplet snapshots <droplet-id>`.**
Sample output if operation is successful:
```
ID		Name	Type		Distribution	Slug	Public	Min Disk
000000000	test	snapshot	Ubuntu			false	20
```

### Removing snapshots
Command for removing Snapshots is located under `image` command tree — `doctl compute image delete`.
**Syntax is `doctl compute image delete <snapshot-id>`.**
In next step, you should be asked to confirm your intention. To do so, type 'y' and then press 'ENTER'. To skip confirmation you can use `force` flag:
`doctl compute image delete <snapshot-id> --force`.

### Renaming snapshots
Command for renaming is also located under `image` command tree — `doctl compute image update`.
**Syntax is `doctl compute image update <snapshot-id> --image-name "new-name"`.**
If successful, you should see list with that snapshot:
```
ID		Name		Type		Distribution	Slug	Public	Min Disk
000000000	new-name	snapshot	Ubuntu			false	20
```

## Volume (Block Storage) snapshots
**Commands for managing volumes snapshots are not available in version 1.5.0 or older!**

## Future of snapshot commands (development version)

As you can see, there are not in same place so it can be hard to keep up with it. To help users, new commands was implemented. Listing, getting and deleting snapshots is located in new command tree `snapshot`. Executing `doctl compute snapshot` will return you available actions:
```
snapshot is used to access snapshot commands

Usage:
  doctl compute snapshot [command]

Aliases:
  snapshot, s


Available Commands:
  list        list snapshots
  get         get snapshot
  delete      delete snapshot
```

Listing is done by executing: `doctl compute snapshot list`. It'll return list of snapshots for both Droplets and Volumes.
You can also get details of specific Droplet/Volume snapshot by executing: `doctl compute snapshot get <snapshot-id>`.
Deleting is done with: `doctl compute snapshot delete <snapshot-id>`. In next step you are asked to confirm intention. To do so, as already explained, type `y` and then press `ENTER`. Also you can use `--force` flag (and of this version shorthand flag `-f`).

Renaming and creating is where it was before.
Beside that you can also create Volume snapshot with `doctl compute volume snapshot <volume-id>`.
To get this version, you can build `doctl` from source, or wait for next release.

If you need anything more, feel free to ask me anything.
