### ISSUE TITLE
Can't login on windows

### ISSUE THREAD

**Issue by theminecoder** [digitalocean/doctl#19]
Just tried installing the client after the twitter post was announce and wanted to login, however the client isn't being so nice about it. `1.0` Releases eh?

Anyway when attempting to login, it seems that the client is ignoring all the argument flags and not actually running the auth flow (or at least clearly stating what it does) 
![image 2016-03-30 at 4 48 01 pm](https://cloud.githubusercontent.com/assets/1396368/14148564/ce7fc1f2-f697-11e5-99a7-2309ef03f101.png)

Also it seems to spin up my browser to an attempted auth page but all that prints is `unknown client`.

Goob job on a 1.0 attempt though guys, looking forward it working nicer :P

**Comment by bryanl** [comment]
I've been able to verify this, and I'm working out a fix for it right now.

**Comment by bryanl** [comment]
I'm working on a solution for this, and in the mean time, you can create a file called `.doctlcfg` in your home directory (not sure what this is on all versions of Windows) with the following contents:

```yaml
access-token: <your do access token>
```

You can manually retrieve an access token at https://cloud.digitalocean.com/settings/api/tokens

**Comment by narration-sd** [comment]
As well, doesn't work with the form of .doctlcfg in the documentation, which would be:

`{
    access-token: <yours>
    output: <json|text>
}`

The location on Win10 and likely earlier is c:\Users\yourusernameabbreviated\.doctlcfg

It does work just simply putting access-token: <yours> alone in the file, as you suggest above.

**Comment by bryanl** [comment]
The format isn't JSON, it's yaml

**Comment by narration-sd** [comment]
Hi Bryan -- yes, thanks; it came to me late in the night that it hadn't been JSON, but sensibly still needed it's comma. The state of coders doing documentation, and of course syntax is seldom the large problem....

Anyway, so many scripting so, so little time, also. We switch gears when we have our head into a page, and deal in the context, don't we.

Kind regards,
Clive

**Comment by darkmorpher** [comment]
I got **Error: exit status 1** too

`doctl auth login` opens up the browser but the page reads **unknown client**

v1.0

**Comment by Ahrotahntee** [comment]
Seeing a problem when attempting to authenticate on Windows as well. It looks like it's not reading the configuration file?

I confirmed the location of user.Current().HomeDir as C:\Users\Ahro, with the correct file name being .doctlcfg, but it doesn't seem to be reading the settings saved in the file. As per this thread I used YAML syntax, as well as trying it with just the single key option.

I attached a debugger and didn't see it even attempt to open the file before beginning network operations.

**Comment by bryanl** [comment]
@darkmorpher Those options are missing for ssh. Would you mind opening a new issue?

**Comment by bryanl** [comment]
@Ahrotahntee I'm trying to replicate your findings. I do have it working with Windows 10.

**Comment by klauern** [comment]
I'm having trouble with this `.doctlcfg` file.  I have it in my home, but it isnt' recognizing it.  However, I can pass the command-line flag to all commands and that works successfully:

```
C:\Users\Me > doctl -t <token> compute droplet-action shutdown <id>
ID              Status          Type            Started At                      Completed At    Resource ID     Resource Type   Region
<id>            in-progress     shutdown        2016-04-21 23:23:26 +0000 UTC   <nil>           <id 2>          droplet         nyc3
```

**Comment by klauern** [comment]
Ok, ignore my previous update.  I mis-typed the cfg file.  I had `.dotctlcfg` not `.doctlcfg`.

**Comment by Phrown420** [comment]
Unless I'm doing something wrong, I'm still getting this unknown client error, even with v1.1.0

**Comment by bryanl** [comment]
@Phrown420 logging with the tool is a known issue on Windows. To proceed, generate an access token at https://cloud.digitalocean.com/settings/api/tokens. Then you have 3 options.

1. Add an `access-token` entry to `.doctlcfg` (this will be the easiest)
2. Use the access token argument when running `doctl`
3. Set `DIGITALOCEAN_ACCESS_TOKEN` environment variable to your token.

**Comment by bryanl** [comment]
As I'm thinking right now `doctl auth login` will go away in the next release.  `doctl` will introduce something like `doctl auth init`, and that will require you to enter in your key.
