### ISSUE TITLE
doctl compute image-action transfer returns: 404 The specified action type is not available.

### ISSUE THREAD

**Issue by discordianfish** [digitalocean/doctl#192]
Maybe I'm doing something wrong but `doctl compute image-action transfer -o json --region sgp1 my-image-id` returns:

```
$ doctl compute image-action transfer -o json --region sgp1 12345
{"errors":[{"detail":"could not transfer image: POST https://api.digitalocean.com/v2/images/12345/actions: 404 The specified action type is not available."}]}
```

**Comment by xmudrii** [comment]
Hi @discordianfish,

First of all sorry for late response, but I've been able to reproduce this issue. I also found root of cause and fixed it in #196. Once it gets merged, it should work normally.

Thanks for report :) :+1:
