### ISSUE TITLE
--volumes requires a UUID while all other options can handle names/slugs

### ISSUE THREAD

**Issue by igalic** [digitalocean/doctl#205]
I recently tried building a droplet using the following cli:

```
doctl compute droplet create meenirx --enable-ipv6 \
  --enable-private-networking --image freebsd-11-0-x64-zfs \
  --size 512mb --ssh-keys 1234567 --volumes volume-fra1-01 \
  --region fra1
```

and got the following response from the API:

```
Error: POST https://api.digitalocean.com/v2/droplets: 500 (request "9b12fd54-ba34-4106-8244-8f0f2ca7c599")
  Looks like something went wrong. If this continues, please open a support ticket so we can help you out.
```

All other options are happy to take a name / slug, only volumes requires a UUID. That seems like inconsistent UI. If there's no way around this, the least we could do would be to add a check on doctl's side before sending it off to the API

**Comment by xmudrii** [comment]
Looking at the code, it appears that specifying volume by name is possible‎. [Function `extractVolumes` ~ Line 415 ](https://github.com/digitalocean/doctl/blob/master/commands/droplets.go#L415) check did you provided UUID or Name and resolves it to [an create object](https://github.com/digitalocean/godo/blob/master/droplets.go#L171) which has ID and Name fields.Make sure you provided name of already existing and **not-attached** volume‎. I'm not sure is it allowed to have multiple volumes with same name but check that too.I'm not able to test it, but once I can, I'll test it.

**Comment by nanzhong** [comment]
It should be possible to have volumes with the same name, but only if they are in different regions. On a per region basis, names must be unique.

@igalic we started deprecating the use of name/region pairs instead of uuids for volumes because it was adding confusion about uniqueness across/between regions. Absolutely agree about the inconsistency also being confusing though. 🤔

**Comment by mauricio** [comment]
Yeah, while inconsistent we're really moving out of names, tags are going to be the closest thing for this.
