### ISSUE TITLE
can't login on KDE

### ISSUE THREAD

**Issue by igalic** [digitalocean/doctl#21]
(either #19 ;)
I traced this one down to https://github.com/bryanl/webbrowser/issues/2 however.

**Comment by bryanl** [comment]
@igalic I created a fresh Ubuntu 14.04 install, and download the 1.0.0 release and ran `doctl auth login`. Firefox popped up, and logged me in. Afterwards, the access token was retrieved. Would you mind describing your setup, so I can help you diagnose?

**Comment by igalic** [comment]
so, i think we need to narrow this down to: KDE.

**Comment by vit1251** [comment]
Could you use auth token without using browser?

**Comment by bryanl** [comment]
Yes, if a `CLIAUTH` environment variable is set, it'll reply with a link you can visit in your browser. An easier method is to generate a token at https://cloud.digitalocean.com/settings/api/tokens, and add it to `$HOME/.doctlcfg` manually. The file format is yaml, so you'll add it like

```yaml
access-token: <your token>
```

In a future version, there will be a command to manage configuration items.

**Comment by bryanl** [comment]
We've decided to replace the `doctl auth login` with `doctl auth init`. It's being tracked in #94.
