### ISSUE TITLE
How to install this for Windows 10?

### ISSUE THREAD

**Issue by AlexioVay** [digitalocean/doctl#211]
Sorry for this noob question, but the file I downloaded is a "doctl" file and not executable. How can I install this CLI?

Thanks.

**Comment by xmudrii** [comment]
You need to download Windows binary from releases page. After that, unzip it where ever you want and it's ready to be used.

v1.6.0 release: https://github.com/digitalocean/doctl/releases/tag/v1.6.0

Windows 64-bit executable: https://github.com/digitalocean/doctl/releases/download/v1.6.0/doctl-1.6.0-windows-4.0-amd64.zip

Windows 32-bit executable: https://github.com/digitalocean/doctl/releases/download/v1.6.0/doctl-1.6.0-windows-4.0-386.zip

**Comment by vaydesign** [comment]
Ah okay, thanks. Is there an option to integrate this globally in my console to type "doctl" from any folder?

**Comment by AlexioVay** [comment]
Ah okay, thanks. Is there an option to integrate this globally in my console to type "doctl" from any folder?

**Comment by xmudrii** [comment]
To make it work as you want, you should put location to `doctl` in your `PATH` environmental variable.

I don't know exact steps for doing so as I'm not Windows user myself but this link should help you http://stackoverflow.com/a/28545224
It applies to Windows 7 but it should be same for Windows 10 too.

Less recommended way is to copy it to `system32` as explained here: https://superuser.com/a/288197
But I would first try adding it to `PATH`.

Note: if you can't access `doctl` executable after adding it's location to `PATH`, maybe you have to restart your computer after adding new dir to `PATH`.

**Comment by AlexioVay** [comment]
It works, thank you!
