### ISSUE TITLE
doctl should error when enabling monitoring on unsupported images

### ISSUE THREAD

**Issue by IOAyman** [digitalocean/doctl#212]
I understand that the monitoring feature that has been [recently announced][1] is not supported on base images such as Fedora.
However, if I `doctl compute d c XX --enable-monitoring --ssh-keys keyid ....`, it does create the droplet and echos no errors or warnings. But when I try to ssh into it afterwards the connection is refused.  
I guess that the droplet initialization process is failing each time because of the `--enable-monitoring` flag, thus keeping me out until I manually reset root password from the web console -which I don't always have access to.

If I my guess is right, I think _doctl_ should echo a warning when `--enabled-monitoring` is passed alongside an unsupported base image.

[1]: https://www.digitalocean.com/community/tutorials/an-introduction-to-digitalocean-monitoring

**Comment by mauricio** [comment]
This was fixed but we didn't go back here to mark this as sorted out, now it is :D
