### ISSUE TITLE
accept name of ssh key when specifying --ssh-keys from cli

### ISSUE THREAD

**Issue by dustymabe** [digitalocean/doctl#216]
Having to find the fingerprint and provide that to `doctl` is a bit of a pain. It would be a much better user experience if I were able to use the name of my key in the digitalocean interface instead of the fingerprint of the public key in order to identify it. 

i.e this is a bit of a pain:

```
# ssh-keygen -E md5 -lf /path/to/key.pub
2048 MD5:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx foo@gmail.com (RSA)
# doctl compute droplet create --image fedora-25-x64-atomic --region nyc3 --size 16gb --ssh-keys xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx  atomicdroplet
```

this would be better:

```
# doctl compute droplet create --image fedora-25-x64-atomic --region nyc3 --size 16gb --ssh-keys name-of-key  atomicdroplet
```

**Comment by xmudrii** [comment]
‎‎@mauricio @viola what do you think about this?

I would give this a try if you agree on adding it. Idea seems good and reasonable. Just like you can add SSH keys from Control Panel without worrying about ID/Fingerprint, we can resolve name to preferable option. 

Also, add a new flag, or make it use existing flag?

**Comment by viola** [comment]
@xmudrii @dustymabe there is a `ssh key commands` to quickly look up ssh key details including the fingerprint: `doctl compute ssh-key list` have you tried that?

**Comment by dustymabe** [comment]
@viola - yes. I found that after I fumbled around for a while. This is the 2nd time i've hit this same road block when using doctl and decided to open an issue this time. While having `doctl compute ssh-key list` does help, I think it would be much better to have `--ssh-keys` support names as well.

**Comment by viola** [comment]
@dustymabe thank you for the detailed explanation and I'm sorry to hear that you had troubles finding that feature.
@xmudrii while I don't have any objections to this reasonable request I'm afraid that at the moment we don't have a way to look up individual ssh-key via `name` nor we validate for the ssh key name uniqueness when creating one.  It's possible to have two or more keys with diffrent fingerprints and the same name as of now.

**Comment by xmudrii** [comment]
@viola @dustymabe Actually I have to agree. Looks like I was typing faster than thinking about it.

For now, we are mostly trying to stick around with IDs (and Fingerprints in SSH Key case). Especially because you can have duplicate names, it's hard to resolve it to ID with absolute precision. It's prone to confusion and errors so sticking to current option is best bet.
‎
With `compute ssh-key list` you can get list of SSH keys and their Fingerprints and IDs. 
If you are highly dependent on it and have any other ideas how to improve and incorporate it, feel free to write down‎, maybe we can help you.

**Comment by dustymabe** [comment]
> Especially because you can have duplicate names,

sounds like a bug to me, you fix that and you can fix this :) 

> If you are highly dependent on it and have any other ideas how to improve and incorporate it, feel free to write down‎, maybe we can help you.

Not highly dependent on it, just providing very useful feedback. It would have taken me 5 minutes to get up and running with the `doctl` versus 15. I think that is very valuable feedback to give, so I opened an issue.

**Comment by xmudrii** [comment]
@dustymabe ‎Actually, I wouldn't say it's a bug.‎ Many other resources such as Droplets, Volumes, Images (IIRC) allow same behavior. Maybe it sound weird for SSH keys now, but it's not that.
When working with API, ID is usually default property. To make it easier, in last time, there is shift to tagged resources wherever it's applicable. 
‎
If you want to learn `doctl` better, there's a [tutorial](https://www.digitalocean.com/community/tutorials/how-to-use-doctl-the-official-digitalocean-command-line-client) explaining most important stuff, you can give it a try. :)

**Comment by dustymabe** [comment]
> @dustymabe ‎Actually, I wouldn't say it's a bug.‎ Many other resources such as Droplets, Volumes, Images (IIRC) allow same behavior. Maybe it sound weird for SSH keys now, but it's not that. When working with API, ID is usually default property. To make it easier, in last time, there is shift to tagged resources wherever it's applicable.

yeah. I certainly would prefer names to be unique, but I didn't design it :) 

One suggestion on how to improve this without requiring unique ssh-key names would be to accept a name on the command line, then cross check to see if it is unique. If it is not unique then require the user to provide a fingerprint. If it is unique, then use the unique ssh key corresponding to the name.

**Comment by dustymabe** [comment]
not to troll too much, but it is worth pointing out that the aws tools have a better ui for this:

```
aws ec2 run-instances --image-id ami-815f6996 --key-name dustymabe-keypair ... 
```

**Comment by kevinrobayna** [comment]
I'm assuming this was never done, even if this was many years ago.

**Comment by davpaez** [comment]
> One suggestion on how to improve this without requiring unique ssh-key names would be to accept a name on the command line, then cross check to see if it is unique. If it is not unique then require the user to provide a fingerprint. If it is unique, then use the unique ssh key corresponding to the name.

This sounds like a good idea. I hope it gets implemented someday
