### ISSUE TITLE
Set TTL for domain record creation.

### ISSUE THREAD

**Issue by clemenko** [digitalocean/doctl#219]
Is it possible to set the TTL when creating a domain record?

current : 
`doctl compute domain records create shirtmullet.com --record-type A --record-name flask --record-data $server`

would like : 
`doctl compute domain records create shirtmullet.com --record-type A --record-name flask --ttl 900 --record-data $server`

**Comment by xmudrii** [comment]
‎@clemenko it's not possible for now to manage TTL for records with doctl.

However, this feature is added to API not so long ago, it will be added to doctl soon.

**Comment by clemenko** [comment]
Where can I find the api documentation?

**Comment by xmudrii** [comment]
‎You can find it at [DigitalOcean Developers site](https://developers.digitalocean.com/documentation/v2/).

**Comment by clemenko** [comment]
Please add this as a feature request for the next version of doctl.

**Comment by xmudrii** [comment]
@clemenko PR #220 should do the job.
Once this get merged, you can build from sources to make it available once this is done, or if you can't, it should be available in 1.7.0 :+1:
