### ISSUE TITLE
proposal: make doctl part of chocolatey package manager

### ISSUE THREAD

**Issue by xmudrii** [digitalocean/doctl#226]
For some time now, `doctl` is part of Homebrew package manager for macOS, and from not so long ago, Snap for Linux joined the party. That means that we don't support only Windows package managers.

As far as I know, Windows still don't have their official solution, but there are some community-driven ones. [Chocolatey](https://chocolatey.org/) seems like one of those, and most popular one, looking by community reviews.
Looking by their [catalog](https://chocolatey.org/packages), there are many popular packages and applications going from casual ones like WinRAR, VLC to developer oriented ones like Node.js, Docker, Kubernetes...

I don't use Windows for long time now, so I'm not really in their community and I don't know about state of package management for it. Searching the Internet and looking by some tweets, it seems like above solution is good to go for Windows.
If you know better and more popular solution, please comment below.

I would like to know, are you interested in adding `doctl` there. If yes, I could see could I be helpful with this and bring needed scripts and so on. I think I can get handy copy of Windows so I guess I can build some testing env.

Also, maybe somebody from DO legal team should check their license requirements. As far as I understand, it's free for Open Source projects to everybody, including companies, but it doesn't hurt to be checked by somebody who knows about it.

Fire up your opinions and critics. :+1: 

/cc @mauricio @viola @caueguerra @lxfontes @hugocorbucci @magicgrl111

**Comment by TonyApuzzo** [comment]
I think [Scoop](https://scoop.sh/) might be a better choice for installing `doctl` than Chocolatey.  I use both, but scoop is way simpler to maintain and since doctl is a lightweight app, it should be pretty trivial to build a scoop installer.

In fact, there already is a [scoop package for doctl](https://github.com/lukesampson/scoop/blob/master/bucket/doctl.json)!

**Comment by geordyvcErasmus** [comment]
> I think [Scoop](https://scoop.sh/) might be a better choice for installing `doctl` than Chocolatey. I use both, but scoop is way simpler to maintain and since doctl is a lightweight app, it should be pretty trivial to build a scoop installer.
> 
> In fact, when I just now went looking, I found that there already is a [scoop package for doctl](https://github.com/lukesampson/scoop/blob/master/bucket/doctl.json)!

Confirmed that installation via scoop works.
Would still be nice if we could have it in both package managers so we only need to use one.

Instructions:
1.  ```powershell iex (new-object net.webclient).downloadstring('https://get.scoop.sh') ```
     - (optional) ```powershell scoop install aria2``` (enables multiple downloads at the same time)
2. ```powershell scoop install doctl ```
3. Have fun using doctl

After the installation the installer will throw an error in my case but doctl works so no problem so far I think
```powershell
Rename-Item : Cannot rename because item at 'C:\Users\geord\scoop\apps\doctl\1.26.3\doctl' does not exist.
At line:1 char:1
+ Rename-Item "$dir\doctl" 'doctl.exe'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Rename-Item], PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,Microsoft.PowerShell.Commands.RenameItemCommand
```

**Comment by andrewsomething** [comment]
:tada:  Thanks to the work of an awesome community contributor, doctl is now available via Chocolatey:

    choco install doctl

https://chocolatey.org/packages/doctl
