### ISSUE TITLE
Feature Request: Suggested doctl CLI Command from Create Droplet UI

### ISSUE THREAD

**Issue by anthcor** [digitalocean/doctl#230]
Similar to how GCP has a suggested "oh you could use this command to create the same thing using `gcloud`" link at the bottom of their VM instance create page, it would be great to have a suggested  `doctl` command at the bottom of the create droplet(s) page of DO's console (https://cloud.digitalocean.com/droplets/new).

Not sure if this is the best place to leave a comment on this request, but hopefully someone can make a note of my feedback somewhere!

Thanks!

**Comment by joonas** [comment]
@anthcor that's a great suggestion, we'll definitely feed this back to our product teams.

I'll go ahead and close this out since there isn't anything actionable for us to do in terms of `doctl` itself :)
