### ISSUE TITLE
Plesee describe in README.md more detail about compile from source

### ISSUE THREAD

**Issue by vit1251** [digitalocean/doctl#24]
> Alternatively, if you have a Go environment configured, you can install the development
> version of doctl from the command line like so:
> go get github.com/digitalocean/doctl

I type **doctl** after this and have no success. I will doing additional shell steps?
Please clarify you REAMDE.md with this steps.

Thanx.

**Comment by Dr-Terrible** [comment]
Try `go get github.com/digitalocean/doctl/cmd/doctl`, which is the build path used by scripts/build.sh.

**Comment by brennen** [comment]
Patching the README shortly.

**Comment by vit1251** [comment]
> go get github.com/digitalocean/doctl/cmd/doctl

Thanx. Work for me.
