### ISSUE TITLE
how to enable monitoring on an existing droplet using doctl command

### ISSUE THREAD

**Issue by lucidprogrammer** [digitalocean/doctl#244]
Yes it is possible to --enable-monitoring during machine creation using doctl command.

However, I have a use case where the machine is created in some other manner. And do need a way to enable monitoring using the doctl command on the droplet. 

Can't see this in the documentation. Thanks.

**Comment by xmudrii** [comment]
@lucidprogrammer No, you can't enable monitoring using `doctl` or API.

You'll have to manually install agent, executing this command on the Droplet:
```bash
curl -sSL https://agent.digitalocean.com/install.sh | sh
```

You can use `doctl compute ssh` to access the Droplet using SSH. You can also try combining it with `--ssh-command` to send command via SSH directly from `doctl`, (_note: `--ssh-command` is not available in `doctl` for Windows_) such as:
```bash
doctl compute ssh droplet-name/ip --ssh-command "curl -sSL https://agent.digitalocean.com/install.sh | sh"
```

**Comment by lucidprogrammer** [comment]
@xmudrii tks, that should do.
