### ISSUE TITLE
Default configuration path is inconsistent

### ISSUE THREAD

**Issue by dwowitz** [digitalocean/doctl#246]
I am using version 1.7.0 on Linux.
When ```$XDG_CONFIG_HOME``` is unset, doctl reads the configuration from ```$HOME/.config/doctl/config.yaml```.
But when ```XDG_CONFIG_HOME=$HOME/.config```, doctl reads the configuration from ```$HOME/.config/config.yaml```.
This also happens when generating a configuration using ```doctl auth init```.
I think this can be changed by modifying the file ```doit.go``` however my attempts were unsuccessful.

**Comment by ncraike** [comment]
I am also having this issue on macOS 10.11.6 (El Capitan).

I'm not sure if it's a default of macOS, but my `XDG_CONFIG_HOME` is set to `$HOME/.config`. 

After running `doctl auth init` my Digital Ocean configuration has been written to `$HOME/.config/config`.
