### ISSUE TITLE
doctl firewall and load-balancer create sometimes fail

### ISSUE THREAD

**Issue by suonto** [digitalocean/doctl#248]
`doctl compute load-balancer create` and `doctl compute firewall create` fail randomly one time out of a hundred. Example:
```
doctl compute load-balancer create --name foo-lb-mutant-production --algorithm round_robin --region ams3 --tag-name foo-mutant-production --redirect --http-to-https --forwarding-rules entry_protocol:https,entry_port:443,target_protocol:https,target_port:443,tls_passthrough:true --health-check protocol:tcp,port:443,check_interval_seconds:20,response_timeout_seconds:10,healthy_threshold:3,unhealthy_threshold:2

create load balancer

Usage:
  doctl compute load-balancer create [flags]

Aliases:
  create, c


Flags:
      --algorithm string          load balancing algorithm, possible values: round_robin or least_connections (default "round_robin")
      --droplet-ids value         comma-separated list of droplet IDs, example value: 12,33 (default [])
      --forwarding-rules string   comma-separated key:value list, example value: entry_protocol:tcp,entry_port:3306,target_protocol:tcp,target_port:3306
, use quoted string of space-separated values for multiple rules
      --health-check string       comma-separated key:value list, example value: protocol:http,port:80,path:/index.html,check_interval_seconds:10,respon
se_timeout_seconds:5,healthy_threshold:5,unhealthy_threshold:3
      --name string               load balancer name (required)
      --redirect-http-to-https    flag to redirect HTTP requests to the load balancer on port 80 to HTTPS on port 443
      --region string             load balancer region location, example value: nyc1 (required)
      --sticky-sessions string    comma-separated key:value list, example value: type:cookies,cookie_name:DO-LB,cookie_ttl_seconds:5
      --tag-name string           droplet tag name

Global Flags:
  -t, --access-token string   API V2 Access Token
  -c, --config string         config file (default is $HOME/.config/doctl/config.yaml)
  -o, --output string         output format [text|json] (default "text")
      --trace                 trace api access
  -v, --verbose               verbose output

Error: invalid character 'L' looking for beginning of value
```

**Comment by xmudrii** [comment]
Hi @suonto,

First of all, there seems to be few errors in the syntax of the command.
`--redirect -http-to-https` should be `--redirect-http-to-https`.
`--health-check protocol :tcp,port:443,check_interval_seconds:20,response_timeout_seconds:10,healthy_threshold:3,unhealthy_threshold:2` have one space more than it should, between protocol and tcp. It should be `--health-check protocol:tcp,port:443,check_interval_seconds:20,response_timeout_seconds:10,healthy_threshold:3,unhealthy_threshold:2`.

At the end, command should be like this:
```
doctl compute load-balancer create --name foo-lb-mutant-production --algorithm round_robin --region ams3 --tag-name foo-mutant-production --redirect-http-to-https --forwarding-rules entry_protocol:https,entry_port:443,target_protocol:https,target_port:443,tls_passthrough:true --health-check protocol:tcp,port:443,check_interval_seconds:20,response_timeout_seconds:10,healthy_threshold:3,unhealthy_threshold:2
```
For me it returns
```
ID                                      IP    Name                         Status    Created At              Algorithm      Region    Tag                      Droplet IDs    SSL     Sticky Sessions                                Health Check                                                                                                                   Forwarding Rules
334e1ada-93f4-416e-8e1a-53527f9f14a3          2foo-lb-mutant-production    new       2017-08-10T08:27:30Z    round_robin    ams3      foo-mutant-production                   true    type:none,cookie_name:,cookie_ttl_seconds:0    protocol:tcp,port:443,path:,check_interval_seconds:20,response_timeout_seconds:10,healthy_threshold:3,unhealthy_threshold:2    entry_protocol:https,entry_port:443,target_protocol:https,target_port:443,certificate_id:,tls_passthrough:true
```

So make sure that you typed everything correctly and **that you have latest version**.
To check version, you can use `doctl version`, which should return `1.7.0` (or `1.0.0-dev` if you built from source). If you already have latest version, you can try building from source if you have working Go development environment.

This could be also issue of digitalocean/godo#142, but I think this should be fixed already?
@mauricio could give more details for us if needed.

**Comment by suonto** [comment]
@xmudrii forgive me my bad copy paste formatting, I use VSCode that sadly adds line separators when you copy multiline commands from the integrated terminal. Anyway, I can assure you that the syntax is correct when I run this command as part of my DO-automation scripts. I don't know if this has anything to do with digitalocean/godo#142 but I can assure you that the error only happens in the mentioned commands (not for example in droplet create) and it happens quite frequently. However, most of the time the commands work.

**Comment by xmudrii** [comment]
‎It could be above mentioned issue. I've seen it with Droplets endpoint last days as well.

We will need somebody from DO to take a look into it, as it's very possible some API problem. I'll also take a look into ‎the code to see is there something to tweak up.

/cc @mauricio

**Comment by mauricio** [comment]
Error messages should be better now with the latest godo in place :D
