### ISSUE TITLE
Documentation mismatch

### ISSUE THREAD

**Issue by vit1251** [digitalocean/doctl#25]
In document https://www.digitalocean.com/community/tutorials/how-to-use-doctl-the-official-digitalocean-command-line-client you describe ".doctlconfig" but in current repository you say about ".doctlcfg".

Other problem is configuration file format is undefined it see like JSON but no where describe about this format.

**Comment by brennen** [comment]
Good catch, re: `.doctlconfig`.  I'll tidy that up in the tutorial.

**Comment by bryanl** [comment]
This is issue has to been fixed at the https://www.digitalocean.com/community/tutorials/how-to-use-doctl-the-official-digitalocean-command-line-client
