### ISSUE TITLE
Zsh completion

### ISSUE THREAD

**Issue by HalisCz** [digitalocean/doctl#250]
Feature request:

Zsh completion, similar to bash completion solved in #90

**Comment by xmudrii** [comment]
@HalisCz It's already implemented in #206, you can use `doctl completion zsh` for zsh completions.

**Comment by HalisCz** [comment]
First of all, thank you very much for really quick response.

Second of all, do you consider to place generated completion in standard system paths (i.e. /etc/bash_completion.d/)?

**Comment by xmudrii** [comment]
‎For now, we are letting user to decide however it wants to use completions. This way we don't have to mind about permissions, settings and user preferences.  

You can freely create file with completions there or use `source`.

You can take a look at few examples by executing `doctl completion --help`.
