### ISSUE TITLE
Transfer ownership of doctl snap to you

### ISSUE THREAD

**Issue by popey** [digitalocean/doctl#253]
[Previously](https://github.com/digitalocean/doctl/issues/136), snap support was discussed, and the [yaml](https://github.com/digitalocean/doctl/blob/master/snap/snapcraft.yaml) is now upstream. We have a snap in the store, which is maintained by our community [snapcrafters](https://github.com/snapcrafters/doctl). 

However we'd prefer that, now you have a yaml in your master branch, we transition the ownership of the snap upstream to you. This should be a fairly painless process, which we can help navigate. Essentially, we need to have:-

  * You register with the snap store at http://dashboard.snapcraft.io/
  * Let us know your account details
  * We request the snap is moved across to your account
  * You hook up our [build service](http://build.snapcraft.io) to push automatically to the store - or you use whatever CI system you prefer to push to the store.

Once you've got an account registered in the store, we can move forward. Do let us know if you have any problems.

**Comment by mauricio** [comment]
Hey @popey,

Account email is mlinhares@digitalocean.com , what else do you need?

**Comment by popey** [comment]
Thanks! I've requested our store team to move the snap over to your account, and cc'ed you on the mail.
