### ISSUE TITLE
Would be nice if region list displayed available features

### ISSUE THREAD

**Issue by vendion** [digitalocean/doctl#255]
It would be nice if the region list command listed if the region list command displayed the available features for each region as reported by the [API](https://developers.digitalocean.com/documentation/v2/#regions). One big thing that would be nice to know is if Volumes and Spaces are available in that region yet or not (depends on if this is reported back from the API or not I guess).

**Comment by mauricio** [comment]
Hey @vendion, right now we don't have a way to collect that information, but will definitely send this down as it's an interesting feature, thanks!

**Comment by xmudrii** [comment]
@mauricio Huh, I think we actually have a way to collect that information. API is reporting it indeed, e.g.:
```
{"regions":[{"name":"New York 1","slug":"nyc1","sizes":["512mb","1gb","2gb","c-2","4gb","c-4","8gb","c-8","16gb","m-16gb","c-16","32gb","m-32gb","48gb","c-32","m-64gb","64gb","m-128gb","m-224gb"],"features":["private_networking","backups","ipv6","metadata","install_agent","storage"],"available":true},...]}
```
We can't check the Spaces, as this is not the same thing, but we can definitely check for Volumes.

If you want, I can make comeback to doctl project and try to add Volumes at least :joy:

**Comment by vendion** [comment]
I figured Spaces was a long shot since it is so new/early stages but would have been surprised if Volumes couldn't be reported, my guess on the previous confusion is the `storage` label instead of `volumes` (if that even is the right feature).  It would be nice to see this kind of information presented so a user doesn't provision a droplet in a region that doesn't have volume support and that is critical for the VM causing them to destroy and reprovision elsewhere.
