### ISSUE TITLE
What broke Jim?

### ISSUE THREAD

**Issue by vit1251** [digitalocean/doctl#26]
Receive follow problem

```bash
$ doctl auth login
login to DigitalOcean account

Usage:
  doctl auth login [flags]

Flags:
  -h, --help   help for login

Global Flags:
  -t, --access-token string   DigitalOcean API V2 Access Token
  -o, --output string         output formt [text|json] (default "text")
      --trace                 verbose output
  -v, --verbose               verbose output

Error: it's broke, Jim
```

What wrong? And I am is not Jim ;) How to determine my name in confg ;)

**Comment by mattkanwisher** [comment]
Yeah there appears to be a issue with "auth login" command we are looking into that. Other commands should be working like "compute droplet list" make sure your ~/.doctlcfg is setup.

As for Jim, I think I found him ...

https://storiesbywilliams.files.wordpress.com/2013/02/captain-kirk1.jpg

**Comment by bryanl** [comment]
Hello, I've fixed this issue, and logins should work.

**Comment by mattkanwisher** [comment]
Btw I found Jim...

![Jim](https://storiesbywilliams.files.wordpress.com/2013/02/captain-kirk1.jpg)

**Comment by vit1251** [comment]
I have message "Failed to execute default Web Browser." and content "Input/Ouput error.".
I can work wit doctl without auth login? Work only via API without require X11?

**Comment by mattkanwisher** [comment]
@vit1251 if you save your auth key to ~/.doctlcfg or set DIGITALOCEAN_ACCESS_TOKEN environment variable you don't need to do "auth login"

**Comment by vit1251** [comment]
> if you save your auth key to ~/.doctlcfg or set DIGITALOCEAN_ACCESS_TOKEN environment variable you don't need to do "auth login"

I can not. I does not know format of ".doctlcfg".

**Comment by mattkanwisher** [comment]
In the read.me in the repo there is an example you can do like this:

cat ~/.doctlcfg
```
access-token: "your auth token here"
output: "text"
```
