### ISSUE TITLE
doctl compute image list-distribution command does not work

### ISSUE THREAD

**Issue by indrayam** [digitalocean/doctl#261]
Hi there.

Brand new user of doctl. I was looking to run a command to get the list of slugs for the various distributions that DO offers.

Running the following command returns blank:
doctl compute image list-distribution
OR
doctl compute image list-application

When I run the following:
doctl compute image list

I do get two snapshots that I had created in 2016. I was kinda surprised to see those, cause I thought I had deleted those snapshots.

Anyways, how do I get this:
Available images, including snapshots, backups, and base distribution images. Use the string in the "Slug" column for creating new Droplets.

doctl compute image list does not return base distribution images. Only the snapshots I had created.

**Comment by xmudrii** [comment]
There should be `--public` flag or something like this which includes all images in the output. If it isn't `--public`, you can use `-h`‎ flag for help and it'll show you exact name of the flag

**Comment by indrayam** [comment]
Brilliant. Thanks!

I first ran this command:
doctl compute image list --help

This command gave me the information that I was looking for.

The command that did the trick was:
doctl compute image list --public

Once again, much appreciated!
