### ISSUE TITLE
ubuntu/xenial64: doctl compute ssh: Error: fork/exec /usr/bin/ssh: permission denied

### ISSUE THREAD

**Issue by binary64** [digitalocean/doctl#263]
Using `vagrant init ubuntu/xenial64` and running `doctl compute ssh 66376976` I get:

`Error: fork/exec /usr/bin/ssh: permission denied`

ssh using `ssh` directly works fine

**Comment by arosales** [comment]
I am also seeing this error, however I am only able to reproduce with the snap.

```
$ sudo snap install doctl

doctl 1.7.0 from 'digitalocean' installed
```

`$ doctl compute droplet list` returns correct droplet information

However, when I trying to ssh via doctl I get an error. Note ssh'ing directly works fine.
```
$ doctl compute ssh ubuntu-17.10
ssh to droplet

Usage:
  doctl compute ssh <droplet-id|host> [flags]

Flags:
      --ssh-agent-forwarding   enable ssh agent forwarding
      --ssh-command string     command to execute
      --ssh-key-path string    path to private ssh key
      --ssh-port int           port sshd is running on (default 22)
      --ssh-private-ip         ssh to private ip instead of public ip
      --ssh-user string        ssh user (default "root")

Global Flags:
  -t, --access-token string   API V2 Access Token
  -c, --config string         config file (default is $HOME/.config/doctl/config.yaml)
  -o, --output string         output format [text|json] (default "text")
      --trace                 trace api access
  -v, --verbose               verbose output

Error: fork/exec /usr/bin/ssh: permission denied
```

The snap installs doctl 1.7.0:
```
$ doctl version
doctl version 1.7.0-release
Git commit hash: bc52eb7
release 1.7.1 is available, check it out! 
```
Additional snap info:
```
snap info doctl
name:      doctl
summary:   Digital Ocean command line tool
publisher: digitalocean
contact:   https://github.com/digitalocean/doctl/issues
description: |
  DigitalOcean's web based control panel provides a
  convenient, point-and-click interface for managing
  Droplets. There are, however, times when a command-line
  tool may be a preferable alternative; If you have many
  Droplets to manage, need to administer Droplets from the
  terminal without a graphical desktop available, or have
  tasks which would benefit from a scriptable interface.
snap-id:     37RaX7lHS7bKamfcFcXcx27EyAaCIzgG
channels:               
  stable:    1.7.0 (13) 3MB -
  candidate: 1.6.0 (2)  3MB -
  beta:      1.6.0 (2)  3MB -
  edge:      1.7.0 (13) 3MB -
```
---
However, when I access the 1.7.0 binary directly by downloading the tar from the release page I do not see the error:

```
$ ./doctl compute ssh ubuntu-17.10
Welcome to Ubuntu 17.10 (GNU/Linux 4.13.0-16-generic x86_64)
$ ./doctl version
doctl version 1.7.0-release
Git commit hash: bc52eb7
release 1.7.1 is available, check it out!
```
I also don't see this in the 1.7.1 release when using the binary directly:
```
$ ./doctl version
doctl version 1.7.1-release
Git commit hash: ab54ea4
$ ./doctl compute ssh ubuntu-17.10
Welcome to Ubuntu 17.10 (GNU/Linux 4.13.0-16-generic x86_64)
```

Thus, this appears to be an issue with the snap.

**Comment by OpenWaveDigital** [comment]
I'm having the same exact issue, with doctl version and installation method identical to what was mentioned above.

**Comment by arosales** [comment]
@OpenWaveDigital thanks for confirming. I believe there is a permissions bug that needs to be sorted in the snap. As a work around use the 1.7.1 doctl binary directly via:
  https://github.com/digitalocean/doctl/releases
Then continue on with the installations instructions in option 2 at:
  https://github.com/digitalocean/doctl#option-2--downloading-a-release-from-github

The snap will provide a more straight forward installation and update process once the bugs are sorted.

hth,
-Antonio

**Comment by jacob-israel-turner** [comment]
Having the same issue here, after installing with Snap.  Going to try the Github release.

**Comment by blahah** [comment]
this is still an ongoing issue - tugboat, the very old unofficial ruby client for digitalocean api, continues to work fine. Would be great to be able to swap to the official client :)
