### ISSUE TITLE
Feature Request: droplet-action by hostname, when possible

### ISSUE THREAD

**Issue by benyanke** [digitalocean/doctl#265]
currently, if I need to bounce my box, I need two commands to reboot 

```
# Find the int ID of the droplet
doctl compute droplet ls | grep "example.com"

# Use the ID above to run command on example.com (id 123456)
doctl compute droplet-action power-cycle 123456
```
This requires one extra step than one would typically expect.

However, most users, I would imagine, only have a few boxes. I'd like to propose another syntax combining these two commands into a single shorthand (commands by hostname):

```
doctl compute droplet-action power-cycle example.com
```
which would be functionally equivilent to the bash command (yes, I know the grep isn't precise, just a rough example):
```
doctl compute droplet-action power-cycle  `doctl compute d ls | grep "example.com" | awk '{print $1}'`
```

When the number of droplets with the hostname of `example.com` = 1, this should introduce no logical issues.

Thoughts?

**Comment by mauricio** [comment]
Hey @benyanke, we've been thinking about this for tags as they are the grouping we have right now but not for names as they're not directly searchable in the system, that way you'd be able to perform operations on droplets grouped by specific tags instead of having to remember all names.
