### ISSUE TITLE
error: snap "doctl" not found

### ISSUE THREAD

**Issue by aj07** [digitalocean/doctl#269]
Ubuntu 16.04 32 bit

Why I am getting this error>
error: snap "doctl" not found

**Comment by xmudrii** [comment]
Could be related to #253, I'm not sure what's the status of this. /cc @mauricio 

In meanwhile, you can download latest release straight from the [GitHub releases](https://github.com/digitalocean/doctl/releases/tag/v1.7.1).

**Comment by kamaln7** [comment]
This was taken care of at some point so I'm closing this issue. A `doctl` snap is currently available.
