### ISSUE TITLE
doctl compute droplet list: Support matching multi tags

### ISSUE THREAD

**Issue by klausenbusk** [digitalocean/doctl#272]
Hello

`doctl compute droplet list` currently only support matching a single tag.

Could it be extended to support matching multi tags? I want to get the droplet with tag `k8s` (Kubernetes node) and `master` (Kubernetes master node).

\- Kristian

**Comment by xmudrii** [comment]
API doesn't provide any Droplet-related endpoint for listing Droplets my multiple Tags. Maybe there're some workarounds such as using [Retrieve a Tag](https://developers.digitalocean.com/documentation/v2/#retrieve-a-tag) endpoint to get all tagged resources and then filter Droplets only.

**Comment by mauricio** [comment]
We don't currently have this available over the API but it's something we're considering.
