### ISSUE TITLE
snaphots have a Name but no Slug

### ISSUE THREAD

**Issue by igalic** [digitalocean/doctl#274]
it makes it tricky to treat a Snapshot the same as an Image, because it's currently not possible to set a snapshot's Slug (and the name is copied over).

This also means that when passing a snapshot for the --image parameter, we need to resolve its ID first

**Comment by mauricio** [comment]
Hey @igalic, slugs are kind of special for the way we handle public/private images, since they have to be unique in the system and it would be complicated to expose that functionality through the API, we might provide something like that in the future but it's not in the plans for now.
