### ISSUE TITLE
Publish doctl to Docker Hub

### ISSUE THREAD

**Issue by shnhrrsn** [digitalocean/doctl#275]
Is there any reason this isn't auto-published to Docker Hub on release?  I'm unclear on why it needs to be built locally, it'd be great if I could just `docker run digitalocean/doctl`

**Comment by sagebind** [comment]
Any chance of this happening? This would make it a lot easier for me to set up various cron jobs in my DigitalOcean Kubernetes cluster.

It seems like it should be pretty easy for the maintainers to do. You already have automated builds in Travis, just build the Docker image & push for tags as one additional step...

**Comment by hilary** [comment]
We're auto-publishing to Docker Hub as of v1.24.1
