### ISSUE TITLE
How to list image slugs for DO-provided distros?

### ISSUE THREAD

**Issue by anxiousmodernman** [digitalocean/doctl#279]
I'm trying to launch a vanilla ubuntu server via terraform. I've tried multiple permutations of `doctl compute image list-*`, to get the id (or the slug) but only my own images show up.

IIRC, the standard DO-provided distros used to show up. Is this a bug or should I look somwhere else? Is there another flag I need to provide?

![foo](https://user-images.githubusercontent.com/396004/33640840-c4fda506-d9e7-11e7-9aa8-b968f2c54b59.png)

doctl version: 1.7.1-release

**Comment by siers** [comment]
https://github.com/digitalocean/doctl/issues/261
> xmudrii commented on Oct 8:
There should be `--public` flag or something like this which includes all images in the output. If it isn't `--public`, you can use `-h`‎ flag for help and it'll show you exact name of the flag.

    % doctl compute image list --public | head -n5                                                                                                                                                          
    ID          Name                                          Type        Distribution     Slug                    Public    Min Disk                                                                                                 
    29917700    1590.2.0 (beta)                               snapshot    CoreOS           coreos-beta             true      20
    13764801    Elixir on 14.04                               snapshot    Ubuntu                                   true      30
    14782899    6.7 x32                                       snapshot    CentOS           centos-6-5-x32          true      20
    14782952    6.7 x64                                       snapshot    CentOS           centos-6-5-x64          true      20

**Comment by anxiousmodernman** [comment]
Gotcha! `doctl compute image list --public` is what I've been looking for.
