### ISSUE TITLE
No .doctlconfig format specified

### ISSUE THREAD

**Issue by vit1251** [digitalocean/doctl#28]
Hello,

Please clarify file format of **.doctlconfig** in documentation.
Now it look like JSON but not quote a string on another source like issue it look like:

```
key1: value1
key2: value2
```

Please describe format or/and provide information about reading parameters in debug or verbose mode.

**Comment by bryanl** [comment]
the file is `$HOME/.doctlcfg`. It's YAML formatted:

```yaml
access-token: <digitalocean token id>
```

You can retrieve a token from: https://cloud.digitalocean.com/settings/api/tokens
