### ISSUE TITLE
doctl releases

### ISSUE THREAD

**Issue by indrayam** [digitalocean/doctl#283]
Any plans to enhance the `doctl version` command to behave like `gcloud version` command so that it will automatically prompt if there was a newer version available and allow it to be updated.

It would make it easier to ensure that we are always running the latest version of `doctl` command line utility.

**Comment by xmudrii** [comment]
When you're run `doctl version` it tells you if there is a new version available.
However, in case you build manually from source, it'll not show you that there's always new version available as it's coded to `1.0.0`:
```
doctl version 1.0.0-dev
release 1.7.1 is available, check it out!
```

**Comment by indrayam** [comment]
Brilliant! Guess I have been actively using it since 1.7.1. Just need to be more patient 😄

**Comment by mauricio** [comment]
1.7.2 is coming in a bit as well :)
