### ISSUE TITLE
Getting a list of my Droplets into one file? 

### ISSUE THREAD

**Issue by AFvloginov** [digitalocean/doctl#288]
Hi All,

Does anyone know how to get a list of all VM droplets into one file?
Ideally, it would be great to get all VMs with the following details:
- Name
- RAM
- Hard Drive
- Created date

Thanks in advance.

**Comment by xmudrii** [comment]
Hi there,

You can use output redirection to forward output to the file, for example:
```
doctl some-command > doctl-output.txt
```

To filter down the output and choose only needed columns, you can use the `--format` flag.
For example, the `doctl compute droplet list --format="Name,Memory,Disk,Status"` command would something along this:
```
Name                    Memory    Disk    Status
ubuntu-512mb-nyc3-01    512       20      active
ubuntu-512mb-nyc3-02    512       20      active
```

Append to the end of the command `> output.txt` to get the `output.txt` file with same content as the above output.

You can also hide headers using the `--no-header` flag:
```
doctl compute droplet list --format="Name,Memory,Disk,Status" --no-header
```
```
ubuntu-512mb-nyc3-01    512    20    active
ubuntu-512mb-nyc3-02    512    20    active
```

This is the plain-text output and therefore, it could be harder to parse it. You can also output the command's result in JSON format, using the `--output` flag:
```
doctl compute droplet --output=json
```
```
[                        
  {                                                                                                                                                                             
    "id": 78395000,              
    "name": "ubuntu-512mb-nyc3-01",   
    "memory": 512,                      
    "vcpus": 1,                   
    "disk": 20,              
    "region": {   
      "slug": "nyc3",                            
      "name": "New York 3",
...
```

Beside `list` command, there's `get` command, which support templates as well. However, it requires you to explicitly provide Droplet's ID.

For more details about using, you can check out our Community tutorial, [How To Use Doctl, the Official DigitalOcean Command-Line Client](https://www.digitalocean.com/community/tutorials/how-to-use-doctl-the-official-digitalocean-command-line-client#generic-doctl-usage), which covers both formatting and templates.
If you have any additional questions, feel free to ping me here and I'll try to help you as much as I can.
