### ISSUE TITLE
domain records list flag --domain-name does nothing

### ISSUE THREAD

**Issue by michaelpporter** [digitalocean/doctl#289]
```bash
doctl compute domain records list -h

Flags:
      --domain-name string   Domain name
```

When I run the list command with the flag it returns the whole list of entries.

```bash
 doctl compute domain records list example.com --domain-name=sub-domain
12345678 A sub-domain [etc]
1234567a CNAME sub-domain-2 [etc]
```

I would like to be able to get just the ID for deleting the record

```bash
doctl compute domain records list example.com --domain-name=sub-domain  --format ID
12345678
```

**Comment by xmudrii** [comment]
As far as I can see in the code, the `--domain-name` flag is actually not implemented anywhere.
It is declared in [domains.go#L63](https://github.com/digitalocean/doctl/blob/master/commands/domains.go#L63) but not referenced anywhere else.

If anybody has an idea how it should work, feel free to present it, I can give a try at implementing it.
In the meanwhile, as a temporarily workaround, you can try using `grep` to filter the output.

**Comment by michaelpporter** [comment]
FYI: Current method

```bash
doctl compute domain records create example.com --record-data $env.HOSTIP --record-name ${siteName} --record-type A
```

```bash
NUMBER="$(doctl compute domain records list example.com | grep ${siteName} | awk '{print $1;}')"
doctl compute domain records delete example.com $NUMBER -f
```

**Comment by michaelpporter** [comment]
I have run in to an issue using grep to get the ID in a script.

If a site has master and master2 as a subdomain grep returns both IDs.

```bash
doctl compute domain records list example.com | grep "\<site-master\>"
12345678    A        site-master-2        192.123.123.124                                                           0           0       3600     0
12345679    A        site-master          192.123.123.124                                                           0           0       1800     0
```

**Comment by michaelpporter** [comment]
```bash
doctl compute domain records list example.com | grep '\ssite-master\s'
```

**Comment by mauricio** [comment]
Yeah, right now the API doesn't provide a way to filter out domains when listing them, that domain-name option needs to go away, not sure what it is doing there.
