### ISSUE TITLE
Release to Package Managers

### ISSUE THREAD

**Issue by ZacharyDuBois** [digitalocean/doctl#29]
You should release it to several different package managers such as [Homebrew](http://brew.sh) and APT repositories (preferably make your own).

**Comment by XzAeRo** [comment]
It's already available through Homebrew.

**Comment by ZacharyDuBois** [comment]
Then it should say in the README under installation :) I'll PR it.

**Comment by bryanl** [comment]
@ZacharyDuBois it was updated to 1.0.0 

https://github.com/Homebrew/homebrew/commit/a2da4fd3dd748a59a6efff52a5bf949a643c69a4

It's in master now.
