### ISSUE TITLE
How to add multiple Volumes when creating a droplet.

### ISSUE THREAD

**Issue by IAlwaysBeCoding** [digitalocean/doctl#290]
I've tried to do this

--volumes ["some-volume-id", "some-volume-id2"] but it doesn't work.

The docs and api isn't really clear and I can't find an example of how to do it.

**Comment by andrewsomething** [comment]
With `doctl` you do not need the surrounding brackets, just a comma separated list without any white space in-between. For example:

```
doctl compute droplet create \
    --size s-1vcpu-1gb \
    --image ubuntu-16-04-x64 \
    --region fra1 \
    --volumes 70777244-810b-11e7-be65-0242ac110908,4acfbd7d-085c-11e8-aa55-0242ac11180a \
    example-01
```

**Comment by IAlwaysBeCoding** [comment]
Got it! Okay , I guess coming from python I was reading the default : [] as an empty list, so was using a list format.
