### ISSUE TITLE
Using doctl, is there a way to see logs from the Load Balancers that we setup?

### ISSUE THREAD

**Issue by indrayam** [digitalocean/doctl#293]
Hi there:

I seem to be getting errors from my DO Load Balancer when I enable Cloud Firewall rules on my Droplets. That said, I do not seem to have a way to see what is erroring out?

Any chance we could see the error logs from the load balancer if it is having issues connecting to the backend? Any chance we can use doctl to see it?

Sincerely,

Anand

**Comment by mauricio** [comment]
Hey @indrayam, this isn't available right now but we've added it to our wishlist, definitely an interesting feature!

**Comment by indrayam** [comment]
Thanks!

**Comment by tpo** [comment]
So @mauricio has correctly noted that having Load Balancer logs would be very useful. Then he closed this ticket as "completed". So where is this feature available?

```
$ doctl compute load-balancer help
[...]
Available Commands:
  add-droplets            Add Droplets to a load balancer
  add-forwarding-rules    Add forwarding rules to a load balancer
  create                  Create a new load balancer
  delete                  Permanently delete a load balancer
  get                     Retrieve a load balancer
  list                    List load balancers
  purge-cache             Purges CDN cache for a global load balancer
  remove-droplets         Remove Droplets from a load balancer
  remove-forwarding-rules Remove forwarding rules from a load balancer
  update                  Update a load balancer's configuration
```
