### ISSUE TITLE
Remove `completion` from auto completion

### ISSUE THREAD

**Issue by eddiezane** [digitalocean/doctl#297]
When typing out `doctl comp` and hitting tab `compute` does not immediately complete because `completion` is also an option. I think it's safe to not expect anyone to need to auto complete `completion`.

![image](https://user-images.githubusercontent.com/959573/37722573-b99b28a0-2d02-11e8-8850-c32da6e280df.png)

**Comment by mauricio** [comment]
Haha, yeah, we'll get that sorted out :D

**Comment by kamaln7** [comment]
Per https://github.com/spf13/cobra/blob/6644d46b81fa1831979c4cded0106e774e0ef0ab/bash_completions.go#L304-L306 & https://github.com/spf13/cobra/blob/c439c4fa093711d42e1b01acb1235b52004753c1/command.go#L1200-L1214:

It doesn't look like there's an easy way to hide a command from the generated autocompletion code without removing the `completion` command from `DoitCmd`. Or, add the option to hide commands from autocompletion to cobra 😉 

https://github.com/digitalocean/doctl/blob/master/commands/completion.go#L88

**Comment by kamaln7** [comment]
Removing just `commands+=("completion")\n` seems to be enough on both bash and zsh. The subcommands are taken care of automatically.

**Comment by eakraly** [comment]
I would even reduce the hierarchy of commands by 1 level, assuming `compute` is default.
99% of daily usage is `doctl compute` so why not make it shorter?

For example:
`doctl droplet list`
`doctl images list`
`doctl account get`

**Comment by eddiezane** [comment]
@eakraly

> I would even reduce the hierarchy of commands by 1 level, assuming compute is default.
99% of daily usage is doctl compute so why not make it shorter?

I'd imagine this is to namespace the commands to give us the freedom to make non-breaking changes or introduce new product.

**Comment by eddiezane** [comment]
FYI https://github.com/spf13/cobra/pull/671
