### ISSUE TITLE
--ssh-port option ignored

### ISSUE THREAD

**Issue by XzAeRo** [digitalocean/doctl#30]
My droplets use a non-standard port for ssh. So I tried this:
`doctl compute ssh <my_droplet> --ssh-user <my_user> --ssh-port 1234`

But I get `ssh: connect to host <droplet_ip> port 22: Connection refused`
`Error: 255`

Software | Version
--- | ---
`doctl` | v1.0.0
OS | OSX El Capitan 10.11.4 (15E65)
Shell | iTerm 2 (2.1.4)

Btw, thank you all for this awesome tool!!

**Comment by bryanl** [comment]
I've verified this happens, but I don't have an immediate answer. I'll be digging in and will report back.
