### ISSUE TITLE
Wildcard for "--record-id" in doctl 

### ISSUE THREAD

**Issue by iprofor** [digitalocean/doctl#300]
Hello to everyone, 

I stumble upon a problem that unfortunately I did not find the solution.
The thing is that I have to update the TTL of all the records of a domain to let's say "3600"

I tried this approach 
doctl compute domain records update example.com __--record-id=*__ --record-ttl=3600

but instead I have got this error

`Error: id is invalid because cannot be less than 1`

Is this a bug or it is supposed to act like this. If so, is there a workaround?

**Comment by mauricio** [comment]
Hey @iprofor, `--record-id` can't be `*`, that has to be the ID of the domain record at the DO API, so you need to perform this operation for every domain there using their own ID. So you fist need to listen the domains and then update each one of them.

**Comment by iprofor** [comment]
Actually, I wrote that I would like to update all the records for just one domain

**Comment by mauricio** [comment]
Yeah, the API doesn't allow you to do that, you need to perform the operation for every record.

**Comment by iprofor** [comment]
too bad. thank you for the clarification. 
is it possible to implement such a feature in the near future?
