### ISSUE TITLE
Newer and last release version on snapcraft

### ISSUE THREAD

**Issue by PrestanceDesign** [digitalocean/doctl#306]
Hi,

Since the last 1.8.0 release 8 days ago, the snap version is always the 1.7.0 version on snap store https://snapcraft.io/doctl. When will be available the last version ?

Best regards.
Mike

**Comment by kamaln7** [comment]
Sorry for the delay here—we're working on this and it should be done in a couple of days!

**Comment by PrestanceDesign** [comment]
Perfect thx!

**Comment by grndlvl** [comment]
Any word on this?

**Comment by idvoretskyi** [comment]
@kamaln7 

Any updates? The snap version is still 1.7.0.

```
# snap info doctl
name:      doctl
summary:   Digital Ocean command line tool
publisher: digitalocean
contact:   https://github.com/digitalocean/doctl/issues
license:   Apache-2.0
description: |
  DigitalOcean's web based control panel provides a
  convenient, point-and-click interface for managing
  Droplets. There are, however, times when a command-line
  tool may be a preferable alternative; If you have many
  Droplets to manage, need to administer Droplets from the
  terminal without a graphical desktop available, or have
  tasks which would benefit from a scriptable interface.
snap-id: 37RaX7lHS7bKamfcFcXcx27EyAaCIzgG
channels:                   
  stable:    1.7.0 (13) 3MB -
  candidate: 1.6.0 (2)  3MB -
  beta:      1.6.0 (2)  3MB -
  edge:      1.7.0 (13) 3MB -
```

**Comment by kamaln7** [comment]
Very sorry for the delay here! The latest version has been released on Snapcraft (stable branch).

cc @PrestanceDesign @grndlvl @idvoretskyi + @mauricio @adamwg

**Comment by dave08** [comment]
@kamaln7 The current snap version is 1.9.0 on stable, whereas it looks like 1.12.1 was released... could the snap be updated please?

**Comment by kamaln7** [comment]
@dave08 thanks, I've let the team know

**Comment by dave08** [comment]
@kamaln7 Thanks for passing this along, but there's still no update...?

**Comment by dave08** [comment]
Is this really so complicated, I need the new client for k8s support... @kamaln,it's useless to have this out on snap if it won't get updated...
