### ISSUE TITLE
Fail authenticate

### ISSUE THREAD

**Issue by valours** [digitalocean/doctl#308]
I can't connect my terminal to digital ocean for use doctl. Can you help me ?
![image](https://user-images.githubusercontent.com/5904891/39023188-78d26fc4-4439-11e8-9ae9-ee3b5951e81a.png)

**Comment by andrewsomething** [comment]
Hi @valours that screen shot doesn't show anything unexpected. Are you seeing any error messages? Does the command `doctl account get` work for you? Is your personal access token in the file `~/.config/doctl/config.yaml` ?

**Comment by xmudrii** [comment]
Hello @valours,

I have an additional question just out of curiosity. What's your `doctl` version? You can check it by running `doctl version`.

@andrewsomething can correct me, but I don't remember such output, it should look like this for past few versions (also there's a typo in the `DOCLT_TOKEN` variable name):
```
Using token [your-token]
Validating token... OK
```

Maybe you can try updating to the latest version, by downloading `doctl` from the [GitHub Releases page](https://github.com/digitalocean/doctl/releases).

**Comment by andrewsomething** [comment]
Oh! I obviously didn't look at that closely enough, but @xmudrii pointing out the spelling difference made me realize the issue. It looks like you are actually using a different CLI with the confusingly similar name: `doclt` It's a Node application: https://github.com/omgimanerd/doclt

**Comment by kamaln7** [comment]
I'm closing this issue, but please let me know if you're still having issues authenticating with doctl. For reference, here are the installation instructions: https://github.com/digitalocean/doctl#installing-doctl
