### ISSUE TITLE
Snapshot ID

### ISSUE THREAD

**Issue by JeffFerg** [digitalocean/doctl#312]
When generating a snapshot, an ID is returned but it's not useful for future reference:
```
doctl compute droplet-action snapshot ######## --snapshot-name "Doctl-Test1"
ID           Status       Type        Started At                       Completed At                     Resource ID    Resource Type    Region
426######    completed    snapshot    2018-05-01 20:35:47 +0000 UTC    2018-05-01 20:36:29 +0000 UTC    ########       droplet          nyc3
```

```
doctl compute image delete 426###### -f
Error: DELETE https://api.digitalocean.com/v2/images/426######: 404 The resource you were accessing could not be found.
```
Of course, I can list the snapshots and delete the actual snapshot that was just created which has a number 339#####

Is there a way to get the ID of the snapshot upon creation (it's not available with --wait which doesn't make much sense)? Seems like I'm missing something.

**Comment by kamaln7** [comment]
The returned ID (426###) is the action ID (see https://developers.digitalocean.com/documentation/v2/#snapshot-a-droplet and https://developers.digitalocean.com/documentation/v2/#actions). Action commands are supported by doctl so you can monitor the snapshot's progress using the returned action ID.

It doesn't look like it's possible to get a snapshot's ID before it is created though, per https://github.com/digitalocean/api-v2/issues/98

**Comment by kamaln7** [comment]
Closing this issue. Will reconsider once there's upstream support for this feature.
