### ISSUE TITLE
error formating "doctl compute volume list" output

### ISSUE THREAD

**Issue by estevesd** [digitalocean/doctl#320]
```
$ doctl version
doctl version 1.8.0-release
```

Usage says : --format string   Columns for output in a comma separated list. Possible values: ID,Name,Size,Region,Droplet IDs

however :
```
$ doctl compute volume list --format "ID,Droplet IDs"
list volume
Usage :
.
Error: unknown column "DropletIDs"
```

```
$ doctl compute volume list --format "ID,Droplet\ IDs"
list volume
Usage :
.
Error: unknown column "Droplet\\IDs"
```
and obviously :
```
$ doctl compute volume list --format ID,Droplet IDs
list volume
Usage :
.
Error: unknown column "Droplet"
```
but interestingly, if --no-header is added, there's no error but a wrong output :
```
$ doctl compute volume list --no-header --format "ID,Droplet IDs"
12345678-1234-1234-1234-123456789012    <nil>
```
```
$ doctl compute volume list --no-header --format ID,Droplet IDs
$
```

**Comment by xmudrii** [comment]
Hi there,

Thanks for reporting the issue!

The `format` flags takes column name without spaces, so you usually have to pass something like `--format "ID,DropletIDs"`.

To check out accepted column names, you can execute the appropriate command with the `--help` flag, and it will show you what column names you can provide:

```
doctl compute volume list --help
```
```
list volume

Usage:
  doctl compute volume list [flags]

Aliases:
  list, ls


Flags:
      --format string   Columns for output in a comma separated list. Possible values: ID,Name,Size,Region,DropletIDs
      --no-header       hide headers
      --region string   Volume region
...
```

However, in case for the `volume list` command, there's a bug, because column names should not contain spaces, or otherwise you'll run into the described issue. I have submitted a pull request to fix this (#322).

**Comment by estevesd** [comment]
Hi,

Thanks for pushing this issue up the chain. 

On top of the bug, there's a need for consistency here. The --help is not the same for me
```
$ doctl compute volume list --help
list volume

Usage:
  doctl compute volume list [flags]

Aliases:
  list, ls


Flags:
      --format string   Columns for output in a comma separated list. Possible values: ID,Name,Size,Region,Droplet IDs
      --no-header       hide headers
      --region string   Volume region
...
```
notice the space in "Droplet IDs"

**Comment by xmudrii** [comment]
Oh, I have copied the help page from `doctl` with fix in the place. :wink: Without fix, it's same as yours.

That's strange for Floating IPs. I think for consistency, it should be better to use non-spaced versions everywhere. Not sure what doctl team think about that (/cc @mauricio). I can create a follow-up PR (or update the current one) later, if needed.
