### ISSUE TITLE
error attaching volume to droplet

### ISSUE THREAD

**Issue by estevesd** [digitalocean/doctl#321]
```
$ doctl version
doctl version 1.8.0-release
```

It seems I can't assign an existing volume to a new droplet while creating it
Usage says :       --volumes value               Volumes to attach (default [])

```
$ doctl compute volume list
ID                                      Name                        Size       Region    Droplet IDs
12345678-1234-1234-1234-123456789012    volume1            2 GiB      fra1
$ doctl compute droplet create droplet1 --volumes "['12345678-1234-1234-1234-123456789012']" \
    --image "ubuntu-16-04-x64" \
    --size "s-1vcpu-1gb" \
    --region fra1
create droplet
Usage:
.
Error: POST https://api.digitalocean.com/v2/droplets: 422 Invalid volume allocations
```

since there's only one volume, I tried without brackets, with different combinations of single and double quotes, and the volume's name instead of the ID, to no avail. always the same error.

Only when putting "[\"12345678-1234-1234-1234-123456789012\"]", it says something different
```
invalid argument "[\"12345678-1234-1234-1234-123456789012\"]" for --volumes: parse error on line 1, column 1: bare " in non-quoted-field
```

Am I missing something?

Also when trying to attach a volume to an existing droplet, it looks like it can't find the volume
```
$ doctl compute volume get 12345678-1234-1234-1234-123456789012
ID                                      Name                Size     Region    Droplet IDs
12345678-1234-1234-1234-123456789012    staging-api-apps    2 GiB    fra1
$ doctl compute volume-action attach 12345678-1234-1234-1234-123456789012 12345678
attach a volume
Usage:
.
Error: POST https://api.digitalocean.com/v2/volumes/12345678-1234-1234-1234-123456789012/actions: 404 The resource you were accessing could not be found.
```

**Comment by xmudrii** [comment]
Brackets are not needed. Probably the description is not as clear as it should be. You need to pass list of volume IDs, separated by commas.

If you want to create Droplet with two volumes attached, the following command could be used:
```
doctl compute droplet create testing-1 \
--region nyc1 \
--size s-1vcpu-1gb \
--image ubuntu-16-04-x64 \
--volumes "12341541-51351351-315413,315315-591513-3131"
```
For one volume, similar, just provide the ID.

I was not able to reproduce the error 404 when attaching a volume, but if it repeats, I would recommend creating a support ticket, so they can check what's the problem.

**Comment by estevesd** [comment]
thanks, I just found this on my own, and was coming back here to update

+1 for the description

for example, format is clear 
```
--format string   Columns for output in a comma separated list.
```

**Comment by eddiezane** [comment]
Thanks for the assist, @xmudrii!
