### ISSUE TITLE
Multiple Missing Things for 'change-kernel' Action

### ISSUE THREAD

**Issue by ZacharyDuBois** [digitalocean/doctl#33]
The `--format` option is missing for the `change-kernel` action using the following command:

```
doctl compute droplet-action change-kernel <droplet-id>
```

This option exists for other similar `droplet-action` such as `power-off`.

I was updating my mass kernel updater script to use `doctl` instead of `curl` and came across this issue.

EDIT:
It also appears the `--no-header` option is missing too.

EDIT 2:
It appears that it does not list all kernels too. My assumption would be the paging in the DigitalOcean API.

**Comment by cybernet** [comment]
+1

**Comment by bryanl** [comment]
Hi, the change-kernel missing options was an oversight, and I've fixed it locally, and will send a PR for it today. The pagination issue is larger, and should have a fix in the next couple of days.

**Comment by ZacharyDuBois** [comment]
👍

**Comment by ZacharyDuBois** [comment]
@bryanl Any updates on pagination? :)

**Comment by bryanl** [comment]
@ZacharyDuBois With the current 1.1.0 release, pagination should work properly.
