### ISSUE TITLE
Configuration file placement warning is issued when 'cwd' is ~/.config/doctl

### ISSUE THREAD

**Issue by 00pauln00** [digitalocean/doctl#334]
I came across a very minor issue where doctl will issue a warning if run from the config file directory.

$ cd .config/doctl
$ doctl compute droplet list
Warning: Configuration detected at "config.yaml". Please move config.yaml to /home/pauln/.config/doctl/config.yaml

ID    Name    Public IPv4    Private IPv4    Public IPv6    Memory    VCPUs    Disk    Region    Image    Status    Tags    Features    Volumes

**Comment by kamaln7** [comment]
Hi @00pauln00, thanks for reporting this! I've pushed #339 as a fix so it will be taken care of in the next release.
