### ISSUE TITLE
How to properly move config.yaml to another computer?

### ISSUE THREAD

**Issue by hillz2** [digitalocean/doctl#336]
The `config.yaml` on my computer has multiple DigitalOcean accounts set up in it and I want to move the config file to another computer so that I won't have to configure `doctl` from scratch again. After I copied `config.yaml` from my computer to another computer and executed this command I got this error:
```
me@anotherPC:~/FFS# doctl account get --context myDOaccount@yahoo.com
get account

Usage:
  doctl account get [flags]

Aliases:
  get, g


Flags:
      --format string   Columns for output in a comma separated list. Possible values: Email,DropletLimit,EmailVerified,UUID,Status
      --no-header       hide headers

Global Flags:
  -t, --access-token string   API V2 Access Token
  -u, --api-url string        Override default API V2 endpoint
  -c, --config string         config file (default is $HOME/.config/doctl/config.yaml)
      --context string        authentication context name
  -o, --output string         output format [text|json] (default "text")
      --trace                 trace api access
  -v, --verbose               verbose output

Error: unable to initialize DigitalOcean api client: access token is required. (hint: run 'doctl auth init')
```
The token is working well on my old computer but somehow it keeps producing the same error on my new computer. How do I properly move `config.yaml` from a computer to another computer so that I won't have to configure doctl from scratch ?

**Comment by hilary** [comment]
Just to be clear, that command runs cleanly on your old computer? Also, what version of `doctl` are you running?

**Comment by hilary** [comment]
This issue has been waiting for a response for months, now. We can always re-open if we get more info.
