### ISSUE TITLE
Update snap & metadata

### ISSUE THREAD

**Issue by popey** [digitalocean/doctl#337]
Hi. It seems the snap of doctl is a little outdated. Can it be updated to 1.8.3?

```
channels:                   
  stable:    1.8.2 (15) 3MB -
  candidate: 1.6.0 (2)  3MB -
  beta:      1.6.0 (2)  3MB -
  edge:      1.7.0 (13) 3MB -
alan@hal:~$ 
```

I'd recommend closing the non-stable channels while you're at it if you're not using them. `snapcraft close doctl candidate beta edge`

While we're at it, the metadata for doctl says the owner of the snap is "Engineering".

![image](https://user-images.githubusercontent.com/1841272/43640398-b867b08c-9717-11e8-9d8f-d0130217f960.png)

I'd recommend changing that to "DigitalOcean" :) Unfortunately we have a store bug which means the process is a little convoluted:-

1. Go to https://login.ubuntu.com/
2. Change "Your Name" field
3. Save
4. Go to https://dashboard.snapcraft.io/
5. Logout
6. Login
7. Go to https://dashboard.snapcraft.io/dev/account/
8. Check Full Name is changed

Once done I think we should add a "Verified" publisher tag (which I will do) so users can be confident the snap comes from the upstream developers.

**Comment by andrewsomething** [comment]
Hi @popey! Thanks for the tip. A new version is up, the name has been corrected, and the old channels have been closed out. Let me know if there's anything else we need to do on our end to get the "Verified" publisher tag.

**Comment by popey** [comment]
@andrewsomething Awesome, thanks for sorting that. You now have a verified badge :)

**Comment by idvoretskyi** [comment]
@andrewsomething 

FYI, snap installs the -dev version of the tool:

```
$ doctl version
doctl version 1.8.3-dev
release 1.8.3 is available, check it out! 
```
