### ISSUE TITLE
Command doctl compute ssh-key import does not work in Alpine

### ISSUE THREAD

**Issue by lavir** [digitalocean/doctl#341]
I used the Dockerfile (image Alpine:3.5 ) from this repo.

Then I tried to import a public key to DO and got an error:
`doctl compute ssh-key import ci_key --public-key-file ~/.ssh/id_rsa.pub`
`Error: open : no such file or directory`

The file `id_rsa.pub` exists.

Seems that the issue is how the doctl been compiled, binary with some dynamic linking.
Any idea how to fix this issue. Maybe I need to instal a missed lib?

**Comment by zachgersh** [comment]
hey @lavir - really apologize for the delay on getting back to this, hopefully our response times are going to be better going forward.

Were you still having this problem?

One other question, were you doing a `docker run` without changing the entry point or did you actually have an interactive session inside the container? I can kind of guess based on your comment but wanted to clarify.

I tried to reproduce this problem and didn't have any luck.

Cheers!

**Comment by lavir** [comment]
> hey @lavir - really apologize for the delay on getting back to this, hopefully our response times are going to be better going forward.
@zachgersh later better than never

> Were you still having this problem?
From that time many things changed, so for me personally this issue is not valid anymore. 
If it works for you then you can close the issue.

Thank you
