### ISSUE TITLE
Missing binaries for v1.9.0

### ISSUE THREAD

**Issue by dbirks** [digitalocean/doctl#344]
Hello, I maintain the Arch Linux package for doctl. I've noticed that there are binaries missing in the Release section for v1.9.0. Could those be added for ease of use? Thank you!

**Comment by sunny-b** [comment]
Oops, that was my fault. I'll add those in

**Comment by sunny-b** [comment]
Okay added them. Let me know if you need anything else. Thanks for catching that @dbirks !

**Comment by dbirks** [comment]
Perfect, thanks for grabbing that so quickly!
