### ISSUE TITLE
--user-data-file Error

### ISSUE THREAD

**Issue by amesmod1** [digitalocean/doctl#347]
Hello,
I tried using the doctl API for Digitalocean but when i create a Droplet with the --user-data-file flag i get the following error : "Error: open script.sh: permission denied" !
Can anyone Help me with this problem please ? 
Thank you .

**Comment by andrewsomething** [comment]
Hi @amesmod1 Are you using the `doctl` snap? Just did some testing on a few different platforms, and it seem like this is a packaging issue related to the snap. Snap packages have strict confinement, and it  seems like we may need to request additional permissions in order access files.

As a work around, can you try following the "Downloading a Release from GitHub" installation method in the README? https://github.com/digitalocean/doctl#option-2--downloading-a-release-from-github

**Comment by XaeroDegreaz** [comment]
I'd just like to chime in and say that I'm also having the same issue when attempting to load a user-data file. I'll try building from the link you posted, though.

**Comment by itbm** [comment]
Run `sudo snap install doctl --classic` see #357
