### ISSUE TITLE
Delete a volume.

### ISSUE THREAD

**Issue by winadv** [digitalocean/doctl#358]
Hello, I'm having a problem with the platform. I am trying to delete a volume only ever error. I wonder what I should do.
I tried deleting the volumes using doctl and nothing just appears the following error:
doctl compute volume delete 9f432a6a-b57c-4bb4-bf92-6d7a539bdd39 

Error: DELETE https://api.digitalocean.com/v2/volumes/5e83331c-da58-11e8-972b-0a58ac14442f: 409 (request "9f432a6a-b57c-4bb4-bf92-6d7a539bdd39") attached volume cannot be deleted

Thanks

**Comment by sunny-b** [comment]
@winadv It looks as if your volume is still attached to a Droplet. That's why it can't be deleted -- it has to be detached first.

Unfortunately, doctl doesn't support `detach` and `attach` at this time. That has to be done either through the UI or API first.

**Comment by sunny-b** [comment]
I was mistaken, you are able to `attach` or `detach` a Volume using `doctl`. `doctl compute volume-action detach <volume-id> <droplet-id>`

**Comment by winadv** [comment]
Yes, that's exactly what I did, but the error quoted above appeared.

doctl compute volume-action detach <volume-id> <droplet-id>
doctl compute volume delete <volume-id>

Error: DELETE https://api.digitalocean.com/v2/volumes/5e83331c-da58-11e8-972b-0a58ac14442f: 409 (request "9f432a6a-b57c-4bb4-bf92-6d7a539bdd39") attached volume can not be deleted

**Comment by sunny-b** [comment]
Are you still getting that error? It looks like volume `5e83331c-da58-11e8-972b-0a58ac14442f: 409` is no longer attached to a droplet and should be able to be deleted without any issue.

**Comment by winadv** [comment]
Yes, the error is still appearing.
Currently I did not re-test with the command I quoted above because I made a request for support from Digital Ocean who verified that this is a mistake that they are still investigating. That's why I'm waiting.

**Comment by eddiezane** [comment]
@winadv hopefully support sorted this out. Going to close here but please reopen if not resolved.
