### ISSUE TITLE
Custom image support

### ISSUE THREAD

**Issue by benpye** [digitalocean/doctl#367]
It would be great to have support for managing custom images from doctl. It looks like your API supports at the very least uploading from a URI but doctl doesn't yet support that. It would be nice to be able to use doctl to integrate custom image building into a CI/CD pipeline, adding the image and then potentially spinning up droplets.

**Comment by alcir** [comment]
I agree. It would be very useful.

**Comment by VictorAvelar** [comment]
I can take care of this one if it's still relevant 😄

**Comment by andrewsomething** [comment]
That would be amazing @VictorAvelar! Here are a few things to point you in the right direction. If you run into any issues or have any questions, please don't hesitate to ask.

This should be implemented as an image sub-command, e.g. `doctl compute image import` So these files will be of interest:

https://github.com/digitalocean/doctl/blob/master/commands/images.go
https://github.com/digitalocean/doctl/blob/master/do/images.go

The relevant API docs: https://developers.digitalocean.com/documentation/v2/#create-a-custom-image
The godo method: https://godoc.org/github.com/digitalocean/godo#ImagesServiceOp.Create

**Comment by VictorAvelar** [comment]
thanks for the comment, I am almost done with the implementation, thanks for the resources I've already figure it our from the code. 👍 p.s.  Props to @Verolop from a fellow Mexican

**Comment by VictorAvelar** [comment]
Hey guys, shouldn't this one be closed? 😄

**Comment by andrewsomething** [comment]
Indeed! Thanks again @VictorAvelar!
