### ISSUE TITLE
Make doctl available on MacPorts

### ISSUE THREAD

**Issue by messa** [digitalocean/doctl#368]
MacPorts is a package manager on macOS - alternative to brew.

**Comment by KritR** [comment]
Just got this taken care of
https://github.com/macports/macports-ports/pull/4471

**Comment by hilary** [comment]
Wonderful! Thanks for the contribution.

Please let us know what we can do to help with updating the port for new versions.

**Comment by KritR** [comment]
The port should be marked as openmaintainer, which means small changes like version updates should go through from anyone. I'll get called in for larger updates. In addition I'll try and do my best to keep things relatively up to date.

**Comment by hilary** [comment]
Super! One of the things I'd like to see us do is automate updating the various packages, so a human only has to intervene when an automated update fails.
