### ISSUE TITLE
Zsh completion errors

### ISSUE THREAD

**Issue by maximilianriemensberger** [digitalocean/doctl#386]
I get the following error when typeing `doctl complete` and then hit `TAB`:
```
_doctl_compute:14: bad math expression: operand expected at `"d"'
```
Completion activated with
```
source <(doctl completion zsh)
```
doctl version (local install, downloaded from github)
```
doctl version 1.12.2-release
Git commit hash: 74b1791e
```
zsh version
```
zsh 5.4.2 (x86_64-ubuntu-linux-gnu)
```

**Comment by eddiezane** [comment]
Looks like it broke between 1.12.0 and 1.12.1.

Here's a gist of the diff: https://gist.github.com/eddiezane/eef3923c10d0bd2eb77ee0d4c0952702

**Comment by eddiezane** [comment]
Seems similar to this https://github.com/helm/helm/issues/5046

**Comment by eddiezane** [comment]
The [proposed fix](https://github.com/helm/helm/pull/5072) doesn't work for me.

Error is now:

```
~ doctl compute _doctl_compute:14: bad math expression: operand expected at `/usr/share...'
```

**Comment by hilary** [comment]
I'm knee deep in getting the snap working again in https://github.com/digitalocean/doctl/tree/hholz/fix-snap-build. The snapcraft.yml in that branch will snap install 1.12.2 under strict confinement, however, I haven't folded the docker ssh logic into it yet.

**Comment by eddiezane** [comment]
@maximilianriemensberger I just opened PR #403 with a patch that models our completion after kubectl's. Would you please test if you get a chance?

**Comment by maximilianriemensberger** [comment]
@eddiezane Works for me. Thanks.
