### ISSUE TITLE
updating the snap

### ISSUE THREAD

**Issue by alexivkin** [digitalocean/doctl#390]
snap find doctl

Name   Version  Publisher      Notes  Summary
doctl  1.9.0    digitalocean✓  -      DigitalOcean command line tool

Could this be brought up to the latest?

**Comment by eddiezane** [comment]
I believe @hilary is working on this in https://github.com/digitalocean/doctl/tree/hholz/fix-snap-build

**Comment by hholst80** [comment]
Also update the README.md. The `--classic` switch is not supported for installation anymore it seems?

**Comment by irontoby** [comment]
Why is `snap` the "preferred" method when it's six releases behind? Please at least update your README to clarify that it is not regularly updated. I'm trying to interact with my Kubernetes cluster and just found out I'm using a `doctl` from last August.

**Comment by alexivkin** [comment]
@hilary @eddizane Let us know if snap can't be supported long term, so we plan for other methods of installing goctl.

**Comment by hholst80** [comment]
My $0.02 

A simple fix would to make the snap build part of the deploy pipeline. These things are trivial on a platform that supports pipelines like Atlassian Bitbucket.

**Comment by maristgeek** [comment]
In the mean time, if any Linux users use [asdf](https://github.com/asdf-vm/asdf), I contributed a `doctl` plugin.

**Comment by tiagomsmagalhaes** [comment]
Any update on this? Last commit on that branch was 3 months ago

**Comment by hilary** [comment]
Sorry, we're just now growing the API/CLI team so that we'll have more resources to handle these issues in a timely manner.

Once we have the snap updated to a modern (i.e., non-classic) snap, we plan on automating the snap build.

**Comment by hilary** [comment]
A beta channel snap is now available for `doctl` 1.18.0 (stable coming soon!)

`snap install --beta doctl`

A couple of quick notes:

* bash/zsh completion is missing from the snap: I wasn't willing to hold the snap in order to get them working
* `doctl compute ssh` doesn't work. That's coming soon
* You will need to rerun `doctl auth init` after installing the snap

Please let us know about any issues you encounter with the beta, and thanks for your patience!

**Comment by irontoby** [comment]
@hilary thanks for the update! Looking forward to testing it...

**Comment by hilary** [comment]
Just pushed a new version of the beta that fixes `doctl compute ssh` 🎉 

Before you use `doctl compute ssh`, you'll need to connect the doctl snap to the core `ssh-keys` snap:

`sudo snap connect doctl:ssh-keys :ssh-keys`

**Comment by hilary** [comment]
I think we can close this now. The snap may occasionally fall behind while an interface is in review, but we're actively maintaining it.
