### ISSUE TITLE
Setting Kubernetes context on first config save

### ISSUE THREAD

**Issue by karakanb** [digitalocean/doctl#394]
When the config saved with the `doctl kubernetes cluster kubeconfig save <cluster-id|cluster-name>` command, the saved configuration has the `current-context` as empty, while the `show` command uses the cluster context in the output message. Apart from inconsistency between these two commands, I believe this is a decision taken to prevent setting cluster context automatically to the retrieved cluster context, though it may be good if it was possible to override.

In my usecase, I am using doctl on CI, in which the retrieved config file is the only one and the environment doesn't have `kubectl` available, which means I need to set `--kube-context` for every `helm` call for example, making the deploy scripts more verbose than they can be. Since the functionality is already there, I believe it would be good if `current-context` on the saved configuration is also configurable via a flag, to whether to set it to the retrieved config or not.

**Comment by TonyApuzzo** [comment]
You can use:
`kubectl config get-contexts` to list the available contexts, which will include the set that you added via `doctl` and whatever others you might have.  Then you can use `kubectl config use-context <cluster-id|cluster-name>` to make whichever cluster you want be the default.

I agree though that it would be nice if `doctl` set the context when it was creating ~/kube/.config or updating it when only 1 cluster was listed.
