### ISSUE TITLE
The renew command in warning is missing cluster

### ISSUE THREAD

**Issue by mostaphaRoudsari** [digitalocean/doctl#395]
When I run `doctl k8s cluster create` command the command I see the following warning which is useful but the command seems to be wrong.

```
Warning: cluster credentials will expire on <DATETIME>, renew with: "doctl k8s kubeconfig save <NAME>"
```

It should be `"doctl k8s **cluster** kubeconfig save <NAME>"`

**Comment by eddiezane** [comment]
Thanks for raising the issue!

We just shipped a new version (v1.13.0) that changes auth a bit and removed this warning.

https://github.com/digitalocean/doctl/pull/387
