### ISSUE TITLE
fetching of Kubernetes credentials / configuration fails occasionally with a "500 Server Error"

### ISSUE THREAD

**Issue by timoreimann** [digitalocean/doctl#399]
When you create a Kubernetes cluster, doctl fetches the configuration and integrates it into the user kubeconfig file. I noticed that this operation is failing occasionally with a HTTP 500 error. Example:

```
$ doctl kubernetes cluster create test-cluster --count 1 --region fra1 --version 1.13.1-do.2
Notice: cluster created, fetching credentials

Warning: couldn't get credentials for cluster, it will not be added to your kubeconfig: GET https://api.digitalocean.com/v2/kubernetes/clusters/059873d7-a92c-447b-99f7-xxxxxxxxxxxx/kubeconfig: 500 Server Error
```

If I were to put this into numbers, I'd say that the failure happens to me at 10 to 15 percent of my cluster creation invocations.

FWIW, I tend to use the FRA1 region.

**Comment by eddiezane** [comment]
Thanks for the report.

There's a PR open to get this status code changed internally.

**Comment by bouk** [comment]
We've now changed this to a 404, but still need to fix it in the doctl client so it doesn't fail
