### ISSUE TITLE
Automatic self-upgrades 

### ISSUE THREAD

**Issue by mwardRH** [digitalocean/doctl#400]
Since this isn't packaged per distribution and primarily distributed via github releases, it would be great for it to be aware of the current released version. Adding an argument such as `doctl update` to find out if you are current would be super useful as you being to implement more to the cli. 

Once aware of the current version it would be a bonus for it to automatically update itself too.

**Comment by eddiezane** [comment]
I believe the functionality to let you know a newer version is available is baked into the `doctl version` command. https://github.com/digitalocean/doctl/blob/59e6c369e84356edad8d80d59dcfc638bb5271a3/doit.go#L114

Self update would definitely hit the wish list!

**Comment by andrewsomething** [comment]
`doctl version` does check for newer releases:

```
$ doctl version
doctl version 1.13.0-release
Git commit hash: 8f157b21
release 1.14.0 is available, check it out!
```

I'm going to go ahead and retitle this one to reflect the self update request.

**Comment by hilary** [comment]
I understand the desire for a

`doctl selfupdate`

and agree that it would be useful, but it isn't a trivial task, as `doctl` is distributed so many different ways. While `doctl` is not packaged per distribution in the traditional sense, it's available (and installed) via a wide variety of package managers. We're also planning to make a public docker image available on dockerhub.

**Comment by hilary** [comment]
If you want `doctl` to stay up to date on your systems, use the snap. Snaps self-update nightly.
