### ISSUE TITLE
Database support ?

### ISSUE THREAD

**Issue by akoutmos** [digitalocean/doctl#407]
I was wondering if/when doctl would support interfacing with your managed database offering. Thanks in advance for any information :)

**Comment by eddiezane** [comment]
@akoutmos we're hoping for this to land in Q2!

As soon as the team builds support out in https://github.com/digitalocean/godo/issues/204 we'll be able to integrate it here.

**Comment by akoutmos** [comment]
Friendly bump :). Any updates on this one now that digitalocean/godo#204 has been closed out?

**Comment by andrewsomething** [comment]
I'm happy to say that support for managed databases was releases with doctl version 1.15.0: 
https://github.com/digitalocean/doctl/releases/tag/v1.15.0

Looks like we forgot to update this issue. Thanks for the reminder @akoutmos.
