### ISSUE TITLE
Handling multiple doctl config

### ISSUE THREAD

**Issue by murarisumit** [digitalocean/doctl#409]
I access multiple digitalocean account, what is right way to handle it up ?

Currently I copy the original config, change access token and use softlink for point to correct config.
Is there something like profile to access multiple account ?

**Comment by andrewsomething** [comment]
`doctl` supports multiple accounts. The first account configured is known as the `default` To add a new account, you can run:

     doctl auth init --context <account-name>

To switch to that account, run:

    doctl auth switch --context <account-name>

Now all commands will be run using the second account. To swtich back to the default account, run:

    doctl auth switch --context default

You can run commands from either account without switching` by using the `--context` flag:

    doctl compute droplet ls --context <account-name>

See the README for more info: https://github.com/digitalocean/doctl#logging-in-to-multiple-digitalocean-accounts

**Comment by murarisumit** [comment]
Thanks for answer, don't know how i missed it.
