### ISSUE TITLE
Is it possible to resize Kubernetes cluster

### ISSUE THREAD

**Issue by thecb4** [digitalocean/doctl#417]
Unclear if I can use the command:

```sh
doctl kubernetes cluster update 
```

to resize the cluster

**Comment by andrewsomething** [comment]
Looks like this is somewhere we need to improved the help output. That is pretty vague!

`doctl kubernetes cluster update` maps to this API call: https://developers.digitalocean.com/documentation/v2/#update-a-kubernetes-cluster

You can use it to rename the cluster or modify the cluster level tags. To adjust the number of nodes in the cluster, you'll want to use the `node-pool` subcommand. For example, first you can find the name and ID of the node pool with:

    doctl kubernetes cluster node-pool list <cluster-id|cluster-name>

Next you can increase or decrease the number of nodes in the pool using:

    doctl kubernetes cluster node-pool \
        update <cluster-id|cluster-name> <pool-id|pool-name> \
        --count 5 --name <updated pool-name> --tag <updated tag>
        
This maps to this underlying API call: https://developers.digitalocean.com/documentation/v2/#update-a-node-pool-in-a-kubernetes-cluster

**Comment by thecb4** [comment]
Is there an opportunity to change the RAM/CPU of each cluster node or do I have to walk through each node and shut down things manually?

Cheers,
CB

**Comment by andrewsomething** [comment]
Generally, the best way to deal with this would be to add a new node pool with the desired amount of RAM/CPU, and then delete the existing node pool. Kubernetes will reschedule any existing services on those nodes to the new ones. The old node will not be deleted until they have been drained of any active work.

**Comment by thecb4** [comment]
Use the following command?
doctl kubernetes cluster node-pool create
Thanks!

**Comment by andrewsomething** [comment]
Somehow I missed your last comment. Sorry about that! Yes, the command `doctl kubernetes cluster node-pool create` can be used to create a new node pool with the desired resources.

If you're still running into issue, feel free to reopen this. Thanks!
