### ISSUE TITLE
Create a Volume from a Snapshot

### ISSUE THREAD

**Issue by Zatvobor** [digitalocean/doctl#420]
I have been working on backup solution which is based on volume snapshots... So, 
is it possible to create a volume from already created volume snapshot using `doctl`?

**Comment by andrewsomething** [comment]
The DigitalOcean API does support this, but it has not yet been implemented in `doctl`

https://developers.digitalocean.com/documentation/v2/#create-a-new-block-storage-volume

**Comment by Zatvobor** [comment]
That's right. Would be great to get this in the next release. 
Thanks.
