### ISSUE TITLE
--ssh-private-ip does not work

### ISSUE THREAD

**Issue by luddite478** [digitalocean/doctl#425]
When i use:
`doctl compute ssh <droplet-id> --ssh-private-ip <droplet-private-ip>`
on droplet with private ip enabled, command line just freezes and nothing happens 
What am i doing wrong?

**Comment by andrewsomething** [comment]
If you pass the `--ssh-private-ip` flag, you should not also need to pass `<droplet-private-ip>` The main purpose for the `ssh` subcommand is to SSH into a Droplet without first needing to look up its IP address.

I have a couple follow up questions to help us understand this better:

- Do both Droplets have private networking enabled?
- Are both Droplets in the same region? Private networking does not work cross region.
- Does the Droplet that the command was run from have an SSH key pair?
- Is the public side of the SSH key pair in the `~/.ssh/authorized_keys` file of the target Droplet?
- Which operating system is the Droplet that the command was run from using?

**Comment by luddite478** [comment]
Oh wow, does this command work only when i use it from droplet? The problem was that I tried to use it from my local computer. I thought it finds correct ip's with the help of auth token somehow. I just logged into my droplet and tried it again and everything worked correctly. 
So If command works this way, there is no need to answer your questions, i believe.

**Comment by andrewsomething** [comment]
Right. Private networking is designed to allow you to create services that are isolated from the public internet. For instance, you might want your database to only be accessible from other Droplets in your private network. One common pattern for accessing these types of services is to create a "bastion server" or "jump box" that is used to control access.

I'm going to go ahead and close this out. Feel free to reopen if you have other questions. Thanks for following up!
