### ISSUE TITLE
Wait for for having an attributed IP to a droplet on creation

### ISSUE THREAD

**Issue by tiagomsmagalhaes** [digitalocean/doctl#432]
It would be nice if `doctl compute create droplet` would wait for the new droplet to be active to return the table with the attributed IP addresses

**Comment by andrewsomething** [comment]
By default `doctl` does not block until the Droplet is ready, but you can pass the `--wait` flag. For example:

```
doctl compute droplet create \
  --image ubuntu-18-04-x64 \
  --region nyc3 \
  --size s-1vcpu-1gb \
  --wait \
   example.com
```

This will wait until the Droplet has been created and return the IP address.

**Comment by tiagomsmagalhaes** [comment]
Sorry. I have noticed the flag previously but must have skipped/misunderstood the flag description. Thanks
