### ISSUE TITLE
ARM version

### ISSUE THREAD

**Issue by mtifs** [digitalocean/doctl#441]
I'd love to use doctl from my RaspberryPi. Will you make an ARM version?

**Comment by hilary** [comment]
What a cool idea! We aren't planning on an official ARM version in the near future, but would be happy to lend a helping hand to a community version if that's something you want to take on.

**Comment by andrewsomething** [comment]
While we don't officially support ARM at the moment, it should build on ARM if you have a Go environment set up. See: https://github.com/digitalocean/doctl#option-3--building-the-development-version-from-source

If you don't have a Go environment on the ARM device, Go does have support for cross-building. So from an i386 or amd64 environment, you could built an ARM binary. Eg.
```
$ cd cmd/doctl && GOOS=linux GOARCH=arm go build -o doctl
$ file doctl 
doctl: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, not stripped
$ uname -m
x86_64
```

Love to hear how it goes if you give it a try!
