### ISSUE TITLE
Suggestion: Show the completion command in help

### ISSUE THREAD

**Issue by GiannisSialmas** [digitalocean/doctl#446]
I noticed that the help text does not show completion as an available command. I had to search for it and read the read me to know the command exists. I think it would be helpful to other users to find in directly in help

**Comment by eddiezane** [comment]
This is an unfortunate side effect of the dependency used for completion.

More context here https://github.com/spf13/cobra/pull/671

Maybe there's a way we can manually print out a string to mention this somehow?

**Comment by eddiezane** [comment]
The original issue was `completion` was auto completing when trying to complete `compute` :facepalmpicard:

**Comment by kamaln7** [comment]
Forgot to say the magic words. I merged #447 which fixes this issue.
