### ISSUE TITLE
Making doctl configuration versatile

### ISSUE THREAD

**Issue by darkmorpher** [digitalocean/doctl#45]
More `.doctlcfg` options could be added, like setting a `droplet_id` alias like:
`droplet-id: someID|aliasName`

By default, Making SSH Connections with `doctl compute ssh` won't work if:
- ssh-key files are **not** in system generated name `id_rsa` as `doctl` assumes
- ssh-key files are **not** in default assumed directory `$HOME/.ssh/`

There is no option to import the differently named ssh-key file into **doctl** so I don't have to keep passing `--ssh-key-path` argument every time. Yes, keys are added to `ssh-agent` and I can make connections to droplet using plain `SSH` just fine.

**Comment by bryanl** [comment]
@darkmorpher, `doctl` will default to using `$HOME/.ssh/id_rsa`. You can pass another using the `--ssh-key-path` argument, or by adding the keys to your ssh agent (if you are not on windows)

Plans are in the works for adding more configuration items, but I don't understand `droplet_id`. Is there something that's missing, that you could possibly find useful? I believe adding a default ssh-key path seems like a good idea, and will take that into consideration as the new config feature takes shape.

**Comment by darkmorpher** [comment]
Sorry If it was a little vague, I updated the first^ post.
My keys are already added to ssh-agent (windows) but `doctl` just spits up "not found" error, so the only option now is to use `--ssh-key-path` argument every time. I had to go back to using plain SSH instead of `doctl`.

**Comment by bryanl** [comment]
@darkmorpher One of the big issues at hand is that ssh on Windows is weird. I can't assume there is a ssh binary, so we have included a custom ssh client. This client doesn't support ssh agent, but I don't know why it couldn't.

**Comment by bryanl** [comment]
I'm going to track SSH agent support in https://github.com/digitalocean/doctl/issues/65. Please feel free to reopen this issue if you don't feel this goes far enough.
