### ISSUE TITLE
Determine config file's default location at runtime

### ISSUE THREAD

**Issue by andrewsomething** [digitalocean/doctl#451]
Currently `doctl`'s help output specifies that the default location of the config file is `$HOME/.config/doctl/config.yaml`

```
  -c, --config string         config file (default is $HOME/.config/doctl/config.yaml)
```

This is hardcoded at:

https://github.com/digitalocean/doctl/blob/e5406406016386e95931501fc00d082691189f65/commands/doit.go#L82

In certain environments, this is not true. For instance, on Linux the location of the config file is determined by the `XDG_CONFIG_HOME` environment variable. On Windows, `LOCALAPPDATA` is used. Additionally when using the Ubuntu snap, `XDG_CONFIG_HOME` is overridden leading to misleading help output. E.g.

```
$ locate doctl | grep '\.config/doctl/config.yaml'
/home/asb/.config/doctl/config.yaml
/home/asb/snap/doctl/19/.config/doctl/config.yaml
```

Instead of hardcoding this path in the help output, we should determine config file's default location at runtime.

Hint: A helper function already exists for this:

https://github.com/digitalocean/doctl/blob/e5406406016386e95931501fc00d082691189f65/commands/doit.go#L158-L160

**Comment by hilary** [comment]
See also #457
