### ISSUE TITLE
Snap saves kubeconfig file in "/home/user/snap/doctl/39/.kube/config" when you run "doctl kubernetes cluster kubeconfig save cluster-name"

### ISSUE THREAD

**Issue by Rillian-Grant** [digitalocean/doctl#457]

**Comment by hilary** [comment]
... which causes problems using `kubectl` (see #458)

Working on a fix

**Comment by hilary** [comment]
After much digging, I believe that `doctl` will need to be [granted classic confinement](https://forum.snapcraft.io/t/classic-confinement-request-doctl/11785) for it to work and play well with `kubectl`. See also my [snapcraft forum post](https://forum.snapcraft.io/t/help-please-kubectl-doctl-strictly-confined/11693).

I'm waiting to hear back on my request for [approval for classic confinement](https://forum.snapcraft.io/t/classic-confinement-request-doctl/11785).

**Comment by hilary** [comment]
fix is in master!
