### ISSUE TITLE
kubeconfig save, exec-credential not aware of context

### ISSUE THREAD

**Issue by Marcuzz** [digitalocean/doctl#459]
**Actual behaviour / how to reproduce**

When authenticated for the first time with `doctl auth init` it uses the `default` context, which is expected. You can then call `doctl kubernetes cluster kubeconfig save CLUSTER_NAME` and it will fetch the users/contexts and save it to the kubeconfig.

The issue occurrs once you need to add a second context to doctl, using a command like `doctl auth init --context=everyday` and then wanting to add a cluster from that context to your kubeconfig using `doctl kubernetes cluster kubeconfig save CLUSTER_NAME2 --context=everyday` 

You would now expect `kubectl cluster-info` to display information about your cluster, but instead it shows an error similar to the following:
`Error: failed to fetch credentials for cluster "37ea18d5-xxxx-xxxx-xxxx-xxxxxxxxxx": cluster not found`

This is because it still assumes it should use the `default` context, when in-fact the `default` context does not have access to this cluster.

**Expected behaviour / fix**

Expected behaviour would be for the  `doctl kubernetes cluster kubeconfig save CLUSTER_NAME2 --context=everyday` to pass the context to `exec-credential` in the kubeconfig as shown in the image below:

![image](https://user-images.githubusercontent.com/3168421/58822922-db79e480-8638-11e9-805c-1f7e805faf41.png)

After adding this line everything works fine, even after removing it again for some reason, which I can only assume is because the context the cluster is supposed to have is cached at this point.

This should be a pretty simple fix for anyone familiar with the doctl codebase or Go in particular

**Comment by hilary** [comment]
Thanks for a lovely writeup!

**Comment by bentranter** [comment]
@Marcuzz This should be fixed as of [the latest release](https://github.com/digitalocean/doctl/releases), but please reopen if you have any more issues.

For some more info into the fix, what we do now is ensure that the `--context` string in the your kubeconfig's exec-credential command always contains the exact context that you ran the `doctl kubernetes cluster kubeconfig save` command with.

**Comment by Marcuzz** [comment]
Awesome 🥇 

Can confirm that it now works exactly like I wanted it to work. Good work! 😃
