### ISSUE TITLE
Cannot run binary

### ISSUE THREAD

**Issue by freekmurze** [digitalocean/doctl#46]
I followed the installation steps of option 2.

Running `doctl` results in this error message: `zsh: exec format error: doctl`

I'm on the latest version of OSX.

How can this be fixed?

**Comment by bryanl** [comment]
Try downloading https://github.com/digitalocean/doctl/releases/download/v1.0.1/doctl-1.0.1-darwin-10.6-amd64.tar.gz. It looks like you might have downloaded the linux version.

**Comment by freekmurze** [comment]
Thanks, that worked!

You might want to update [this article on your site](https://www.digitalocean.com/community/tutorials/how-to-use-doctl-the-official-digitalocean-command-line-client).

OSX users get directed to using doctl-1.0.0-linux-amd64.tar.gz

**Comment by sebs** [comment]
Prolly get the docs right on DO website: They do not doffer this cases on download time good UI wise.
