### ISSUE TITLE
Add a FreeBSD release

### ISSUE THREAD

**Issue by tjayl** [digitalocean/doctl#47]
I would like to make a FreeBSD port for the doctl tool.

It would be much easier to pull the release build from github rather than building it from source.

Would it be possible to add a FreeBSD release?

**Comment by bryanl** [comment]
I'm going to release a 1.0.2 today, and I'll try to get freebsd in that release.

**Comment by tjayl** [comment]
That would be great. Thanks

**Comment by darkmorpher** [comment]
@bryanl could you plz post a release change-log too? thanks.

**Comment by bryanl** [comment]
As an update, I'm working on adding a freebsd release. The tool I used to generate the cross platform binaries doesn't have freebsd support out of the box, but this isn't a show stopper.

**Comment by bryanl** [comment]
Update: We are still planning to do a freebsd release.

**Comment by cybernet** [comment]
+1

**Comment by dch** [comment]
hi folks, still waiting on this - unable to build from source either atm :-(

**Comment by xmudrii** [comment]
Is there an error building from source or you don't manage to do it?I would like to try building, but I bricked my PC now so I'm not able to do so. =(

**Comment by dch** [comment]
@xmudrii an excellent time to install FreeBSD then ;-)

It fails so:

```
 /r/g/bin env GOPATH=/repos/go go get github.com/digitalocean/doctl/cmd/doctl
# cd /repos/go/src/github.com/digitalocean/doctl; git submodule update --init --recursive
fatal: No url found for submodule path 'vendor/github.com/vektra/errors' in .gitmodules
package github.com/digitalocean/doctl/cmd/doctl: exit status 128
```

Following this error, if I *remove* the mocking repo, with this diff:

```diff
git diff
diff --git a/scripts/regenmocks.sh b/scripts/regenmocks.sh
index 762c5e6..528df0a 100755
--- a/scripts/regenmocks.sh
+++ b/scripts/regenmocks.sh
@@ -4,7 +4,6 @@
 
 set -e
 
-go get github.com/vektra/mockery/.../
 
 cd do
-mockery -all -note "Generated: please do not edit by hand"
\ No newline at end of file
+echo mockery -all -note "Generated: please do not edit by hand"
```

then the `doctl` binary is correctly created. I assume skipping some mocks is not going to affect the production code, if it is actually passing all tests :1st_place_medal:

**Comment by xmudrii** [comment]
This is not something needed. When you first time execute `go get` you'll get the said output:
`go get github.com/digitalocean/doctl/cmd/doctl`
```
# cd /home/freebsd/work/src/github.com/digitalocean/doctl; git submodule update --init --recursive
fatal: No url found for submodule path 'vendor/github.com/vektra/errors' in .gitmodules
package github.com/digitalocean/doctl/cmd/doctl: exit status 128
```

`go get` error-ed and `doctl` is not built. However, if you execute same command again, it will work flawless.
`go get github.com/digitalocean/doctl/cmd/doctl`
There is no output as it indicates successful build. Your `doctl` binary is available in your `$GOPATH/bin` and you should be able to use it without problems.

There is no need to play with removing mocking repos and so on, just executing `go get` again after previous failed will do the job. =)

Hopefully, someone of us will be able to fix this. =)

**Comment by xmudrii** [comment]
@dch This is not a real fix, actually this fixes nothing.
The file you changed [regenmocks.sh](https://github.com/digitalocean/doctl/blob/master/scripts/regenmocks.sh), is here to help `doctl` developers to generate mocks for API actions. It's just that, it's nothing about `go get`, this doesn't fix `go get`.
It's very possible that `go get` got working because effect explained in comment above.

Even to test, if you execute `go get github.com/vektra/mockery/.../` yourself, it will work.

**Comment by dbaio** [comment]
http://www.freshports.org/sysutils/doctl
Just landed, it's needed testing.

thanks @Jehops

**Comment by mauricio** [comment]
Looks like this one has been sorted out :)
