### ISSUE TITLE
Using Doctl to rebuild a droplet

### ISSUE THREAD

**Issue by kylebebak** [digitalocean/doctl#48]
I ran `doctl compute droplet list` to get a droplet_id for our droplets.

One of our droplets has droplet_id **12018347**.

I then ran `doctl compute image list` to get the image_id for the Ubuntu 14.04.4 x64 image. According to this command, the image with slug "ubuntu-14-04-x64" has the image_id **15943679**.

However, when I run `doctl compute droplet-action rebuild 12018347 --image-id 15943679`, doctl returns the following error:

**"POST https://api.digitalocean.com/v2/droplets/12018347/actions: 422 Image can't be blank"**

Is this image really blank, or this is this a problem with the API? If there is another image_id that refers to a "non-blank" Ubuntu 14.04.4 x64 image, how would I find it? Is `doctl compute image list` not the right way?

**Comment by bryanl** [comment]
Hi, I heard this might be incoming, so I prepared a fix in https://github.com/digitalocean/doctl/pull/49.

**Comment by bryanl** [comment]
@kylebebak The fix is in master now and will be in the next release if you want to wait on binaries.

**Comment by kylebebak** [comment]
@bryanl Thank you, I'm looking forward to using it but I think I'll wait for the next release =)
