### ISSUE TITLE
error passing one command result to another

### ISSUE THREAD

**Issue by designermonkey** [digitalocean/doctl#480]
I ran the following:

```
doctl compute tag delete <(doctl compute tag list --format "Name" --no-header)
```

to delete all the tags on our account. The error reported was:

```
Error: DELETE https://api.digitalocean.com/v2/tags//dev/fd/11: 404 The resource you were accessing could not be found.
```

It seems the file descriptor is not being opened but directly referenced.

**Comment by andrewsomething** [comment]
That process substitution syntax outputs the filename for file descriptor, not the contents itself. For example run:

```
file <(doctl compute tag list --format "Name" --no-header)
/dev/fd/63: symbolic link to pipe:[3163131]
```

This cat be treated as a file:

```
cat <(doctl compute tag list --format "Name" --no-header)
```

If you want to just pass the output of the list command to `doctl compute tag delete`, try:

```
doctl compute tag delete $(doctl compute tag list --format "Name" --no-header)
```

Please feel free to reopen this issue if I have misunderstood your problem.
