### ISSUE TITLE
Provide instructions with permission denied error when using Snap without kubeconfig access

### ISSUE THREAD

**Issue by andrewsomething** [digitalocean/doctl#481]
**Problem**

Similar to #475. Looks like [we will not be given](https://forum.snapcraft.io/t/personal-files-request-for-doctl-was-classic-confinement-request-doctl/11785/12) auto-connect for write access to kubeconfig.

When installed as an Ubuntu snap, doctl needs to be explicitly given permission to access `~/.kube/config` for use with the `doctl kubernetes cluster kubeconfig save` sub-command.

Attempting to save a kubeconfig file before granting those permissions results in an error:

    Error: open /home/asb/.kube/config.lock: permission denied

Unless you have read the README, this error message can be confusing and does not provide a path forward for the user.

**Proposed Solution**

When `doctl kubernetes cluster kubeconfig save` is run in a snap environment (hint: https://docs.snapcraft.io/environment-variables) without first being granted access to the doctl:kube-config plug, we should catch the permissions error (or check first if possible) and present the user with an error message with a clear path to resolving the problem. For example:

    Error: open /home/asb/.kube/config.lock: permission denied

    Using the doctl Snap? Grant access to the doctl:kube-config plug to use this command.

        sudo snap connect doctl:kube-config

**Comment by alelevinas** [comment]
THANKS!!!!

**Comment by draveness** [comment]
I met the save problem in production.

**Comment by dsebastien** [comment]
+1, please add this to doctl. I've spent 20 minutes looking at my file permissions before stumbling upon this and realizing this was an "issue" with snap! :)

**Comment by mwaeckerlin** [comment]
It does not work for me:

```
$ sudo snap connect doctl:kube-config
$ echo $?
0
$ doctl kubernetes cluster kubeconfig save bd90e23b-12e5-485b-beb6-a84af130dd8e
Warning: Using the doctl Snap? Please create the directory: "/home/marc/.kube" before trying again
Notice: Adding cluster credentials to kubeconfig file found in "/home/marc/.kube/config"
Notice: Setting current-context to do-ams3-k8-cluster
Warning: Using the doctl Snap? Grant access to the doctl:kube-config plug to use this command with: sudo snap connect doctl:kube-config
Error: mkdir /home/marc/.kube: permission denied
```

Installed on Ubuntu 20.04 using:

    sudo snap install doctl
    sudo snap connect doctl:kube-config
    snap install kubectl --classic

What's wrong?
