### ISSUE TITLE
Invalid Windows binaries v1.21.0

### ISSUE THREAD

**Issue by djcharding** [digitalocean/doctl#485]
1.21.0's windows binary is invalid.

![image](https://user-images.githubusercontent.com/10661937/61180976-76c58880-a5ed-11e9-86ed-0f8aa64e5432.png)

![image](https://user-images.githubusercontent.com/10661937/61180979-847b0e00-a5ed-11e9-865d-c53b1d1f3a40.png)

Reverted to using 1.20.0

**Comment by hilary** [comment]
Thanks for letting us know. I ran into a problem with the release scripts and thought I had found a way to recover gracefully as I had not yet tagged the release. 

Fun, fun, fun with the github API.

I'll cut a patch release which should fix the problem.

**Comment by hilary** [comment]
@djcharding I just cut v1.21.1 with a set of changes to prevent a release getting wedged in the way that v1.20.0. Sorry for the hassle. 😞
