### ISSUE TITLE
The floating IP already has a pending event.

### ISSUE THREAD

**Issue by DeanChan** [digitalocean/doctl#493]
Hi there~

When I'm deleting a floating ip right after it's unassigned from a droplet, the following error occurred:
`Error: DELETE https://api.digitalocean.com/v2/floating_ips/xxx.xxx.xxx.xx: 422 The floating IP already has a pending event.`
The corresponding command is :
```bsah
doctl compute floating-ip-action unassign $OLD_FLIP
doctl compute floating-ip create --droplet-id $DROPLET_ID
doctl compute floating-ip delete -f $OLD_FLIP
```
Inserting a `sleep 10` between the lines is a workaround, yet it *cannot guarantee* that the floating ip is changed successfully.

Is there any safer way to solve this?

Thank you.

**Comment by andrewsomething** [comment]
Unassigning a floating IP returns an action item which can be used to check the the status. Fore example:

```
$ doctl compute floating-ip-action unassign 178.128.133.144
ID           Status         Type           Started At                       Completed At    Resource ID    Resource Type    Region
721743418    in-progress    unassign_ip    2019-07-15 22:00:12 +0000 UTC    <nil>           2994767248     floating_ip      nyc1
$ doctl compute action wait 721743418
ID           Status       Type           Started At                       Completed At                     Resource ID    Resource Type    Region
721743418    completed    unassign_ip    2019-07-15 22:00:12 +0000 UTC    2019-07-15 22:00:13 +0000 UTC    2994767248     floating_ip      nyc1
```

Using `wait` here will block until the action has completed. In a script, you could use something like:

```
ACTION_ID=`doctl compute floating-ip-action unassign --no-header --format ID ${FLOATING_IP}`
doctl compute action wait ${ACTION_ID}
```

**Comment by DeanChan** [comment]
Wow cool! That works!
Many thanks for your help!
