### ISSUE TITLE
doctl not deleting snapshots

### ISSUE THREAD

**Issue by benzionyunger** [digitalocean/doctl#495]
I created a bash script to automate a daily snapshot creation, and keep the 5 oldest snapshots and delete the rest. Initially I was having trouble with the creation, until I saw this article [https://github.com/digitalocean/doctl/issues/184](url)  and started using the old version v1.5.0 for my script. 
The current issue is the delete is not working, its not returning any errors, but on every run its retrying the same IDs. My code runs this command `doctl compute snapshot delete <snapshot-id> -f` to delete. I also checked manually , by executing `doctl compute snapshot list` to see if the snapshot ID was still there, and it's still there. I also checked on the web console and the snapshots were still there undeleted.

**Comment by andrewsomething** [comment]
Hi @benzionyunger,

I'm not able to reproduce your issue with an up-to-date version of doctl. For example:

```
$ doctl compute snapshot list --format ID,Name | grep ved
49779932                                vedcmhxk-001-1563459111238
$ doctl compute snapshot delete 49779932
Warning: Are you sure you want to delete snapshot(s) (y/N) ? y
$ doctl compute snapshot list --format ID,Name | grep ved
$ 
```

We'll need some additional information to help understand why you're running into a problem. First of all, 
please make sure you are on the latest version. (All the features in v1.5.0 still exist in newer versions. The discussion in the issue you linked is about additional features added in v1.6.0.) Next, you can pass the `--trace` argument to the delete command. This provides information about the underlying API request. Finally, if you could share any details about your script, that would also be helpful.

**Comment by benzionyunger** [comment]
Hello Andrew and thank you for responding.

Before showing you what I did, l tried with a newer version like you
recommended, but to no avail.

Firstly I updated to 1.21.1 and for some reason it would only give me 1.20.
This is what I did:
curl -sL
https://github.com/digitalocean/doctl/releases/download/v1.21.1/doctl-1.21.1-linux-amd64.tar.gz
| tar -xzv

Afterwards I tried:
doctl version

and it returned me this:
doctl version 1.20.0-dev
release 1.21.1 is available, check it out!

That by itself doesn't make sense to me. In any case, I can't find the
create snapshot command anywhere with this version. I checked with -
doctl compute actions -h
doctl compute droplet snapshots -h
doctl compute droplet-actions -h
doctl compute image -h
doctl compute image-action -h

What's the correct command to create a snapshot?

**Comment by andrewsomething** [comment]
Thanks for pointing out the issue with the available version. I've opened #496 for that.

> What's the correct command to create a snapshot?

The correct syntax remains:

`doctl compute droplet-action snapshot <droplet-id> --snapshot-name "some-name"`

Downloading doctl the same way as you did above, I am able to see that command and use it successfully:

```
asb@asb-do:/tmp$ curl -sL https://github.com/digitalocean/doctl/releases/download/v1.21.1/doctl-1.21.1-linux-amd64.tar.gz | tar -xzv
doctl
asb@asb-do:/tmp$ ./doctl compute droplet-actions -h | grep snapshot
  snapshot           snapshot commands
asb@asb-do:/tmp$ ./doctl compute droplet-action snapshot 137147385 --snapshot-name "new-snapshot"
ID           Status         Type        Started At                       Completed At    Resource ID    Resource Type    Region
723556957    in-progress    snapshot    2019-07-18 16:14:48 +0000 UTC    <nil>           137147385      droplet          nyc3
```

**Comment by benzionyunger** [comment]
I must've missed that command.
I tried creating and deleting and it worked!

Thanks a ton!

**Comment by andrewsomething** [comment]
Awsome! Glad to help.
