### ISSUE TITLE
v1.23.0 binaries named with extra ".exe"

### ISSUE THREAD

**Issue by dbirks** [digitalocean/doctl#507]
The assets for v1.23.0 all have an extra .exe included in there. Example: `doctl-1.23.0-linux-amd64.exe.tar.gz`

Thanks for providing these!

**Comment by hilary** [comment]
Thanks, we're on it! If you're in the mood for irony. The bug came from the first step in adding tests to our build/release scripts. 🤦‍♀

**Comment by dbirks** [comment]
Very understandable, thanks for grabbing it :+1:
