### ISSUE TITLE
doctl compute droplet list ordering

### ISSUE THREAD

**Issue by mjclemente** [digitalocean/doctl#546]
First off, thanks for this fantastic tool - the DO platform and offerings are very developer friendly - much appreciated.

This is more of a question than an issue, but I'm not sure if there's a better place to post it. 

Is there a way to order the results of `doctl compute droplet list`?

In my use case I'm trying to determine if there is a simple way to access the most recently created Droplet, but more robust listing / sorting options seem like they may be beneficial.

Thanks!

**Comment by mark-veenstra** [comment]
@mjclemente I do not think this is an option directly in the `doctl` command, but you could use the JSON output together with `jq`, like so:

** sort on `created_at` ascending**
```
doctl compute droplet list -o json | jq -s '.[] |= sort_by(.created_at)' > output.json
```

**Comment by mjclemente** [comment]
Thanks! Makes sense. I forgot that the json option returned all the data about the Droplets. That's good enough for me

Really appreciate your help.
