### ISSUE TITLE
Is there any way to list all the contexts

### ISSUE THREAD

**Issue by murarisumit** [digitalocean/doctl#556]
I see we have two command `doctl auth init` and `doctl auth switch`. Is there any command to list all the context, or is this is valid question to ask of.  

How to manage multiple contexts for DO ?

**Comment by bentranter** [comment]
@murarisumit There currently is no command in `doctl` to list all the contexts. With that said, you can view all of the contexts by viewing your `doctl` config file, typically located at:
* `C:\Users\<your-username>\AppData\Local\doctl\config` on Windows
* Either `$XDG_CONFIG_HOME/doctl/config.yaml` or `~/.config/doctl/config.yaml` on Linux and Mac

The contexts appear under the `auth-contexts:` key in the config file.

With that said, I think this would be a useful feature to have, so we'll keep this ticket open to consider adding it.

**Comment by BaptismofFire** [comment]
according to doc below, use `doctl auth list`. that being said, if you find consistent error like 
1) you just dont have the mean to "re-initialize"
<pre><code>
PS C:\Users\XXXX> doctl auth init
Using token for context doct_access_test

Validating token... ✘

Error: Unable to use supplied token to access API: GET https://cloud.digitalocean.com/v1/oauth/token/info: 400 (request "2b9e1749-ac4a-47ef-a296-f78f5381b166"
</pre></code>
OR
2) the current `context` just refuse to change
<pre><code>
(base) PS C:\Users\xxx> doctl auth list
default
docker-push
doct_access_test (current)
(base) PS C:\Users\xxx> doctl auth switch docker-push
Now using context [doct_access_test] by default
(base) PS C:\Users\xxx> doctl auth list
default
docker-push
doct_access_test (current)
</pre></code>


delete the context-token relationship in `config.yaml`
if you cant find `config.yaml` at c:\user\xxx\.config\.doctl\, look for it with `doctl auth --config`
I found mine at **%APPDATA%\doctl\config.yaml**
<br>
Reference: 
https://docs.digitalocean.com/reference/doctl/reference/auth/list/
