### ISSUE TITLE
format ignored when output is json

### ISSUE THREAD

**Issue by gangachris** [digitalocean/doctl#569]
```
 doctl compute volume list --format ID,Name -o json
```

Will display everything ignoring the formatting. 

While the default
```
 doctl compute volume list --format ID,Name -o text
```

Will list only ID and Name

**Comment by andrewsomething** [comment]
Hi @gangachris. This is to be expected. When displaying text output, we do not show every attribute available, just a table of certain ones. The `--format` flag can be used to choose which table columns to display as some you might be interested in are hidden by default while others shown by default might not be needed in your case.

    --format string   Columns for output in a comma separated list.

Specifying `-o json` returns the full json output as returned by the API. If you want to display just the id and name attributes in JSON, I'd suggest piping the output to `jq`. For example:

    doctl compute volume list -o json | jq 'map({id: .id, name: .name})'

**Comment by gangachris** [comment]
@andrewsomething Ok. Makes sense. It just feels a little bit unintuitive. Thanks for the explanation.

Closing.

**Comment by andrewsomething** [comment]
Definetly. We can at least make the help output more clear that format is currently only for text output or perhaps make the arguments mutually exclusive. We'll consider adding support for JSON formatting in the future.

Thanks for the feedback!
