### ISSUE TITLE
[Suggestion] XDG conformance for .doctlcfg

### ISSUE THREAD

**Issue by RankoKohime** [digitalocean/doctl#59]
This would be a nice to have feature for those of us with OCD.  :)

**Comment by aybabtme** [comment]
@RankoKohime are you talking about https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html ?

If so, I think it's a good idea.

**Comment by RankoKohime** [comment]
I did neglect to put in that link, but yes, that is what I am referring to.  :)

**Comment by bryanl** [comment]
So, as I'm reading this, we'll have to add support for the `XDG_*` dirs, and default to the `$HOME/.config`  equivalent if they don't exist. This should work, but I would like to figure out an answer for Windows before proceeding. If anyone has any suggestions, I'm up for it.

**Comment by RankoKohime** [comment]
I think [this comment](https://github.com/rackspace/rack/issues/338#issuecomment-141701188) sums it up better than I could.  Although the appdirs module it refers to is python based, maybe it could be a good starting ground for all of the platforms?

**Comment by bryanl** [comment]
Still haven't stopped thinking about this. I've come to the conclusion this makes sense. Will be starting on this work soon. (vacation limiting of course)

**Comment by klauern** [comment]
Thank you @bryanl !  Much appreciated
