### ISSUE TITLE
`mkdir: permission denied` upon first usage

### ISSUE THREAD

**Issue by daohoangson** [digitalocean/doctl#591]
What I did:

1. Create a new droplet (image id `docker-18-04`)
1. Install doctl (`snap install doctl`)
1. Create a new user and change to said user
1. Execute any doctl command (e.g. `/snap/bin/doctl compute droplet delete 123 --access-token xxx`)

Expect:

1. `Warning: Are you sure you want to delete 1 droplet(s) (y/N) ? ` prompt

Actual:

1. `mkdir /home/test/.config: permission denied`

This happens with `root` account too. After manually creating the `.config` directory, it starts working without further issue.

**Comment by kamaln7** [comment]
Thanks for reporting this @daohoangson. If installed using snap, doctl has limited access to personal files. It's confined to `~/.config/doctl` (per [snapcraft.yaml](https://github.com/digitalocean/doctl/blob/master/snap/snapcraft.yaml#L51-L55)) so it can't create the directory `~/.config` if it doesn't exist.

I think this behavior is fine as doctl doesn't need access to all of `~/.config`. We should add a note to the README though.

**Comment by daohoangson** [comment]
Thanks @kamaln7 for replying, that makes perfect sense. I will create the directory before calling `doctl` then.

Should I close this issue right now or you want to leave it open until the README note addition?

**Comment by hilary** [comment]
Hmmm... actually, I would rather it create `~/.config` if it doesn't exist. It's a better UX. I'm going to update `snapcraft.yaml` accordingly.

**Comment by hilary** [comment]
We'll need snapcraft to update the snap definition for the change to take effect. I'll update `snapcraft.yaml` once the snap definition has been updated.

**Comment by daohoangson** [comment]
Awesome, that's even better. Thanks @hilary 👍

**Comment by mogwai** [comment]
It seems that doctl is creating .lock file in the config directory though. If it doesn't have persmissions in there then shouldn't the lock file be placed somewhere else?

**Comment by resetreboot** [comment]
Hello, I'm having an issue with this. My `.config` directory is a symlink, and it tries to create the directory anyway, and does not run.
