### ISSUE TITLE
kubectl cannot load credentials from doctl

### ISSUE THREAD

**Issue by webartistse** [digitalocean/doctl#595]
To use DO access token in CI you need the DIGITALOCEAN_ACCESS_TOKEN env. Kubectl cannot get the token I guess.

Setup:
- Bitbucket pipelines
- DO Kuberenetes

**Reproduce with image atlassian/default-image:2:**
`curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl`

`chmod +x ./kubectl`

`mv ./kubectl /usr/local/bin/kubectl`

`curl -LO https://github.com/digitalocean/doctl/releases/download/v1.32.0/doctl-1.32.0-linux-amd64.tar.gz`

`tar xf ./doctl-1.32.0-linux-amd64.tar.gz`

`chmod +x ./doctl`

`mv ./doctl /usr/local/bin/doctl`

`export DIGITALOCEAN_ACCESS_TOKEN=$DIGITALOCEAN_APIKEY`

`doctl kubernetes cluster kubeconfig save cluster-test`

`kubectl config get-contexts`

`kubectl get pods`

**Get pods will get:**
root@2c3df388eda2:/opt/atlassian/bitbucketci/agent/build# kubectl get pods
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xadb9fc]

goroutine 1 [running]:
github.com/digitalocean/doctl/commands.execCredentialFromConfig(0xc0000bdda0, 0x7f0, 0xe00, 0xc0000bdda0)
	/home/travis/gopath/src/github.com/digitalocean/doctl/commands/kubernetes.go:803 +0xfc
github.com/digitalocean/doctl/commands.(*KubernetesCommandService).RunKubernetesKubeconfigExecCredential(0xc000254ce0, 0xc00026f680, 0x0, 0xc00026f680)
	/home/travis/gopath/src/github.com/digitalocean/doctl/commands/kubernetes.go:775 +0x472
github.com/digitalocean/doctl/commands.cmdBuilderWithInit.func1(0xc00025d180, 0xc00026dc80, 0x1, 0x3)
	/home/travis/gopath/src/github.com/digitalocean/doctl/commands/doit.go:432 +0x118
github.com/spf13/cobra.(*Command).execute(0xc00025d180, 0xc00026dbc0, 0x3, 0x3, 0xc00025d180, 0xc00026dbc0)
	/home/travis/gopath/src/github.com/digitalocean/doctl/vendor/github.com/spf13/cobra/command.go:766 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x12efd80, 0x4eaf09, 0xc0000c2000, 0x8)
	/home/travis/gopath/src/github.com/digitalocean/doctl/vendor/github.com/spf13/cobra/command.go:852 +0x2ea
github.com/spf13/cobra.(*Command).Execute(...)
	/home/travis/gopath/src/github.com/digitalocean/doctl/vendor/github.com/spf13/cobra/command.go:800
github.com/digitalocean/doctl/commands.Execute()
	/home/travis/gopath/src/github.com/digitalocean/doctl/commands/doit.go:125 +0x34
main.main()
	/home/travis/gopath/src/github.com/digitalocean/doctl/cmd/doctl/main.go:24 +0x47
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xadb9fc]

goroutine 1 [running]:
github.com/digitalocean/doctl/commands.execCredentialFromConfig(0xc0001301e0, 0x7f0, 0xe00, 0xc0001301e0)
	/home/travis/gopath/src/github.com/digitalocean/doctl/commands/kubernetes.go:803 +0xfc
github.com/digitalocean/doctl/commands.(*KubernetesCommandService).RunKubernetesKubeconfigExecCredential(0xc0001fb090, 0xc0002137a0, 0x0, 0xc0002137a0)
	/home/travis/gopath/src/github.com/digitalocean/doctl/commands/kubernetes.go:775 +0x472
github.com/digitalocean/doctl/commands.cmdBuilderWithInit.func1(0xc00020d680, 0xc00023e330, 0x1, 0x3)
	/home/travis/gopath/src/github.com/digitalocean/doctl/commands/doit.go:432 +0x118
github.com/spf13/cobra.(*Command).execute(0xc00020d680, 0xc00023e270, 0x3, 0x3, 0xc00020d680, 0xc00023e270)
	/home/travis/gopath/src/github.com/digitalocean/doctl/vendor/github.com/spf13/cobra/command.go:766 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x12efd80, 0x4eaf09, 0xc0000b6000, 0x8)
	/home/travis/gopath/src/github.com/digitalocean/doctl/vendor/github.com/spf13/cobra/command.go:852 +0x2ea
github.com/spf13/cobra.(*Command).Execute(...)
	/home/travis/gopath/src/github.com/digitalocean/doctl/vendor/github.com/spf13/cobra/command.go:800
github.com/digitalocean/doctl/commands.Execute()
	/home/travis/gopath/src/github.com/digitalocean/doctl/commands/doit.go:125 +0x34
main.main()
	/home/travis/gopath/src/github.com/digitalocean/doctl/cmd/doctl/main.go:24 +0x47
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xadb9fc]

goroutine 1 [running]:
github.com/digitalocean/doctl/commands.execCredentialFromConfig(0xc00017f1a0, 0x7f0, 0xe00, 0xc00017f1a0)
	/home/travis/gopath/src/github.com/digitalocean/doctl/commands/kubernetes.go:803 +0xfc
github.com/digitalocean/doctl/commands.(*KubernetesCommandService).RunKubernetesKubeconfigExecCredential(0xc000244cd0, 0xc000264ea0, 0x0, 0xc000264ea0)
	/home/travis/gopath/src/github.com/digitalocean/doctl/commands/kubernetes.go:775 +0x472
github.com/digitalocean/doctl/commands.cmdBuilderWithInit.func1(0xc00024d180, 0xc00025dcb0, 0x1, 0x3)
	/home/travis/gopath/src/github.com/digitalocean/doctl/commands/doit.go:432 +0x118
github.com/spf13/cobra.(*Command).execute(0xc00024d180, 0xc00025dbf0, 0x3, 0x3, 0xc00024d180, 0xc00025dbf0)
	/home/travis/gopath/src/github.com/digitalocean/doctl/vendor/github.com/spf13/cobra/command.go:766 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x12efd80, 0x4eaf09, 0xc0000c8000, 0x8)
	/home/travis/gopath/src/github.com/digitalocean/doctl/vendor/github.com/spf13/cobra/command.go:852 +0x2ea
github.com/spf13/cobra.(*Command).Execute(...)
	/home/travis/gopath/src/github.com/digitalocean/doctl/vendor/github.com/spf13/cobra/command.go:800
github.com/digitalocean/doctl/commands.Execute()
	/home/travis/gopath/src/github.com/digitalocean/doctl/commands/doit.go:125 +0x34
main.main()
	/home/travis/gopath/src/github.com/digitalocean/doctl/cmd/doctl/main.go:24 +0x47
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xadb9fc]

goroutine 1 [running]:
github.com/digitalocean/doctl/commands.execCredentialFromConfig(0xc0001902a0, 0x7f0, 0xe00, 0xc0001902a0)
	/home/travis/gopath/src/github.com/digitalocean/doctl/commands/kubernetes.go:803 +0xfc
github.com/digitalocean/doctl/commands.(*KubernetesCommandService).RunKubernetesKubeconfigExecCredential(0xc000246c80, 0xc00025d0e0, 0x0, 0xc00025d0e0)
	/home/travis/gopath/src/github.com/digitalocean/doctl/commands/kubernetes.go:775 +0x472
github.com/digitalocean/doctl/commands.cmdBuilderWithInit.func1(0xc00024f180, 0xc000261b00, 0x1, 0x3)
	/home/travis/gopath/src/github.com/digitalocean/doctl/commands/doit.go:432 +0x118
github.com/spf13/cobra.(*Command).execute(0xc00024f180, 0xc000261a40, 0x3, 0x3, 0xc00024f180, 0xc000261a40)
	/home/travis/gopath/src/github.com/digitalocean/doctl/vendor/github.com/spf13/cobra/command.go:766 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x12efd80, 0x4eaf09, 0xc0000ca000, 0x8)
	/home/travis/gopath/src/github.com/digitalocean/doctl/vendor/github.com/spf13/cobra/command.go:852 +0x2ea
github.com/spf13/cobra.(*Command).Execute(...)
	/home/travis/gopath/src/github.com/digitalocean/doctl/vendor/github.com/spf13/cobra/command.go:800
github.com/digitalocean/doctl/commands.Execute()
	/home/travis/gopath/src/github.com/digitalocean/doctl/commands/doit.go:125 +0x34
main.main()
	/home/travis/gopath/src/github.com/digitalocean/doctl/cmd/doctl/main.go:24 +0x47
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xadb9fc]

goroutine 1 [running]:
github.com/digitalocean/doctl/commands.execCredentialFromConfig(0xc00024c5a0, 0x7f0, 0xe00, 0xc00024c5a0)
	/home/travis/gopath/src/github.com/digitalocean/doctl/commands/kubernetes.go:803 +0xfc
github.com/digitalocean/doctl/commands.(*KubernetesCommandService).RunKubernetesKubeconfigExecCredential(0xc000212fd0, 0xc00022f560, 0x0, 0xc00022f560)
	/home/travis/gopath/src/github.com/digitalocean/doctl/commands/kubernetes.go:775 +0x472
github.com/digitalocean/doctl/commands.cmdBuilderWithInit.func1(0xc000223680, 0xc00022dec0, 0x1, 0x3)
	/home/travis/gopath/src/github.com/digitalocean/doctl/commands/doit.go:432 +0x118
github.com/spf13/cobra.(*Command).execute(0xc000223680, 0xc00022de00, 0x3, 0x3, 0xc000223680, 0xc00022de00)
	/home/travis/gopath/src/github.com/digitalocean/doctl/vendor/github.com/spf13/cobra/command.go:766 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x12efd80, 0x4eaf09, 0xc0000c0000, 0x8)
	/home/travis/gopath/src/github.com/digitalocean/doctl/vendor/github.com/spf13/cobra/command.go:852 +0x2ea
github.com/spf13/cobra.(*Command).Execute(...)
	/home/travis/gopath/src/github.com/digitalocean/doctl/vendor/github.com/spf13/cobra/command.go:800
github.com/digitalocean/doctl/commands.Execute()
	/home/travis/gopath/src/github.com/digitalocean/doctl/commands/doit.go:125 +0x34
main.main()
	/home/travis/gopath/src/github.com/digitalocean/doctl/cmd/doctl/main.go:24 +0x47
Unable to connect to the server: getting credentials: exec: exit status 2

**Comment by webartistse** [comment]
Problem when I try to auth another way:

root@2c3df388eda2:/opt/atlassian/bitbucketci/agent/build# doctl auth init --access-token "02...ce"
Using token [02...ce]

Validating token... OK

Error: open /root/.config/doctl/config.yaml: no such file or directory

**Comment by andrewsomething** [comment]
Hi, thanks for raising this issue. It looks like there was a temporary issue with this DigitalOcean API that should now be resolved. Can you give it another try?

That said, `doctl` should protect against this error better. The problem can be found here:

https://github.com/digitalocean/doctl/blob/master/commands/kubernetes.go#L801-L806

Panic when I reproduced: 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xadb9fc]

goroutine 1 [running]:
github.com/digitalocean/doctl/commands.execCredentialFromConfig(0xc00008e360, 0x81a, 0xe00, 0xc00008e360)
	/build/parts/doctl/build/commands/kubernetes.go:803 +0xfc
github.com/digitalocean/doctl/commands.(*KubernetesCommandService).RunKubernetesKubeconfigExecCredential(0xc0002430a0, 0xc000317d40, 0x0, 0xc000317d40)
	/build/parts/doctl/build/commands/kubernetes.go:775 +0x472
github.com/digitalocean/doctl/commands.cmdBuilderWithInit.func1(0xc00024d180, 0xc000259d10, 0x1, 0x3)
	/build/parts/doctl/build/commands/doit.go:432 +0x118
github.com/spf13/cobra.(*Command).execute(0xc00024d180, 0xc000259c50, 0x3, 0x3, 0xc00024d180, 0xc000259c50)
	/build/parts/doctl/build/vendor/github.com/spf13/cobra/command.go:766 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x12e7d80, 0x4eaf09, 0xc0000c4000, 0x8)
	/build/parts/doctl/build/vendor/github.com/spf13/cobra/command.go:852 +0x2ea
github.com/spf13/cobra.(*Command).Execute(...)
	/build/parts/doctl/build/vendor/github.com/spf13/cobra/command.go:800
github.com/digitalocean/doctl/commands.Execute()
	/build/parts/doctl/build/commands/doit.go:125 +0x34
main.main()
	/build/parts/doctl/build/cmd/doctl/main.go:24 +0x47
```

The second error mentioned in your comment looks to be a separate problem introduced in https://github.com/digitalocean/doctl/pull/589

**Comment by bentranter** [comment]
@webartistse As of the [latest release](https://github.com/digitalocean/doctl/releases/tag/v1.32.1), we've fixed the issue mentioned in your second comment, so both of these issues should now be resolved.

**Comment by webartistse** [comment]
@bentranter You were right becaue now it worked! And very fast update :) Is it at better place to get latest version or a specific one? Because now the build script fails when downloading older version is getting 404.

**Comment by bentranter** [comment]
@webartistse You'll want to get the latest version – the old one is 404'ing because I deleted it, since it was pretty broken for most users.

**Comment by webartistse** [comment]
@bentranter yeah I know but now Im gonna add this to 10 repos so next time you do a release and remove the previous version all 10 builds will fail and needs an update. A solution could be the same way Im getting kubectl:
curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl

Is this something for doctl as well?

**Comment by andrewsomething** [comment]
@webartistse Using the GitHub API, you can do something like this to get the most recent release:

```
DOCTL_VERSION=`curl "https://api.github.com/repos/digitalocean/doctl/releases/latest" | jq -r .tag_name | sed "s/v//"`
curl -LO "https://github.com/digitalocean/doctl/releases/download/v${DOCTL_VERSION}/doctl-${DOCTL_VERSION}-linux-amd64.tar.gz"
```
