### ISSUE TITLE
doctl auth : no such file

### ISSUE THREAD

**Issue by ahafid01** [digitalocean/doctl#604]
On Macos, when I run `$ doctl auth init`
I have this stak :
DigitalOcean access token: 
Validating token... OK
Error: open .../Library/Application Support/doctl/config.yaml: no such file or directory.

doctl version : 1.32.0-release

**Comment by bentranter** [comment]
Hey @ahafid01, unfortunately the 1.32.0 release is broken – if you upgrade to 1.32.2 (the latest release as of the time of writing), you won't see those issues.

**Comment by NebojsaKrtolica** [comment]
hi @ahafid01  and @bentranter 

I've had the exact same issue on my macos 10.14.6.

What i did was:

1. navigate to the Application Support folder
2. created an empty dir with `mkdir doctl`
3. created an empty config.yaml in that newly created folder with: `touch doctl/config.yaml`

I hope this helps  🍀

**Comment by bentranter** [comment]
Hey @NebojsaKrtolica, thanks for sharing – that's definitely the right (and only!) workaround for using doctl on 1.32.0. For some more context in case other folks hit this issue, 1.32.0 had an issue affecting MacOS and some Windows users where we fail to create the `doctl` directory before reading `config.yaml` from in there. 1.32.1 and up doesn't have this, so the fix should be as easy as upgrading.

**Comment by ahafid01** [comment]
hi @bentranter and @NebojsaKrtolica
Both solutions work fine, so I upgraded doctl
Thank you

**Comment by aiandev** [comment]
` doctl auth init -c ~/Library/Application\ Support/doctl/config.yaml `
even I had the file in default location I got this error `Error: open : no such file or directory`,
Fixing :  I have provided the file location and it works

**Comment by ricardov03** [comment]
Thanks, @aiandev. That work for me.

**Comment by lu-roth** [comment]
I opened an issue for this bug cause its tedious to always append the --config/-c flag to every command.
https://github.com/digitalocean/doctl/issues/1280

**Comment by lu-roth** [comment]
For everyone who is exhausted by appending --config/-c to every doctl command, you can edit your ~/.zshrm or ~/.bashrc (depending on what shell you use) and add the following line. 
You may have to adjust the first path of your doctl installation and the path for the config file.

```
doctl () {
	/usr/local/bin/doctl "$@" --config=${HOME}/.doctl/config.yaml
}
```
