### ISSUE TITLE
Windows SSH client agent support

### ISSUE THREAD

**Issue by bryanl** [digitalocean/doctl#65]
Doctl uses a custom ssh client because it can't assume there is a ssh executable in the path. In order to be more friendly, there should exist support for SSH agents.

**Comment by xmudrii** [comment]
Is this still a problem on Windows?

What about:
https://godoc.org/golang.org/x/crypto/ssh#Permissions
It talks about `permit-ssh-agent`.
But also more important - https://godoc.org/golang.org/x/crypto/ssh/agent

Is it possible to fix issue with this, is this still a issue?

cc @aybabtme @nanzhong

**Comment by xmudrii** [comment]
By looking more into issue, it looks like it's already implemented/fixed long time ago if I'm thinking of right thing.
On [lines 77-85](https://github.com/digitalocean/doctl/blob/master/pkg/ssh/ssh_internal.go#L77-L85), as well as [lines 188-194](https://github.com/digitalocean/doctl/blob/master/pkg/ssh/ssh_internal.go#L188-L194) of [`pkg/ssh/ssh_internal.go`](https://github.com/digitalocean/doctl/blob/master/pkg/ssh/ssh_internal.go), you can see Agent Forwarding code.

Commit ec6d5c2 implemented it.

If this is right thing, this issue could be closed. If not, provide more context on what is needed if it's possible.

cc @viola @caueguerra @mauricio

**Comment by mauricio** [comment]
Yup, this has been sorted out already.
