### ISSUE TITLE
-bash: /usr/local/bin/geth: cannot execute binary file

### ISSUE THREAD

**Issue by joe-nano** [digitalocean/doctl#654]
Cannot geth in the command line. On Mac OSX Catalina. Need some help here. Any reason?

**Comment by andrewsomething** [comment]
Hi Joe, we'll need some more information to get to better understand the issue you're experiencing. Could you let us know:

- How did you install `doctl`?
- What you were doing when you encountered this error?

**Comment by hilary** [comment]
I'm sorry, I don't understand. How is `doctl` involved?

**Comment by goatandsheep** [comment]
all my commands return this error. what is `doctl`?

**Comment by feraudet** [comment]
Hello,
The same here with fresh brew installation: `$ geth
-bash: /usr/local/bin/geth: cannot execute binary file`

**Comment by hilary** [comment]
Does not appear `doctl` related.
