### ISSUE TITLE
Context switch not persisted

### ISSUE THREAD

**Issue by fabn** [digitalocean/doctl#656]
I've just upgraded to latest doctl and now my context are broken:

```
$ doctl version
doctl version 1.32.3-release
$ doctl auth switch --context xxx
Now using context [xxx] by default
$ doctl k8s clusters list
ID    Name    Region    Version    Auto Upgrade    Status    Node Pools
# This is the expected output, but I get it only if I pass context
$ doctl k8s clusters list --context xxx
ID                                      Name        Region    Version        Auto Upgrade    Status     Node Pools
325b08c2-8e24-4c9b-9c55-d2f0aafb33ab    xxx         fra1      1.15.4-do.0    true            running    xxx-default-pool
```

As result I cannot interact with my Kubernetes cluster anymore

```
kubectl get pods
Error: failed to fetch credentials for cluster "325b08c2-8e24-4c9b-9c55-d2f0aafb33ab": cluster not found
Error: failed to fetch credentials for cluster "325b08c2-8e24-4c9b-9c55-d2f0aafb33ab": cluster not found
Error: failed to fetch credentials for cluster "325b08c2-8e24-4c9b-9c55-d2f0aafb33ab": cluster not found
Error: failed to fetch credentials for cluster "325b08c2-8e24-4c9b-9c55-d2f0aafb33ab": cluster not found
Error: failed to fetch credentials for cluster "325b08c2-8e24-4c9b-9c55-d2f0aafb33ab": cluster not found
Unable to connect to the server: getting credentials: exec: exit status 1
```

How can I fix that?

**Comment by Voziv** [comment]
I just installed `doctl` via the snap method. Running `doctl auth switch --context voziv` doesn't persist for me either. When I run `doctl account get` it shows me the default account that I have setup.

```
$ doctl version
doctl version 1.32.3-release
Git commit hash: d9a63ca
```

**Comment by hilary** [comment]
We have a fix in https://github.com/digitalocean/doctl/pull/651. I'll update once merged.

**Comment by hilary** [comment]
The fix is in master. 

@Voziv you can get the fix by switching to the candidate channel for the moment: use `snap install doctl --candidate` to install. We'll release a new stable version on Monday. (Most of engineering is at a retreat at present, so we're currently conservative about releases.)

@fabn you could install from source or just revert for the moment. The new release will be out on Monday with the fix.

**Comment by Voziv** [comment]
Switching to the candidate release when I do `doctl auth switch --context voziv` and run `doctl account get` I see the correct details. :tada: 

So far looks great! Thanks :grinning:

**Comment by hilary** [comment]
Great! Thanks for taking the chance on a release candidate and for reporting back. Please let me know if you run into any problems with it.

**Comment by fabn** [comment]
> @fabn you could install from source or just revert for the moment. The new release will be out on Monday with the fix.

I've used homebrew to install. Which version I should rollback to to have ti working again?

**Comment by zachgersh** [comment]
@fabn - `1.33.0` should get you back to working correctly again. Let us know if it doesn't!

**Comment by fabn** [comment]
Yes, I tried binary from releases page and it's working. Homebrew didn't publish it yet, but the issue can be closed.

**Comment by zachgersh** [comment]
@fabn excellent! Really apologize for the bug and hopefully homebrew gets that updated soonish!
