### ISSUE TITLE
Kubernetes cluster creation flag bug

### ISSUE THREAD

**Issue by AntoineDao** [digitalocean/doctl#668]
Having some problems with the 1.33.0 release of doctl whereby I can't create an autoscaling cluster the way I did in 1.32.3.

I think the issue lies with the changes made at this line: https://github.com/digitalocean/doctl/blob/3dd3c265426b9998603bfdfb598012f4eebfea65/commands/kubernetes.go#L1130

Not sure what `c.NS` is so can't really debug it properly however I suspect this boolean statement is returning true when it shouldn't. I suspect this because running the following command returns the following error:

```console
➜ doctl k8s cluster create new-cluster \
    --region nyc3 \
    --version 1.15.5-do.0 \
    --node-pool "name=default;auto-scale=true;min-nodes=2;max-nodes=5" \ 
    --access-token $DO_TOKEN

Error: flags "size" and "count" cannot be provided when "node-pool" is present
```

I'm happy to give a go at fixing it if someone can give me some indication as to what the `c.NS` variable refers to in the context of doctl. 

Thanks for all the great work!

**Comment by zachgersh** [comment]
Hey @AntoineDao - really appreciate you reporting this bug and sorry for any problems it may have caused you! 

We did a refactoring to try to straightening out our flag setting/getting and inadvertently ran into this bug https://github.com/spf13/viper/issues/323 on viper. We've just reverted the changes (as a short term fix) and added another integration test to make sure this doesn't happen in the future. 

If you can rebuild from master that version should work, if not, we'll be releasing a version v1.34.0 shortly.

**Comment by AntoineDao** [comment]
No worries, was easy to just revert to previous release. Figured you guys would benefit from a bug report :smile: .

Thanks for the quick reply.

Also, classic bug:
![image](https://user-images.githubusercontent.com/20436635/67722588-40d5d400-fa25-11e9-9a59-cb8379d84708.png)

**Comment by zachgersh** [comment]
@AntoineDao excellent meme. This should now be fixed with release https://github.com/digitalocean/doctl/releases/tag/v1.33.1

I am going to close and if you still have a problem please reopen the issue! 

Again, really appreciate the bug report.
