### ISSUE TITLE
OSX zsh error after tar ball install

### ISSUE THREAD

**Issue by cabbiepete** [digitalocean/doctl#71]
after following the basic install (download tar, extract)

Running 
```
./doctl auth login
```

Produces
```
zsh: exec format error: ./doctl
```

**Comment by cabbiepete** [comment]
Installing on osx via

```
brew install dolt
```

Produces a workable command

**Comment by bryanl** [comment]
@cabbiepete it looks like you have downloaded the binary for Linux. Glad it is working for you now.
