### ISSUE TITLE
Question: Is there a way to get the doctl-equivalent of a droplet creation from the web UI ?

### ISSUE THREAD

**Issue by paraita** [digitalocean/doctl#710]
I'd like to know if there's a way to know the doctl command equivalent to a digital ocean resource I've created (let's say a droplet) from the web UI ?
Does my request make any sense ?

**Comment by andrewsomething** [comment]
Hi @paraita,

It does make sense! :smile: In fact, on idea that we have discussed is actually showing the command right in the web UI, updating it in real time as you make changes, to show that just about anything you can do in the UI you can do with `doctl` as well. Though, unfortunately, nothing like that currently exist.

We're working on expanding the `doctl` help documentation to make it easier to know which flags  correspond to options shown in web UI. Is there a specific option you can't translate into a `doctl` command? I'm happy to help if you have further questions!

**Comment by paraita** [comment]
> It does make sense! 😄 In fact, on idea that we have discussed is actually showing the command right in the web UI, updating it in real time as you make changes, to show that just about anything you can do in the UI you can do with `doctl` as well. Though, unfortunately, nothing like that currently exist.

That would be an awesome feature !


> We're working on expanding the `doctl` help documentation to make it easier to know which flags correspond to options shown in web UI. Is there a specific option you can't translate into a `doctl` command? I'm happy to help if you have further questions!

I don't have any particular problems with the `doctl` options but I'd completely dig an interactive mode for `doctl` like `az interactive` or `was-shell`. Writing commands would be much faster if I could just autocomplete parameters names and contextual values (ssh-keys for example).

I'll just close the issue since you gave me the info. I'll rely on the man for the time being, thanks for your help !

**Comment by andrewsomething** [comment]
Thanks for the feedback @paraita!
