### ISSUE TITLE
Support Trusted Sources in Managed Database?

### ISSUE THREAD

**Issue by JamesChevalier** [digitalocean/doctl#711]
The API supports updating a database cluster's firewall rules (known as "trusted sources" in the control panel). Is there a plan/timeline to include this functionality in doctl?

Related Links:
- https://github.com/digitalocean/api-v2/issues/178
- https://developers.digitalocean.com/documentation/changelog/api-v2/managed-databases-firewall-and-sql-mode-management/
- https://developers.digitalocean.com/documentation/v2/#update-firewall-rules--trusted-sources--for-a-database-cluster

**Comment by LoopsGod** [comment]
Yes this would be great, especially for dynamically adding an IP address with CI/CD runners.

**Comment by charlimmelman** [comment]
Yes, this would be a great addition.
