### ISSUE TITLE
Complete Uninstall

### ISSUE THREAD

**Issue by KamuelaFranco** [digitalocean/doctl#716]
The docs seem to be missing a guide to completely uninstall on various environments. I am looking for a complete uninstall on macOS with homebrew.

**Comment by zachgersh** [comment]
hey there @KamuelaFranco - brew makes this pretty easy:

`brew uninstall -f doctl`

the `-f` flag being there to uninstall all older versions of the formula as well.

Hope that helps and please reopen if not.

**Comment by zachgersh** [comment]
One more thing you need to make sure you remove, because I don't believe brew knows how to clean this up - the doctl config dir.

On mac you would remove this directory completely
```
$HOME/Library/Application Support/doctl
```

**Comment by KamuelaFranco** [comment]
#743
