### ISSUE TITLE
context switching in Readme tripped me up

### ISSUE THREAD

**Issue by winwisely99** [digitalocean/doctl#719]
Might want to make the command more explicit.

Currently says:

To use a non-default context, pass the context name as described above to any doctl command. To set a new default context, run doctl auth switch. This command will save the current context to the config file and use it for all commands by default if a context is not specified.

should say:
````
doctl auth switch --context $(DIGITALOCEAN_CONTEXT)

````

**Comment by andrewsomething** [comment]
Thanks for flagging this for us. I can definitely see how that could trip someone up.
