### ISSUE TITLE
`kubectl cluster create` gotchas (for me at least!)

### ISSUE THREAD

**Issue by DazWilkin** [digitalocean/doctl#722]
`doctl` and the Golang SDK are both very good, thanks!

Playing around with `doctl` today, I encountered some gotchas.
```bash
doctl version
doctl version 1.36.0-release
Git commit hash: 5233d90
```
While these are undoubtedly user errors, I hope the feedback is useful.

```bash
NAME=freddie
SIZE=s-1vcpu-2gb
REGION=sfo2
VERSION=1.16.2-do.1
```
Here's a working command:
```
doctl kubernetes cluster create ${NAME} \
--node-pool="name=default;size=${SIZE};count=3;tag=${TAG1};tag=${TAG2}" \
--region=${REGION} \
--version=${VERSION}
```
#### 1. Must use semi-colons:

I inadvertently used commas instead of semi-colons:
```bash
doctl kubernetes cluster create ${NAME} \
--node-pool="name=default,size=${SIZE},count=3,tag=${TAG1},tag=${TAG2}" \
--region=${REGION} \
--version=${VERSION}
```
The result is *unexpected*:
```
doctl kubernetes cluster node-pool list ${NAME} --format=Name
Name
default
exporter-pool-2
exporter-pool-3
exporter-pool-4
exporter-pool-5
```
Fortunately, either I've insufficient quota or this command is ineffective and appears to **not** succeed in provisioning the cluster nor creating any droplets.

#### 2. Must quote the `--node-pool` string
Initially, I didn't quote the `--node-pool` string (and I used commas). Even using semi-colons, not quoting the `--node-pool` string is problematic:
```bash
doctl kubernetes cluster create ${NAME} \
--node-pool=name=default;size=${SIZE};count=3;tag=${TAG1};tag=${TAG2} \
--region=${REGION} \
--version=${VERSION}
```
This appears to not parse beyond `--node-pool`. While the pool appears created correctly, the command returns an error (`--region=sfo2: command not found
`) and the region (defaults to?) `nyc1`:
```bash
doctl kubernetes cluster get ${NAME} --format=Region
Region
nyc1
```
and:
```bash
doctl kubernetes cluster get ${NAME} --output=json \
| jq -r ".[]|select(.name=\"${NAME}\")|.region == \"${REGION}\""
false
```
Although:
```bash
doctl kubernetes cluster node-pool list ${NAME} --format=Name,Size,Count
Name       Size           Count
default    s-1vcpu-2gb    3
```

**Comment by hilary** [comment]
Thanks for the detailed feedback! We really appreciate it. And so will the rest of the DO community, until we get a chance to ensure that `doctl` behaves more intuitively. :)
