### ISSUE TITLE
Cannot execute binary file when following instructions in Readme.md

### ISSUE THREAD

**Issue by jaredcaputo** [digitalocean/doctl#73]
Hi, I get the error "-bash: /usr/local/bin/doctl: cannot execute binary file" when following the instructions in the readme file.

**Comment by aybabtme** [comment]
Hi @jaredcaputo !  What OS are you using?

**Comment by jaredcaputo** [comment]
Mac OS X 10.11.4

**Comment by aybabtme** [comment]
@jaredcaputo can you list out exactly what commands you performed?

**Comment by jaredcaputo** [comment]
cd ~

curl -OL
https://github.com/digitalocean/doctl/releases/download/v1.0.0/doctl-1.0.0-linux-amd64.tar.gz

tar xf doctl-1.0.0-linux-amd64.tar.gz

sudo mv ./doctl /usr/local/bin

doctl auth login

Then, on the final one, I get: -bash: /usr/local/bin/doctl: cannot execute
binary file

On Fri, May 6, 2016 at 7:54 PM Antoine Grondin <notifications@github.com>
wrote:

> @jaredcaputo <https://github.com/jaredcaputo> can you list out exactly
> what commands you performed?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/digitalocean/doctl/issues/73#issuecomment-217589606>
>
-- 
Jared Caputo
Silver Palm Productions, LLC
(941) 404-8145
Jared@silverpalmproductions.com

**Comment by jaredcaputo** [comment]
Also tried on another Mac running the same OS, didn't work.

**Comment by aybabtme** [comment]
thanks @jaredcaputo, the problem is that our readme tells people to download the Linux executable, which doesn't work on OS X. Try installing with `brew install doctl`, or this link if you want to download manually: 

```
https://github.com/digitalocean/doctl/releases/download/v1.1.0/doctl-1.1.0-darwin-10.6-amd64.tar.gz
```

**Comment by jaredcaputo** [comment]
Works! Thanks very much!!

**Comment by Aprea123** [comment]
I missing myself inside of the com.apple /PrivateFrameworks and you find several times "cannot execute binary file".  Just finish now to install doctl. Thank you very much.
