### ISSUE TITLE
WINDOWS VERSION? We dont all run mac you know

### ISSUE THREAD

**Issue by nigel-dewar** [digitalocean/doctl#730]
Alot of tutorials including your own specify using this tool, and yet it has no Windows version???

We all not yuppies with macs. 

Please make this tool Windows capable.

**Comment by hilary** [comment]
Hi @nigel-dewar 

We have windows binaries available for download in [releases](https://github.com/digitalocean/doctl/releases). We have a thriving community of windows users! Our CI/CD pipeline includes windows, via TravisCI. Our windows users are very important to us. :)

Not a yuppy with a mac :)

Hilary

**Comment by nigel-dewar** [comment]
Thanks very much, this is appreciated. This fact should be advertised far and wide.

cheers
