### ISSUE TITLE
Ephemeral Access Token

### ISSUE THREAD

**Issue by hostragon-hosting** [digitalocean/doctl#75]
After authenticating using:  doctl auth login --access-token {string}

The `doctl auth login` doesn't' work.

you still get: 

> Error: access token is required

 when trying to run `doctl compute droplet list` or most of the commands.

To list, you have to use:

`doctl compute droplet list --region nyc3 --output json --access-token`

That's not ideal if you have to use the token each time.

Installed via Homebrew

**Comment by Auralien** [comment]
Same problem for me, also installation via Homebrew. It seems like `doctlcfg` file is not being created, can't find it in the home directory.

**Comment by fevrin** [comment]
I think this changed in v1.1.0.  `doctl auth login` works fine for me in v1.0.2, but running the same command with v1.1.0 on a new machine leads to the "access token is required" error.  I've encountered this on Ubuntu 16.04, and it does look like ~/.doctlcfg isn't being created as it should be with v1.1.0.  Once that file exists (I just used v1.0.2 to create it), v1.1.0 seems to work fine for me. #

**Comment by bryanl** [comment]
`doctl auth login` will be removed in the next version and replaced with `doctl auth init`. This will alleviate problems seen with Windows.
