### ISSUE TITLE
auth login does not open a new browser tab

### ISSUE THREAD

**Issue by koorb** [digitalocean/doctl#76]
Is anyone else finding that typing `doctl auth login` does not open a new browser window but outputs the usage and the error:

```
Error: access token is required
```

… well I thought that was what this command was suppose to figure out for me!?

I'm running OS X 10.11.4 — zsh shell and Safari is my primary browser if it helps.

**Comment by vkurchatkin** [comment]
Same for me

**Comment by brianjking** [comment]
Same as @koorb with the exception of Chrome is my default browser.

**Comment by brianjking** [comment]
I created the `.doctlcfg` file in my home directory and obtained an API token manually and was able to execute `doctl auth login` successfully this time.

If you go this route make sure you enter: `access-token:` prior to your token in the config file.

**Comment by vkurchatkin** [comment]
It seems that digital ocean just deleted existing tokens and also there is a bug in `auth login`

**Comment by cwinebrinner** [comment]
How in the world did this version make it past testing?

**Comment by bryanl** [comment]
`doctl auth login` will be removed in the next release and replaced with a simpler `doctl auth init` command that will create the initial configuration.
