### ISSUE TITLE
SSH Agent Forwarding

### ISSUE THREAD

**Issue by sebgie** [digitalocean/doctl#77]
First and foremost, this tool is great and it makes my work a lot easier! Thank you!

One of the things I use quite often is SSH agent forwarding (`ssh -A user@server`) for example for deployment tasks. I wonder if it would be possible to add this functionality to the `doctl compute ssh <droplet-name>` command?

**Comment by bryanl** [comment]
I concur. This is an idea on the list. I want to make this available sooner than later. I'll make sure to update this issue with the status.

**Comment by bryanl** [comment]
Support for ssh agent forwarding is now in master. A new release including this support will be shipped soon.
