### ISSUE TITLE
Wait for initialization, with cloud-init

### ISSUE THREAD

**Issue by waghanza** [digitalocean/doctl#773]
Hi,

Using `--wait` switch allow us to wait until `droplet` is available.

Is there a way to wait for its setup, preferably with *cloud-init* ?

I mean I am setuping my `droplets`, with *cloud-init*, and I want to wait until the process has ended (all my packages are setup ...).

Regards,

**Comment by bentranter** [comment]
Hey @waghanza,

There's no way to wait for a Droplet's cloud-init script to be setup with `doctl`.

With that said, cloud-init has a "[phone home](https://cloudinit.readthedocs.io/en/latest/topics/modules.html#phone-home)" feature that lets you pass a URL that the cloud-init script sends an HTTP POST request to, to indicate that the script has completed. That's probably the closest way to approximate the behaviour you're looking for, but does require you to run a web server to handle those HTTP POST requests.

If there's anything I can do to help you, or if you'd like an example of this, feel free to let me know. 🙂

**Comment by waghanza** [comment]
Thanks for the tips. Unfortunately, I use `cli` to build my `droplet`.

The only way I found is to create `droplets` with `cloud-init` >= 19 and to wait (sleep) while I get the status (`cloud-init status` through **SSH**) _done_
