### ISSUE TITLE
Allow for setting expiry time for `kubernetes cluster kubeconfig` commands

### ISSUE THREAD

**Issue by andrewsomething** [digitalocean/doctl#791]
When I'm using `doctl` as part of a CI/CD process, I want to be able to set a custom expiration time when calling `kubernetes cluster kubeconfig {save,show}` so that I can feel secure and not have long lived API tokens that need to be manually cleaned up.

This is supported in the API and in godo:

https://developers.digitalocean.com/documentation/v2/#retrieve-the-kubeconfig-for-a-kubernetes-cluster
https://godoc.org/github.com/digitalocean/godo#KubernetesClusterCredentialsGetRequest

Related issue:  https://github.com/digitalocean/action-doctl/issues/30

**Comment by Ka1wa** [comment]
Quickly looking through the code it seems that the code that would have to be changed for this is here:

https://github.com/digitalocean/godo/blob/f16bb6067e44de615df9c9980ab9735edce033c3/kubernetes.go#L495

**Comment by QNester** [comment]
any updates? :)
