### ISSUE TITLE
kubernetes node-pool errors

### ISSUE THREAD

**Issue by silgon** [digitalocean/doctl#793]
**Problem 1:**
I used the following command:

`doctl kubernetes cluster create cluster-name --region ams3 --node-pool name=your-name;size=-1vcpu-2gb;count=1`

However, the count seems not to work because 3 nodes were created. Note: as you see, I misspelled the size parameter, that might be the reason, but I didn't realized at the moment. You should throw me an error in that case. (not sure if that's the reason because I changed it on the interface later)

**Problem 2: (documentation)**
![image](https://user-images.githubusercontent.com/901061/80527686-0ed20a00-8995-11ea-88d9-1f12601c8510.png)

Reversed min-nodes and max-nodes.

**Comment by silgon** [comment]
And, since we are here. Can you tell me an example of the auto scale please? I tried:

```
$ doctl kubernetes cluster create test2 --region ams3 --node-pool name=test-node;size=s-1vcpu-2gb;count=1;min-nodes=1;max-nodes=2;auto-scale=true;
Error: POST https://api.digitalocean.com/v2/kubernetes/clusters: 422 validation error: 3 additional nodes but not enough available droplet limit
min-nodes=1: command not found
max-nodes=2: command not found
auto-scale=true: command not found
```
So, first, I'm not trying to create 3 nodes, then it tells me the parameters in the documentation are not found.

**Comment by andrewsomething** [comment]
Hi @silgon,

Thanks for flagging this issue for use. It looks like the docs need improvement here. Instead of:

    doctl kubernetes cluster create test2 --region ams3 --node-pool name=test-node;size=s-1vcpu-2gb;count=1;min-nodes=1;max-nodes=2;auto-scale=true;

you need to use:

    doctl kubernetes cluster create test2 --region ams3 --node-pool "name=test-node;size=s-1vcpu-2gb;count=1;min-nodes=1;max-nodes=2;auto-scale=true"

Without the surrounding quotes, your shell is breaking the command at the `;` causing the defaults to be used.

**Comment by silgon** [comment]
Ohh... I see. Thanks for your quick reply. I'll test it some other time (I don't intent to test it know since I already have the cluster up, and it would be just wasting some cents for not too much). =)
