### ISSUE TITLE
node not deleted with kubectl delete

### ISSUE THREAD

**Issue by silgon** [digitalocean/doctl#795]
Yesterday I created a node pool with the parameters `min=1` and `max=2`. Since at the beginning they were 2 nodes, I decided to force deletion (instead of waiting automatic deletion), I did it with `kubectl delete nodes name-38wa7` where `name-38wa7` was the name of my alternate node.

You can see when you check on the command line that the node has been deleted:
```
$ kubectl get nodes
NAME              STATUS   ROLES    AGE   VERSION
name-38wam   Ready    <none>   15h   v1.16.6
```

However, today, just by chance I look into my user interface and to my surprise the other node was still up.
![image](https://user-images.githubusercontent.com/901061/80591285-b8f57480-8a1d-11ea-824a-cc1694d7acd7.png)

Can you clarify why is this happening? As far as I understand, the second node is going to be created only as needed. I didn't have any processes in the cluster (I just starting configuring a couple of hours ago).

**Comment by silgon** [comment]
**Update:** after posting the message I decided to delete manually (with the web interface) the node `name-38wa7` and the system just blocked. On the interface everything is frozen:
![image](https://user-images.githubusercontent.com/901061/80592190-4c7b7500-8a1f-11ea-8b0a-4aded639d588.png)
And my processing changed from running to pending:
![image](https://user-images.githubusercontent.com/901061/80592226-6321cc00-8a1f-11ea-96e1-57028fb7222e.png)
Guys... I have the feeling that I'm troubleshooting the application. Help me out here. In any case I'll remove if I got another problem, I'll let you know.

**Comment by andrewsomething** [comment]
The DigitalOcean Kubernetes serivce does not currently support managing nodes directly with `kubectl`. Nodes are "owned" by DOKS, so all delete requests should go through the DOKS API/UI. You can do this via `doctl` with:

    doctl kubernetes cluster node-pool delete-node <cluster-id> <node-pool-id> <node-id>

I've let the DOKS team know about your experience. Thanks for the feedback!
