### ISSUE TITLE
Do not use this digitalocean!

### ISSUE THREAD

**Issue by Vendin** [digitalocean/doctl#799]
Hi.
I have been waiting for VPC functional for several weeks. #415
When it was added, I immediately used it in my project.
And Digitalocean blocked my account without explaining the reasons and did not tell me anything.
I lost work on which I worked for several weeks.
I urge everyone to use anything AWS, GCP, Azure, but not this garbage ocean.
Digitalocean doesn't care about its customers!

**Comment by andrewsomething** [comment]
Hi @Vendin,

I'm sorry to hear about the problem with your DigitalOcean account. Issues on GitHub are not a good way to resolve account problems. Please reach out directly to our support team for assistance:

https://www.digitalocean.com/support/
