### ISSUE TITLE
doctl compute ssh fails on ubuntu 20.04 with snap

### ISSUE THREAD

**Issue by llimllib** [digitalocean/doctl#809]
**Describe the Issue:**

`doctl compute ssh` fails on a nearly-vanilla ubuntu 20.04 system

1. Install doctl in the recommended way from a snap on a nearly-vanilla ubuntu 20.04
2. log in with `doctl auth init`
3. try to ssh into a server, and see it fail:

```
$ doctl compute ssh <servername>
/etc/ssh/ssh_config: line 19: Bad configuration option: include
/etc/ssh/ssh_config: terminating, 1 bad configuration options
Error: exit status 255
```

**Environment:**

 - doctl version:
```
doctl version 1.43.0-release
Git commit hash: 1b6d0b8
```
 - OS: Ubuntu 20.04
 - Installation method: snap

Seems very related to #385; ssh works fine in the non-snap version

**Comment by andrewsomething** [comment]
Unfortunately, support for include directives was added in OpenSSH 7.3, but the version of OpenSSH provided by the Snap core is only 7.2.

```
$ cd ~
asb@asb-home:~$ snap run --shell doctl
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

asb@asb-home:/home/asb$ ssh -V
OpenSSH_7.2p2 Ubuntu-4ubuntu2.8, OpenSSL 1.0.2g  1 Mar 2016
```

From: https://www.openssh.com/txt/release-7.3

> New Features
> ------------
> 
>  * ssh(1): Add an Include directive for ssh_config(5) files.

There is a related bug upstream: https://bugs.launchpad.net/snappy/+bug/1871827

**Comment by andrewsomething** [comment]
I've published a pre-release build using a `core20` base Snap to the doctl edge channel. If anyone is experiencing this issue and can not use one of the existing work-a-rounds, you can install this version using:

    snap install --channel=edge doctl

Or update from the stable version with:

    snap refresh --channel=edge doctl
