### ISSUE TITLE
Create list of different droplet sizes and image names for reference on docs

### ISSUE THREAD

**Issue by zwhitchcox** [digitalocean/doctl#814]
**What is the problem this feature would solve? Please describe.**
I have no idea what the available names for the images are when using doctl. And when I try just some random name, it does not give me a list of options. Where are we supposed to find the list of options? If there is a list somewhere, it needs to be easier to find.

 Thank you for all you do :)
**Describe the solution you'd like**
Ideally, you would have the list of possible options for images here:
https://www.digitalocean.com/docs/apis-clis/doctl/reference/compute/droplet/create/

or on the github docs, even better on the README

**Comment by andrewsomething** [comment]
Thanks for the feedback. I think we can definitely make this more clear in the help output (which is what that docs page is generated from).

Check out these commands to find the sizes and images:

`doctl compute size list` will list the available Droplet sizes.
`doctl compute image list-distribution` will list the available base Linux images available.

**Comment by zwhitchcox** [comment]
Thank you!
