### ISSUE TITLE
I am unable to automatically remove Access Tokens generated by doctl registry auth

### ISSUE THREAD

**Issue by bockelie93** [digitalocean/doctl#817]
**Describe the Issue:**
In my pipeline, I get access to my docker registry with the command _doctl registry login_. This generates an API Token, which never expires (oldest is 19 days, so I assume it doesn't expire). For every pipeline run another Access Token is generated, which obviously is a problem over time when it doesn't expire.

In short:
- doctl auth init -t my-token
- doctl registry login
- docker build and push...
- doctl registry logout

**Environment:**
Inrelevant

**Additional Details:**

Somewhat related to https://github.com/digitalocean/doctl/issues/791

**Comment by andrewsomething** [comment]
Thanks for opening this issue. This PR already merged to master adds a `--expiry-seconds` flag to the  `doctl registry login` command to allow for creating short lived tokens for this use case: https://github.com/digitalocean/doctl/pull/808 It will be part of the next release.

**Comment by bockelie93** [comment]
Awesome, @andrewsomething !

https://github.com/digitalocean/doctl/issues/818 can likely be dropped then.

**Comment by andrewsomething** [comment]
`doctl` v1.44.0 is now available for download including this feature.
