### ISSUE TITLE
I cannot set the expiry time for doctl auth init generated tokens

### ISSUE THREAD

**Issue by bockelie93** [digitalocean/doctl#821]
Describe the Issue:
I use **doctl auth init** in my pipeline to grant helm access to our cluster. The access token that is generated expires after a week, but I wish I could have more short-lived access tokens. i.e. 1 hour, 10 minutes.

Environment:
Inrelevant

Additional Details:

Somewhat related to #791
https://github.com/digitalocean/doctl/issues/817 (basically the same issue, less severe)

**Comment by andrewsomething** [comment]
`doctl auth init` does not generate a token. You must provide one generated in the control panel.

The following commands all generate an API token and each accepts the `--expiry-seconds` argument to produce short-lived tokens:

    doctl  kubernetes cluster kubeconfig save
    doctl  kubernetes cluster kubeconfig saveshow
    doctl registry login

Being able to produce a short-lived token from the control panel something we should support in the future, but that is out of scope for `doctl` itself.

Please feel free to re-open the issue if you feel I've misunderstood it.
