### ISSUE TITLE
doctl didn't create $HOME/.doctlcfg file

### ISSUE THREAD

**Issue by nolan-interactive** [digitalocean/doctl#83]
No sure why, but ran the following command after installing `doctl` using Homebrew (Mac OS, El Capitan, v10.11.5).

```BASH
doctl auth login -t (my token)
```

Output: `updated access token`

But no `.doctlcfg` file was created in $HOME.

**Comment by bryanl** [comment]
This is a know issue. In the mean time, you can create a a file named .doctlcfg in home with the following contents:

```yaml
access-token: <your access token>
```
or you can set `DIGITALOCEAN_ACCESS_TOKEN` in the your environment.

**Comment by nolan-interactive** [comment]
Thanks, I figured either of the two options would work-around the issue, I couldn't locate the format of the .doctlcfg file though.

**Comment by bryanl** [comment]
Glad to be of help. Create more issues if you see any weirdness.
