### ISSUE TITLE
doctl tries to create ~/.config even if -c provided

### ISSUE THREAD

**Issue by wlonkly** [digitalocean/doctl#833]
**Describe the Issue:**

I'm calling doctl as `doctl -c /etc/doctl/config.yaml`, since it's running in a cronjob, but it still refuses to run because it can't create `/root/.config`. 

It should not care about `$HOME/.config` when `-c` is provided.

(That it fails to create it when installed by snap is #591 -- _this_ bug report is that it shouldn't try, regardless of whether it's installed as a snap or anything else.)

**Environment:**

 - doctl version: 

```
# doctl version
Error: mkdir /root/.config: permission denied
```

Haha, just kidding 🤪

```
doctl version 1.45.1-release
Git commit hash: 1041a0e5
```

 - OS: Ubuntu 18.04
 - Installation method: snap

**Comment by wlonkly** [comment]
(I should add that I'm happy to take a swing at fixing it once there's agreement about how it should work.)

**Comment by andrewsomething** [comment]
Hi @wlonkly,

Thanks for raising this issue. I agree that not attempting to create the directory when `-c` is provided would be a better experience. If you're interested in taking a shot at implementing this, please do! Let us know if there's anything we can do to help. This might take a bit of unwinding as it currently happens very early in the process.
