### ISSUE TITLE
Add command Get and List to volume-actions

### ISSUE THREAD

**Issue by tonybolzan** [digitalocean/doctl#834]
**What is the problem this feature would solve? Please describe.**
Without commands `Get` and `List` in `doctl compute volume-action` I don't have a sane way to see if the snapshot has ben take on not.

**Describe the solution you'd like**
The VolumeActionsService on `do/volume_actions.go` have a Get and List signature
I beleave only `commands/droplet_actions.go` don't have a bind to.

**Additional context**
This solution keep in sync with https://developers.digitalocean.com/documentation/v2/#list-all-actions-for-a-volume

**Comment by danaelhe** [comment]
Thank you for the suggestion. Closed via #945 and #940
