### ISSUE TITLE
Allow picking the context’s name in `doctl kubernetes cluster kubeconfig save`

### ISSUE THREAD

**Issue by vandrijevik** [digitalocean/doctl#856]
**What is the problem this feature would solve? Please describe.**
Currently, `doctl kubernetes cluster kubeconfig save <NAME>` saves a `kubectl` context named `do-<REGION>-<NAME>`. This makes it difficult to use `doctl` in continuous integration runs, because the name it configures `kubectl` with depends on also knowing the region of the cluster.

**Describe the solution you'd like**
Adding an `--alias=name` option (I picked that name from `aws eks update-kubeconfig`), which saves authentication information under the specified context, would allow control over the context’s name. By making the name predictable, we can then use it elsewhere in CI pipelines, or other scripts locally.

**Comment by vandrijevik** [comment]
Closing, since this hasn’t had any sort of response or reaction in a few months.

**Comment by andrewsomething** [comment]
Hi @vandrijevik, 

Sorry for the lack of communication. I think this is a great suggestion and we have an internal ticket to implement it. Unfortunately, the team has other priorities at the moment. 

I'd be happy to review/accept a PR. If anyone is interested in working on this, here's a bit of context. We return the config here:

https://github.com/digitalocean/doctl/blob/a901a7278a7370ecc3cee919568c4653c1e1973f/commands/kubernetes.go#L1070

The config is a https://godoc.org/k8s.io/client-go/tools/clientcmd/api#Config

After checking for the flag, renaming the context might look something like:

	remoteKubeconfig.Contexts[alias] = remoteKubeconfig.Contexts[remoteKubeconfig.CurrentContext]
	delete(remoteKubeconfig.Contexts, remoteKubeconfig.CurrentContext)
	remoteKubeconfig.CurrentContext = alias

**Comment by vandrijevik** [comment]
Cheers, thanks for letting me know @andrewsomething! I’m glad to read that this is on your radar :)

**Comment by andrewsomething** [comment]
Fixed via https://github.com/digitalocean/doctl/pull/1075
