### ISSUE TITLE
how to create a droplet from an image??

### ISSUE THREAD

**Issue by 5201413** [digitalocean/doctl#857]
how to create a droplet from an image??

**Comment by andrewsomething** [comment]
You need to pass the `--image`  when creating a Droplet. Public images have easy to remember "slugs" that you can reference, e.g.:

```
doctl compute droplet create \
  --image ubuntu-20-04-x64 \
  --size s-1vcpu-1gb \
  --region nyc1 \
  example.com
```

While private images like snapshots must be referenced by ID, eg:

```
doctl compute droplet create \
  --image 34566353 \
  --size s-1vcpu-1gb \
  --region nyc1 \
  example.com
```

You can find the ID's of your snapshots with: `doctl compute image list-user`
Or for public base images: `doctl compute image list-distribution`

Hope that answers your question. Let us know if you have any more!

**Comment by 5201413** [comment]
why not --domain example.com
