### ISSUE TITLE
address droplets by name

### ISSUE THREAD

**Issue by perler** [digitalocean/doctl#86]
currently every action (shutdown, snapshot etc) needs the ID as parameter. this is not very practical for scripting things like this. Will it be possible to give these actions the Name of the droplet as parameter?

shutdown_and_update.sh

```
#!/bin/sh
doctl compute droplet-action shutdown my.droplet.com
doctl compute droplet-action snapshot my.droplet.com
 --snapshot-name my.droplet.com
```

restore_and_wakeup.sh

```
#!/bin/sh
doctl compute droplet create my.droplet.com   --size 8gb  --image my.droplet.com --region nyc1
doctl compute droplet-action power-on my.droplet.com
```

**Comment by bryanl** [comment]
Hello, I think this is a valid suggestion, and I have questions about failure cases. Nothing prevents you from giving two (or more) Droplets the same name. What would you expect to happen in that case?

**Comment by perler** [comment]
right, I didn't realise, that you indeed can create multiple droplets with the same name. In this case doctl should simply spit out an error..

**Comment by rasodu** [comment]
Few more things to keep in mind
 - If droplet B's name is same as droplet A's ID(Unlikely to happen)
 - If someone changes name of a droplet or creates a new droplet in web interface.(Add a command to refresh internal droplet id/name cache OR refresh cache when ```doctl compute droplet list``` is executed)

**Comment by snoopdouglas** [comment]
Something else to note here is that it's completely possible to give a droplet a name that could be identical to a droplet ID (ie. a completely numeric string). So it'd probably be safest to explicitly specify that a name is being addressed, eg.:

```
doctl compute droplet-action shutdown 12345678
doctl compute droplet-action shutdown --name 12345678
```

**Comment by mauricio** [comment]
As we move more and more towards tags, we'll start using them for this kind of operations, once APIs move more into this direction we should have a better perspective on this but names are mostly for UI only.
