### ISSUE TITLE
Apps integration test fails to check a returned error

### ISSUE THREAD

**Issue by bentranter** [digitalocean/doctl#867]
### Overview

Our [Go Report Card](https://goreportcard.com/report/github.com/digitalocean/doctl) shows that we're failing to get a perfect score on the `ineffassign` check due to a [single error](https://goreportcard.com/report/github.com/digitalocean/doctl#ineffassign). That error is in our integration testing suite, and it's that our apps integration test fails to check a returned error.

### How to fix it

1. Clone this repo.
2. If you haven't already, install Go through their [official installer](https://golang.org/dl/).
3. In [`doctl/integration/apps_spec_test.go:145`](https://github.com/digitalocean/doctl/blob/master/integration/apps_spec_test.go#L145), we're failing to check the `err` returned from the `json.Marshal(testAppSpec)` call. Just below that line, you'll need to add an `expect.NoError(err)` statement.
4. Open a pull request to this repo with your changes. If you want, mention this issue in your pull request by writing something like, "Closes #867" which will close this issue upon being merged.

**Comment by kadern0** [comment]
Happy to take this one!
