### ISSUE TITLE
Several misspellings in doctl

### ISSUE THREAD

**Issue by bentranter** [digitalocean/doctl#870]
### Overview

There are several misspellings in our codebase. These can be found with the Go tool [misspell](https://github.com/client9/misspell).

### How to fix it

1. Clone this repo.
2. If you're using the `misspell` tool, you'll notice that there are quite a few issues reported. Most of these are in vendored code, so to make it easier, these are the only ones affecting this actual codebase:
    1. `commands/account.go:27:65`: "retreive" is a misspelling of "retrieve"
    2. `commands/certificates.go:85:36`: "comfirmation" is a misspelling of "confirmation"
    3. `commands/image_actions.go:48:123`: "inlcuding" is a misspelling of "including"
    4. `commands/completion.go:165:35`: "commmand" is a misspelling of "command"
    5. `integration/cdn_create_test.go:84:11`: "orgin" is a misspelling of "origin"
    6. `integration/cdn_create_test.go:100:46`: "orgin" is a misspelling of "origin"
3. Once those misspellings have been fixed, open a pull request to this repo with your changes. If you want, mention this issue in your pull request by writing something like, "Closes #870" which will close this issue upon being merged.

**Comment by nadyafebi** [comment]
Hi! I'd love to work on this 😄
