### ISSUE TITLE
Way to delete image tags from DO container registry

### ISSUE THREAD

**Issue by madfromplay** [digitalocean/doctl#880]
**What is the problem this feature would solve? Please describe.**
I am looking for suitable way to cleanup docker container registry in digital ocean. It would be perfect if this will be possible with doctl 

**Describe the solution you'd like**
I want to be able to fetch list of image tags from my registry, eg:
doctl registry my-registry/myproject list
my-registry/myproject:tag1
my-registry/myproject:tag2
my-registry/myproject:tag3

doctl registry my-registry/myproject:tag1 delete

**Additional context**
As i understood there is only one way to delete images at this moment - via UI - This is not acceptable in case i have 150+ images build per day

Thanks in advance

**Comment by andrewsomething** [comment]
The API has recently gained endpoints that would enable this:

https://developers.digitalocean.com/documentation/v2/#delete-container-registry-repository-tag

**Comment by scotchneat** [comment]
@madfromplay doctl has a way to do this through the `repository` commands.

List images:
`doctl registry repository list`

List tags for an image:
`doctl registry repository list-tags <image-name>`

Delete tags of an image:
`doctl registry repository delete-tag <image-name> <tag>`

Does this give you what you need?

**Comment by scotchneat** [comment]
I'm going to close this issue. @madfromplay if my answer isn't in line with what you need, please feel free to reopen this issue.
