### ISSUE TITLE
Doctl Returns 500 Error When deploying app.yaml to DO App Platform

### ISSUE THREAD

**Issue by LuisOsta** [digitalocean/doctl#883]
**Describe the Issue:**
I've created a YAML spec for my DO App Platform based on the sample on this repository.

Which looks like this:

```
name: unique-expressions

services:
  - name: api
    environment_slug: node-js
    github:
      repo: Valencian-Digital/unique-expressions
      branch: main
      deploy_on_push: true
    source_dir: api
    routes:
      - path: /api
```

But when I try to execute `doctl apps create --spec .do/app.yaml`. 

It returns a 500 Error and nothing else. I've tried executing the command both in a Github action and locally with different API tokens. I'm able to access other resources on my DO account but I can't successfully create the spec.

Do you know what could be going wrong?

**Environment:**
 - doctl version: 1.48.1
 - OS: Windows WSL 2 & Ubuntu (Github Actions)
 - Installation method: Installed from Brrew & Through Github Action

**Additional Details:**
This is the specific error I get back from doctl:
`Error: POST https://api.digitalocean.com/v2/apps: 500 Server Error`

This is the output of the command with the trace flag turned out.
P.S. I formatted to be more readable.

```
doctl: 2020/10/15 12:16:14 -> "POST /v2/apps HTTP/1.1\r\n
Host: api.digitalocean.com\r
User-Agent: doctl/1.48.1-release (linux amd64) godo/1.46.0\r
Content-Length: 237\r
Accept: application/json\r
Content-Type: application/json\r
Accept-Encoding: gzip\r\n\r\n

{\"spec\"
:{\"name\":\"unique-expressions\",
\"services\":[
      {\"name\":\"api\"
      ,\"github\":
           {\"repo\":\"Valencian-Digital/unique-expressions\"
           ,\"branch\":\"main\"
           ,\"deploy_on_push\":true
          }
     ,\"source_dir\":\"api\"
     ,\"environment_slug\":\"node-js\"
     ,\"routes\":[{\"path\":\"/api\"}]}]}}\n"

doctl: 2020/10/15 12:16:15 <- "HTTP/2.0 500 Internal Server Error\r\n

Content-Length: 59\r\nCf-Cache-Status: DYNAMIC\r\nCf-Ray: 5e2b2fd229a50ec2-DFW\r\nCf-Request-Id: 05cedc375d00000ec2bc955000000001\r\n

Content-Type: application/json\r\nDate: Thu, 15 Oct 2020 17:16:16 GMT\r\nExpect-Ct: max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"\r\nServer: cloudflare\r\nSet-Cookie: __cfduid=d6649d4345922d7d76e72b342f07c99d81602782175; expires=Sat, 14-Nov-20 17:16:15 GMT; path=/; domain=.digitalocean.com; HttpOnly; SameSite=Lax\r\nX-Gateway: Edge-Gateway\r\nX-Request-Id: 8981250f-c646-45c5-a0ad-5c54c83bf8fa\r\nX-Response-From: service\r\n\r\n{\"id\": \"Internal Server Error\", \"message\": \"Server Error\" }"


```

**Comment by andrewsomething** [comment]
Hi @LuisOsta, 

Looks like we need to respond with a better error message here. Looking up your request ID in our internal systems, I see:

```
getting github latest commits: getting repo branch commit: getting repo branch commit: GET https://api.github.com/repos/Valencian-Digital/unique-expressions/branches/main: 404 Branch not found []
```

Can you double check the branch name for your app?

**Comment by LuisOsta** [comment]
@andrewlouis93 You were right on the money. My branch was master, not main which caused the issue. And yeah it'd be great to get some better error messaging on that.

**Comment by andrewsomething** [comment]
Closing this as a doctl issue as the App Platform team has a task on their end to return a better error via the API.
