### ISSUE TITLE
Add a way to see private IP of the machine

### ISSUE THREAD

**Issue by vsviridov** [digitalocean/doctl#89]
I have a scenario, when I need to generate SSL certificates for a bunch of machines in the cluster. It would be nice if the output of `doctl compute droplet [create|list]` included the private ip (provided `--enable-private-networking` was issued).

Right now I have to manually ssh (since `doctl compute ssh` doesn't seem to take commands) into the box and run scripts to get that information, which is really inconvenient.

**Comment by vsviridov** [comment]
MacGyver solution combinding `doctl` access credentials, APIv2, and `jq`

```
curl -s -X GET -H "Content-Type: text/plain" -H "Authorization: Bearer $(cat ~/.doctlcfg | awk '{print $2}')" https://api.digitalocean.com/v2/droplets/${machine_id} | jq '.droplet.networks.v4[] | select(.type=="private") | .ip_address'
```

**Comment by bryanl** [comment]
Yes, only the public IPv4 address is easily accessible, but there is still a way:

```sh
doctl compute droplet get <dropletID> -o json | jq -c '.[0].networks.v4[] | select(.type=="private").ip_address'
```

You don't need curl. The key points here is that every command has JSON output than you can mangle with `jq`

**Comment by vsviridov** [comment]
Right, missed the fact that `doctl` provides json output (see my temporary solution above).
Still, would be nice to just have that and not depend on external dependency like `jq`

**Comment by bryanl** [comment]
I think ultimately we shouldn't hardcode every single thing in, but if doctl provided a a way to get at the raw JSON a bit easier, it wouldn't be too bad. Perhaps the easy way would be allow [go template](http://golang.org/pkg/text/template/#pkg-overview), and JSON path support, so you could do something like

`doctl compute droplet get <dropletID> --go-template="whatever"` or
`doctl compute droplet get <dropletID> --jsonpath="whatever"`

**Comment by bryanl** [comment]
Created new issues to add these two features in #95 and #96.

**Comment by kapaggar** [comment]
Lists both public and private IP list of all your DO droplets

`doctl compute droplet list -o json |jq -r  '.[]| "\(.id)\t\(.name)\t\(.networks.v4[].ip_address)"'`
