### ISSUE TITLE
auth init is freezing after OK

### ISSUE THREAD

**Issue by prepetti65** [digitalocean/doctl#891]
Hello,

I installed doctl 1.48.1 on Windows 10Pro v1909, by downloading the executable from the relases page.

I created an API token and I am trying to initialize.

The command doctl auth init accepts the token, but after writing OK it freezes and never goes back to prompt, I have to kill the CMD session.
 I have tried with --trace option. The response is 200 OK but it freezes as well.

![immagine](https://user-images.githubusercontent.com/73177642/96596446-01b32980-12ed-11eb-9548-f8bed1de13a7.png)

**Comment by prepetti65** [comment]
I see no response here. Should I open a ticket to DigitalOcean directly ?

**Comment by prepetti65** [comment]
Hi,

the file is created in the path you mention but it's empty, is that correct ?

Thanks

**Comment by andrewsomething** [comment]
It should write configuration information in the file, including most importantly a line like:

```
access-token: asecretaccesstokenhere
```

or in your case ,since you passed `ictadmin1` as a context:

```
auth-contexts:
  ictadmin1: asecretaccesstokenhere
```

Does `doctl` function as expected if you manually configuration information?

**Comment by prepetti65** [comment]
Is that the only info the file should contain ?

And: should I execute doctl in an elevated CMD ?

Thank you

**Comment by andrewsomething** [comment]
That's the only information that it needs to contain. You shouldn't need elevated permissions unless for some reason you do not have read/write access to `%appdata%\doctl\config.yaml`

**Comment by prepetti65** [comment]
Hello,

doctl works after having manually filled the config file as suggested.

Thank you
