### ISSUE TITLE
`doctl compute droplet get <droplet-id|droplet-name>`

### ISSUE THREAD

**Issue by DazWilkin** [digitalocean/doctl#895]
**What is the problem this feature would solve? Please describe.**

`doctl compute droplet get` supports only droplet ID whereas `doctl compute droplet delete` supports ID and name

```console
doctl compute droplet get --help

Usage:
  doctl compute droplet get <droplet-id> [flags]

doctl compute droplet delete --help

Usage:
  doctl compute droplet delete <droplet-id|droplet-name>... [flags]
```

**Describe the solution you'd like**

It would be helpful to `doctl compute droplet get <droplet-name>` to save `doctl compute droplet list` and then either `grep`ping the ID  or `--output=JSON` and then `jq`ing it, in order to get values from a specific droplet's configuration.

Or, I'm missing something!?

**Comment by mamercad** [comment]
Something to keep in mind is that Droplet names don't have to be unique:

```
❯ doctl compute droplet list -o json | jq -r '.[] | .name'
hacktoberfest
hacktoberfest
```

**Comment by DazWilkin** [comment]
Aha!

I will start capturing IDs on create.

Thanks @mamercad.

**Comment by mamercad** [comment]
No worries, it's not impossible to implement this functionality, but, it doesn't exist in the [API specification right now for Droplets](https://developers.digitalocean.com/documentation/v2/#retrieve-an-existing-droplet-by-id). The logic of "do we have a single Droplet with that name, if so, return it" would have to be built into `doctl compute droplet get`.

**Comment by DazWilkin** [comment]
How awesome are you!? Thanks
