### ISSUE TITLE
Bash Completion

### ISSUE THREAD

**Issue by Grynn** [digitalocean/doctl#90]
Feature request: We need bash completion...

doctl <tab> should show compute, account, auth ...

**Comment by andrewsomething** [comment]
Running this little program will create a bash completion file for doctl.

```go
package main

import "github.com/digitalocean/doctl/commands"

func main() {
	cmd := commands.Init()
	cmd.GenBashCompletionFile("doctl.sh")
}
```

Save it as `doctl-bash.go` and then with the go compiler installed, you can run it with `go run doctl-bash.go` It will produce a file called `doctl.sh` which if you can place in `/etc/bash_completion.d/`

The question is how to best get it in the hands of the user. We could create it as part of the build/release process. Then homebrew (and hypothetical rpms/debs) could install it. An alternative might be to add a new command that does this. For instance, Hugo provides a genautocomplete sub-command.

**Comment by bryanl** [comment]
This is currently on the plate. I'm thinking bash, zsh, and fish (mostly because I use it) for the first version.

**Comment by Grynn** [comment]
For what it's worth I'd suggest generating the completion as part of the build process; then homebrew (or rpm/deb) can just copy it into the right place. (As suggested by @andrewsomething). 

```
$>brew info git
...
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completion has been installed to:
  /usr/local/share/zsh/site-functions
```


The one other way I've seen it work, which is much harder, is to have a stub completion that actually executes `doctl compute --help --porcelain` or similar and then uses that to compute the completion. This can take into account chars you've already typed. So `doctl compute droplet delete abc-` would complete names beginning with `abc-`. See this: https://github.com/HiroKws/ArtisanBashCompletion for a pretty awesome example.

**Comment by Grynn** [comment]
Also @andrewsomething 

```
$ go get github.com/digitalocean/doctl/commands
# cd /Users/vishal/src/golang/src/github.com/digitalocean/doctl; git submodule update --init --recursive
fatal: No url found for submodule path 'vendor/github.com/vektra/errors' in .gitmodules
package github.com/digitalocean/doctl/commands: exit status 128
```

**Comment by biji** [comment]
@andrewsomething please share resulted script.sh

**Comment by andrewsomething** [comment]
@biji Sure thing. This is the output for 1.3.0: https://gist.github.com/andrewsomething/7ba993a7f7897936c6946ffed2f1edc6

**Comment by stormbeta** [comment]
@andrewsomething It looks like you want `DoitCmd` instead of `Init()` in your example to generate the completion script.

**Comment by jyundt** [comment]
@bryanl @Grynn Would it be possible to do something similar to what [kubernetes](https://kubernetes.io/docs/user-guide/kubectl/kubectl_completion/) does with kubectl + bash auto completion?

**Comment by xmudrii** [comment]
@jyundt I think, yes, it would be possible.
[spf13/cobra/bash_completions.md](https://github.com/spf13/cobra/blob/master/bash_completions.md) explains this feature on example of Kubernetes/kubectl.
If no one else takes it before me, I'll be taking on this issue very soon.
