### ISSUE TITLE
Improve error message when providing non-numeric droplet id

### ISSUE THREAD

**Issue by mloughran** [digitalocean/doctl#928]
**Describe the Issue:**

As a new user of `doctl`, I mistakenly tried to use using the droplet's name rather than the id when triggering actions. Since the error isn't clear, it took me longer than I'd like to admit to figure out what I was doing wrong.

For example

```shell
% doctl compute droplet-action power-off not-an-id
Error: strconv.Atoi: parsing "not-an-id": invalid syntax
```

An error such as this would have been helpful:

```shell
% doctl compute droplet-action power-off not-an-id
Error: expected <droplet-id> to be numeric, got "not-an-id"
```

**Environment:**
 - doctl version: doctl version 1.54.0-release
 - OS: macOS Big Sur
 - Installation method: Homebrew

**Comment by bentranter** [comment]
Hey @mloughran, thanks for the report. This is a great suggestion – we'll work on this within the next week or so.
