### ISSUE TITLE
Appspec global envs removed on app update

### ISSUE THREAD

**Issue by umgelurgel** [digitalocean/doctl#934]
**Describe the Issue:**

`doctl apps` ignores the global `envs` section of the appspec file. It's misleading when using `doctl apps spec get ${APP_ID}` when the generated appspec file is missing these values, but can be catastrophic when using `doctl apps update ${APP_ID} --spec app.yaml` as this ignores the values in the appspec file and removes all existing global envs from the application.

The global `envs` section is present when exporting the appspec through the gui.

**Environment:**
 - doctl version 1.54.0-release
Git commit hash: a901a727
 - OS: Ubuntu 20.04.1 LTS
 - Installation method: Snap package

**Comment by andrewsomething** [comment]
Thanks for the report. App platform global envs are a new feature that is not yet supported in `doctl`. Looks like we'll need to cut a new godo release with the changes from https://github.com/digitalocean/godo/pull/422 and rebuild doctl with that.

**Comment by umgelurgel** [comment]
Thanks for the quick response and a quick fix!
