### ISSUE TITLE
Replace `doctl auth login` with `doctl auth init`

### ISSUE THREAD

**Issue by bryanl** [digitalocean/doctl#94]
The `doctl auth login` process has a few issues that doesn't allow it to work the same way on every platform. I'm proposing we replace this with a `doctl auth init` that will take a DO token on the command line and do the initial configuration which will include creating a doctl config file.

**Comment by lcherone** [comment]
+1 - KDE user

doctl is useless to me (unless I want to open chrome and goto DO)...
 
`doctl auth login` just opens chrome and asks me to login, does not trigger oauth..
