### ISSUE TITLE
Allow jsonpath traversals through doctl output

### ISSUE THREAD

**Issue by bryanl** [digitalocean/doctl#96]
Add a jsonpath option to allow easy retrieval of specific data from a doctl response. Example:

`doctl compute get 1234 --jsonpath "Networks.V4"` would return the IPv4 networks block from the JSON response. JSON output is assumed with the `jsonpath` option.

**Comment by aybabtme** [comment]
How do you propose traversing arrays?

**Comment by bryanl** [comment]
My first thought is the same way jq does it.

**Comment by mauricio** [comment]
Not much action here, closing out.
