### ISSUE TITLE
Add watch option to Apps Platform create-deployment

### ISSUE THREAD

**Issue by sjparkinson** [digitalocean/doctl#964]
**What is the problem this feature would solve? Please describe.**

I would like a means to wait for an Apps Platform deployment to complete and get a relevent status code back from the command line, to inform a job as part of a build pipeline in GitHub Actions.

**Describe the solution you'd like**

When calling `doctl apps create-deployment` I'd like to pass a `--watch` option so that I can get the command to return once the deployment is completed, with a relevent return status code.

There's a few ways to cut this for sure, so whatever makes the most sense.

**Additional context**

`kubectl` supports this by calling `kubectl rollout status --watch <name>` after applying a change.

https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#-em-status-em-

**Comment by sjparkinson** [comment]
Feel free to get an idea of what I'm trying to achieve in GitHub Actions from https://github.com/sjparkinson/isitup.org/blob/73f9585569060b1de4d4415f5f09f2152f26f37b/.github/workflows/deploy.yaml#L40-L132.

That's my old Kubernetes deployment job, recreating it to tie togther a Apps Platform deployment to a deployment in GitHub is the main aim.

At the moment the auto-deploy from GitHub feature is a bit too keen. In Heroku there is a good option to wait for status checks to pass first before starting a deployment. I figure a `--watch` option is a good interim solution until App Platform is more fully integrated with GitHub and all it's deployment and checks APIs.

**Comment by andrewsomething** [comment]
This sounds like something we should have. It would be consistent with other resources that can take awhile to become ready. Both `doctl compute droplet create` and `doctl kubernetes cluster create` have `--wait` flags that block until the resource has been successfully created.

We have similar logic to what will be needed here in the Terraform provider:

https://github.com/digitalocean/terraform-provider-digitalocean/blob/1f777298a6e1d91b2cfccb6c877fd0970d7d74cf/digitalocean/resource_digitalocean_app.go#L159

**Comment by Shanduur** [comment]
Is there any progrss on this issue? If no one started the work yet, I could try to implement it.

**Comment by andrewsomething** [comment]
@Shanduur It is not actively being worked on. If you're interested in implementing it, I'd be very happy to review/merge. Let me know if you have any questions!

**Comment by Shanduur** [comment]
@andrewsomething should the wait flag be passed during the integration testing?
