### ISSUE TITLE
Remove auth from list

### ISSUE THREAD

**Issue by davisbento** [digitalocean/doctl#965]
**What is the problem this feature would solve? Please describe.**

I need to remove an auth account from my auth list.
Let's say I have 4 accounts from my command 'doctl auth list', I want to remove one of them (or more than one), how can I do it? I searched and didn't find a way to do it.

**Describe the solution you'd like**

Maybe we can create a command like

```
doctl auth remove auth-name
```

**Additional context**

Yeah I know that I can remove the auth from config.yml but it is much easier if there was a command

**Comment by ChiefMateStarbuck** [comment]
Hey Davis. This is a great suggestion. Currently there is no implementation for this feature. We will gladly accept any PR's. My team and I will attempt to find time for this issue, but cannot commit to any allocation of resources at this time.

**Comment by davisbento** [comment]
@ChiefMateStarbuck tks for reply. I have no exp with golang, but i'll try 😁
