### ISSUE TITLE
`doctl registry login` with doctl+Docker snaps uses incorrect (!?) `config.json`

### ISSUE THREAD

**Issue by DazWilkin** [digitalocean/doctl#968]
**Describe the Issue:**

`doctl registry login` provides a helpful (but incorrect?) reminder that:

```console
Warning: Using the doctl Snap? Grant access to the doctl:dot-docker plug to use this command with: sudo snap connect doctl:dot-docker
```

After permitting the change (`sudo snap connect doctl:dot-docker`), the commands updates:

`${HOME}/.docker/config.json`

But, with the Docker snap (and, if using doctl snap, this is more probable), this is incorrect and the command should update:

`${HOME}/snap/docker/current/.docker/config.json`

Manually (there's probably a sweet `jq` way too) moving `auths["registry.digitalocean.com"]`, works (i.e. I can `docker push registry.digitalocean.com/${REGISTRY}/${IMAGE}:${TAG}`)

**Environment:**

 - doctl version:  doctl version 1.57.0-release; Git commit hash: 497c9008

 - OS:  Ubuntu 20.04.2 LTS
 - Installation method:  `doctl` and `docker` under Snap

**Additional Details:**

I don't know of a portable way to determine the location of dockerd's `config.json`.

**Comment by danaelhe** [comment]
Hi there, thanks for bringing this up.

The short and sweet answer here is that there is a work around. `doctl registry login` is just a bit of a convenience. You can login to a DO registry without it via `docker login -u $DO_TOKEN -p $DO_TOKEN registry.digitalocean.com` more info [here](https://www.digitalocean.com/docs/container-registry/how-to/use-registry-docker-kubernetes/#docker-integration).

Now, to dig a little deeper into the perceived behavior- snap is designed to work in strict confinement and only access things (directories, services, etc.) that they have been granted permission for. This works great when they need access to well-defined common things like networking, a camera interface, etc. It's a bit like installing an app on a cell phone. It gets difficult when two arbitrary applications need to interact. There's a related issue on the Docker side that could provide some more info [here](https://github.com/docker-snap/docker-snap/issues/7)

**Comment by DazWilkin** [comment]
Very helpful, thank you!

I like the principle of the containment from using Snaps but, to your point, sometimes using them bite me.
