### ISSUE TITLE
Can't (un)set result limit count

### ISSUE THREAD

**Issue by WoLfulus** [digitalocean/doctl#975]
I made some automation using `doctl` but I just found out (when things broke 😆) that the results are getting limited to 25 and there's no flag to "unlimit" it, thus I assumed it would return all of them.

Basically I have ~40 apps on DigitalOcean App Platform and `doctl apps ls` is showing me only those first 25.

Am I missing something? --help doesn't show any flags to set the return limit

Using latest version on windows and downloaded from releases.

**Comment by andrewsomething** [comment]
DigitalOcean API responses are paginated. Unfortunately, it looks like this was not handled when apps support as initially added to doctl. We'll need to make a few changes to support this.

Thanks for flagging this issue!

**Comment by rijkvanzanten** [comment]
@andrewlouis93 Do you happen to have a clearer overview of the changes that are needed to support this? I'm down to give it a shot in a PR, but I'm not (at all) familiar with the internal of `doctl` (yet) 🙂

**Comment by andrewsomething** [comment]
Hey @rijkvanzanten! Thanks for the offer, but the work is already in progress. Take a look at the linked PRs to see what this involves. If there's another issue that piques your interest, please feel free to tag me. I'd be very happy to break down any needed changes for you.

**Comment by rijkvanzanten** [comment]
So fast! Thanks 👍🏻

**Comment by andrewsomething** [comment]
The fix for this should now be available: https://github.com/digitalocean/doctl/releases/tag/v1.59.0
