### ISSUE TITLE
doctl databases fork existing cluster

### ISSUE THREAD

**Issue by richardwu** [digitalocean/doctl#992]
**What is the problem this feature would solve? Please describe.**
I would like to fork an existing database cluster using `doctl`, similar to how you can do this in the web UI.

**Describe the solution you'd like**
Some command of the form `doctl databases fork <existing-name> <new-name> [flags]`

**Additional context**
Would be more convenient than doing a manual copy using postgres.

**Comment by nibblesnbits** [comment]
Any movement on this?  It's the one thing preventing some current automation efforts.

**Comment by danaelhe** [comment]
Addressed in #1352 

Will be available in the next doctl release.

Thank you for your write up and request!

**Comment by nibblesnbits** [comment]
Is there an ETA for that next release?

**Comment by danaelhe** [comment]
We can cut one next week. I’ll let comment here when we do.

**Comment by danaelhe** [comment]
> Is there an ETA for that next release?

We have cut a new release of doctl- v1.93.0:
https://github.com/digitalocean/doctl/releases/tag/v1.93.0

😄
