### ISSUE TITLE
Removing default auth context

### ISSUE THREAD

**Issue by dandob74** [digitalocean/doctl#999]
Hi, I try to remove the default context, which was initially created by `doctl auth init`.

Executing the command `doctl auth list` displays:
default (current)

How should I remove this context now?
Using the following command  `doctl auth remove --context default` throws an Error: Context not found.

Any help is appreciated.
Cheers,
Daniel

**Environment:**
 - doctl version: 1.61.0-release
 - OS:  macOS Mojave
 - Installation method: MacPorts

**Comment by scotchneat** [comment]
Hi @dandob74, thanks for reporting this bug. It does look like the default auth isn't considered a context and isn't covered in the `remove` function. 

We don't have a timeline for a fix for this issue but certainly encourage contributions. 

Meanwhile, if you need a workaround, the default auth token can be removed from the config file. You can find the file by running `doctl auth -h`. The description for the `--config` global flag will display you the default config file location for your operating system (`/Users/<YOUR_USER>/Library/Application Support/doctl/config.yaml` on MacOS). Removing the top-level key `access-token` will have the effect you're looking for.

**Comment by dandob74** [comment]
Yep, thanks that works!
